#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20200407
CATEGORIA="Editores de audio"

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=audacity
	SRCNAM=Audacity
	EXTENSION=tar.gz
	GESTOR=wget
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=https://github.com/audacity/audacity
	VERSION=$(curl -s $WEB/releases|grep -Po 'title="\K.*(?=")'|grep $SRCNAM-[0-9]|grep -v beta|grep -v rc[0-9]|head -1|cut -d- -f2)
	SOURCES=$SRCNAM-$VERSION.$EXTENSION
	CD=$PRGNAM-$SRCNAM-$VERSION
	DOWNLOAD=$WEB/archive/$SOURCES
}

# Comprobar dependencias
F_dependencias(){
DEPENDENCIAS="libiec61883
libxml++
libconfig
libffado
celt
wxGTK3
jack
ffmpeg
ladspa_sdk
lame
soundtouch
twolame
vamp-plugin-sdk
serd
sord
lv2
sratom
lilv
suil"
f_dependencias
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){  
# Configuramos paquete
echo ""
echo "$VERDE"Configurando ..."$CIERRE"
sleep 1

echo "
/Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj4An/AaFdADCdSKuHgCFyvCmLAj9fPkndrrLdd492L47H
Hxm5eP5iWn52CgdFQS1MN38lW9YvsFepf/8lsbShZn9vFu/m5inVxKWpheParnLLVongaqgAzE+b
uiaHrxkn0jAEPo+BFKKwHKSAa6/k/ipfx8YFKsLZHhKGLizWFAsEu7NLoyvvev9E5bORtUPHotGk
XlQZWn0nebAmPSSEgP8rVyVBrxsB/R9vl9GnXMSTcSMdrQlbGcv4dRDIFmzOSCdgkQF2UmaAQaN6
rVRv3C7FeZRe6DlhljsNinMCspltBufTxWQ20U2dTZPVq4GHBiMsoZq1woCZw3kueqq8Abs1Ypma
yach0OhRhcR2KRn5WofFCe5OQvUtLH0I7BgfBgAB83nsk3NisBiJGOGlufJzC7uJ7mB1nNF2G0E4
rW0Srui/dcARMpSHtGrY0Mh2zHqy6neqvygnB+nav6y0NNBiZepuEAVg1YZmKk65e5bIMQuY3KTD
w97HtbSIOxthC2PuDKZgoxBB5QmwX3L/p4xkRnGJvguCd1ud2uLXLB6MEMwdt1niAAAAAABDmkIs
SIPnpwABvQOAFAAAMRPX1LHEZ/sCAAAAAARZWg==" | base64 -d > $TMP/audacity-ffmpeg.txz
tar xvf $TMP/audacity-ffmpeg.txz &>/dev/null
patch -p1 < audacity-ffmpeg.patch

sed -i "s,lib/vamp,lib$LIBDIRSUFFIX/vamp,g" \
  lib-src/libvamp/src/vamp-hostsdk/PluginHostAdapter.cpp || true

autoreconf -fi

LDFLAGS="-L/usr/lib$LIBDIRSUFFIX" \
CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --enable-unicode \
  --enable-nyquist \
  --with-expat=system \
  --with-lame=system \
  --with-libvorbis=system \
  --with-libmad=system \
  --with-libflac=system \
  --with-libsndfile=system \
  --with-libid3tag=system \
  --with-libsoxr \
  --with-portaudio \
  --with-ladspa \
  --with-ffmpeg=system \
  --with-lv2=system \
  --with-soundtouch=system \
  --with-libtwolame=system \
  --with-libvamp=system \
  --without-libresample \
  --without-libsamplerate

for i in ffmpeg expat lame libid3tag libflac libmad libresample libsndfile libvamp lv2 soundtouch twolame; do
  rm -rf lib-src/$i
done
  
echo ""
echo "$VERDE"Compilamos ..."$CIERRE"
sleep 1
make || exit 1
make install DESTDIR=$PKG

install -D -m 0644 images/AudacityLogo48x48.xpm \
  $PKG/usr/share/pixmaps/$PRGNAM.xpm
  
echo "
/Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj4BH/BQJdADCdSKuHgCFyvCxdYS/Le21Yp/ne7yg8B1xl
1d189uFEczROqUeU8GC70OxtdtoEiJEWzMb2GXzclN+tOThEH0+5gYTfIdd8zWWjYQG34Oxr84A0
6veyd8q+SIGqgxMB4I/mEZM8KMP2FlKNAbwwO+T87GJWaVnpaRz+2Ho+91lONSwi3WJTD+Jqp6Bs
T6cI1rGdd+4YvmlbFP75MySs6HQzBS9rH8wrXVFvgKC1AwN7T7RCd8AC6tRi+TO/YSBsT/TEg0ZG
4dyNzcVOBKqPBUTDl9UInjgjiydEvlj8+Q5U9KXlezg8Pw+2TzXShF+4xpFDMtGd+2qPGp5LjTNU
TdOsFDHudCFDkWWV07asuHCfcus9TWC3FfvcJ+g5tGZInUyuJPklYythJteKYCD6Fdz61eSyisFP
t3ZLKn3iV8zfw3thKXvBSbRJfKGh5/wLGA2r17w9QhwdSwJSNJRLjSNECGwC4/KqSsNX8QBYRQes
OBRAirAtd7ujE7rxw+V80OEfNRwgRnVFlBIpGlQpLbq0HXogoYAFxWmnB0POzWXCFDxqxdk9FVQN
XSuKiO0gJfzWEcybNCyW4Q7+1dXs6IjXTuKsPk9BGa5cD2q/ZM1UBKzxB5Tk3v2RoSudGHFDlXW2
ihLHMqgH45jA4NcF/3Mg0kQmTP5W2sEJn8jLCJe1LDWjfo0CbOW+7mySgCGAydNdq9OW1qzPXaKz
w3/yd5Ytfn55YSELEafSVhHCVMks50R8RYQAvH+wnwoBbdKoqOgSjRuCBZyeHoU+6z6Bi3GFpkI5
yMjQxt5mcSFvpN3cD3ddFy1F75qKfEUC9OQQ6T+4+Eqrspuo4y/QiE7qu7Gs1eCwklkmxC1/DSkR
5QCH4KAgJFORfn+Ul1zg12GZ6eLQg9iOhnGnBD9Mshm4sXBj+LeYGwLjENti+Eq1GnL2oyR+1O+n
iy587CBtM9hWsshBXw9ZaxeoJQcGZSow7Jd8TpgGhrnFCmAg42MT0UURGj/LbQUmOpy0hIntJTQH
tpvMlCn7onwSa7Caa6UDaFZE0hMWTi0FgQQ0kwmdZkjW/dhKwiJMuceh510npwzJxU8eZdBWHNLo
coMTvxgaBGl7aTREOgO4bbjPGjqEwn5mFI0x2XR/GOB/Ixw0bTMEt/olGA0s2eIqVRey+CGItv/2
0+d3amMd97C8SdNKjd07eWXtYe3XVSR0hicLXVwuuPBlr8UtUif6jV/GVteCtpI2lKyWV7QCB5NJ
MBxXJX+NUclzmWotEhNAJYWLKBfhdJegtwkPwXLn2C7BpVpjpqXyX1EpoiqZru+19QwiOc+Yvn9/
58vPBb25wbOm+VeZK8LwBx4hhsNB8RVP6tiNJZt2img1TIE06DVFRu88UAtuA5bW1CyUDLmB9Z5X
RqvYCIoCShBew9EY/lzVbcwaLaHkieHL7/3OyQsVcRfNVsYJjLu8Cdatby0x/YQ9H4F4Ab0P63/Q
l6z9Ru/ZkTiv7JbySOYBD1Y6a9lmd1uHauLLUchqBpLPOh+ygtqAzgNOpD8TADNqVHyMTsAMn7AV
PRI6cKPZRnvn6SBskhpzTEED4AxsM8vzhmDXhjZcKF3UHSgKev5FYh4cg4DHD3kX2qd45pnvcP6V
oPTIWikeeNQVj/bwVO/1+tJEw+R4Vev0zsvtOIwyYpiGbalL/YJDSjg/5i0udMDj9Ti5LkjokpCU
AAAAAADGt2CxQLwhEAABngqAJAAASOOUfLHEZ/sCAAAAAARZWg==" | base64 -d > $TMP/desktop.txz
tar xvf $TMP/desktop.txz &>/dev/null
install -D -m 0644 $PRGNAM.desktop \
  $PKG/usr/share/applications/$PRGNAM.desktop
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del script
f_versionInstalada
# Comprobar dependencias
F_dependencias
#Si no existe el fichero se descargara
f_download
#Descomprimir sources
f_descomprimir
#Cd a ruta
f_cd
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales