#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20240131
CATEGORIA="Editores de video"

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################

F_variables() {
	PRGNAM=avidemux
	EXTENSION=tar.gz
	GESTOR=wget
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=http://fixounet.free.fr/avidemux/download.html
	VERSION=$(curl -s $WEB|grep tar.gz|head -1|sed 's/ //g'|cut -d '>' -f3|cut -d '<' -f1)
	SOURCES=${PRGNAM}_${VERSION}.$EXTENSION
	CD=${PRGNAM}_${VERSION}
	DOWNLOAD=https://downloads.sourceforge.net/avidemux/$SOURCES
}

F_dependencias(){
DEPENDENCIAS="aften
amrnb
amrwb
celt
libdbus-c++
libiec61883
mm-common
libxml++3
libconfig
libffado
opus
x265
faad2
libdca
x264
xvidcore
faac
dcaenc
aom
twolame
recode
perl-Cstools
perl-Unicode-Map
perl-Unicode-String
perl-Unicode-Map8
enca
jack
"
f_dependencias
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo 
echo "$VERDE"Compilando ..."$CIERRE"
sleep 1
 
sed -i 's|../avidemux/qt4|../avidemux/qt4 -DLRELEASE_EXECUTABLE=/usr/bin/lrelease-qt5|' bootStrap.bash || exit 1
sed -i 's|0.19|1.0|' avidemux_plugins/ADM_videoFilters6/ass/CMakeLists.txt || exit 1
bash bootStrap.bash --with-core --with-cli --with-plugins
make -C buildCli DESTDIR="$PKG" install
make -C buildCore DESTDIR="$PKG" install
make -C buildPluginsCLI DESTDIR="$PKG" install
make -C buildPluginsCommon DESTDIR="$PKG" install
install -Dm 644 avidemux_icon.png $PKG/usr/share/pixmaps/avidemux.png
make -C buildQt5 DESTDIR="$PKG" install
make -C buildPluginsQt5 DESTDIR="$PKG" install
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Comprobamos version instalada del paquete
f_versionInstalada
# Comprobar dependencias
F_dependencias
#Si no existe el fichero se descargara
f_download
#Descomprimir sources
f_descomprimir
#Cd a ruta
f_cd
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales