#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20210219
CATEGORIA="Reproductores multimedia"

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=exaile
	EXTENSION=tar.gz
	GESTOR=wget
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=https://github.com/exaile/exaile
	VERSION=$(curl -s $WEB/releases|grep -v beta|grep -v rc|grep -v alpha|grep [0-9].tar.gz|head -1|cut -d- -f2|cut -d t -f-1|sed 's/.$//g')
	SOURCES=$VERSION.$EXTENSION
	CD=$PRGNAM-$VERSION
	DOWNLOAD=$WEB/archive/$SOURCES
}

# Comprobar dependencias
F_dependencias(){
DEPENDENCIAS="
TiMidity++
aom
amrnb
amrwb
celt
faac
faad2
gsm
libass
libcdaudio
libdc1394
libdca
libfdk-aac
libkate
liblrdf
libmimic
libmodplug
libmusicbrainz
libofa
libquicktime
lv2
musepack-tools
rtmpdump
schroedinger
soundtouch
xvidcore
gst-plugins-bad
cddb-py
streamripper
mutagen
bsddb3
pluggy
py
more-itertools
atomicwrites
python3-attrs
setuptools-scm
python3-pytest
ipython
gst-python3
setuptools-scm
functools-lru-cache
python-soupsieve
python3-soupsieve
BeautifulSoup4
html5lib
lxml
pylast
musicbrainzngs
bubblewrap
enchant2
geoclue2
libseccomp
libwpe
wpebackend-fdo
xdg-dbus-proxy
webkit2gtk
" 
f_dependencias
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
## Fix manpage location.
sed -i -e 's|share/man|man|g' Makefile

make
PREFIX=/usr \
LIBINSTALLDIR=/lib${LIBDIRSUFFIX} \
make install DESTDIR=$PKG PREFIX=/usr LIBINSTALLDIR=/lib${LIBDIRSUFFIX}
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Comprobamos version instalada del script
f_versionInstalada
# Comprobar dependencias
F_dependencias
#Si no existe el fichero se descargara
f_download
#Descomprimir sources
f_descomprimir
#Cd a ruta
f_cd
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales