#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20200904
CATEGORIA="Reproductores multimedia"

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=exaile
	EXTENSION=tar.gz
	GESTOR=wget
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=https://github.com/exaile/exaile
	VERSION=$(curl -s $WEB/releases|grep -v beta|grep -v rc|grep -v alpha|grep [0-9].tar.gz|head -1|cut -d- -f2|cut -d t -f-1|sed 's/.$//g')
	SOURCES=$VERSION.$EXTENSION
	CD=$PRGNAM-$VERSION
	DOWNLOAD=$WEB/archive/$SOURCES
}

# Comprobar dependencias
F_dependencias(){
DEPENDENCIAS="
geoclue2
webkit2gtk
bsddb3
mutagen
feedparser
opencore-amr
libdvdcss
libmpeg2
twolame
x264
gst-plugins-ugly
musicbrainzngs
cddb-py
pylast
python-keybinder
streamripper
decorator
parso
jedi
ptyprocess
pexpect
pathlib
pickleshare
wcwidth
prompt_toolkit1
shutil_get_terminal_size
simplegeneric
ipython_genutils 
traitlets
Pygments
ipython
" 
f_dependencias
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
## Fix manpage location.
sed -i -e 's|share/man|man|g' Makefile

make
PREFIX=/usr \
LIBINSTALLDIR=/lib${LIBDIRSUFFIX} \
make install DESTDIR=$PKG PREFIX=/usr LIBINSTALLDIR=/lib${LIBDIRSUFFIX}
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Comprobamos version instalada del script
f_versionInstalada
# Comprobar dependencias
F_dependencias
#Si no existe el fichero se descargara
f_download
#Descomprimir sources
f_descomprimir
#Cd a ruta
f_cd
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales