#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20200312
CATEGORIA="Reproductores streaming"

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=gradio
	SRCNAM=Gradio
	EXTENSION=tar.gz
	GESTOR=wget
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=https://github.com/haecker-felix/gradio
	VERSION=$(curl -s $WEB/releases|grep .gz|grep v[0-9]|grep -v beta|head -1|cut -d / -f5|cut -d v -f2|cut -d t -f-1|sed 's/.$//g')
	SOURCES=v${VERSION}.${EXTENSION}
	CD=$SRCNAM-$VERSION
	DOWNLOAD=$WEB/archive/$SOURCES
}

# Comprobar dependencias
F_dependencias(){
DEPENDENCIAS="gst-plugins-ugly yelp-xsl yelp-tools"
f_dependencias
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo 
echo "$VERDE"Configurando ..."$CIERRE"
sleep 1

./autogen.sh

CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --mandir=/usr/man \
  --build=$ARCH-slackware-linux

echo 
echo "$VERDE"Compilando ..."$CIERRE"
sleep 1
make || exit 1
make install DESTDIR=$PKG

# Cambio en la categoria
FICHERO=$PKG/usr/share/applications/gradio.desktop
mv -f $PKG/usr/share/applications/*.desktop $PKG/usr/share/applications/gradio.desktop
SECCION=`cat $FICHERO |grep Categories|cut -d '=' -f2`
sed -i "s/$SECCION/AudioVideo/g" $FICHERO
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Comprobamos version instalada del paquete
f_versionInstalada
#Compronar dependencias
F_dependencias
#Si no existe el fichero se descargara
f_download
#Descomprimir sources
f_descomprimir
#Cd a ruta
f_cd
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales