#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20250407
CATEGORIA="Editores de video"

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=lives
	EXTENSION=tar.bz2
	GESTOR=wget
	echo -e "\033]2;${PRGNAM}_updater\007"
	WEB=https://sourceforge.net/projects/$PRGNAM/files/$PRGNAM
	VERSION=$(curl -s $WEB/|grep latest|cut -d/ -f8)
	SOURCES=$PRGNAM-$VERSION.$EXTENSION
	CD=$PRGNAM-$VERSION
	DOWNLOAD=$WEB/$VERSION/$SOURCES
}

# Comprobar dependencias
F_dependencias(){
DEPENDENCIAS="mjpegtools ladspa_sdk libunicap libdv schroedinger libavc1394"
f_dependencias
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo -e "\n${VERDE}Configurando ...${RESET}"

# Don't build toonz plugin (build failure when opencv is present)
# https://sourceforge.net/p/lives/bugs/217/
sed -i -e '/toonz/d' lives-plugins/weed-plugins/Makefile.am

CFLAGS="$SLKCFLAGS -fcommon -I/usr/include/tirpc -Wl,-ltirpc" \
./configure \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --sysconfdir=/etc \
  --localstatedir=/var \
  --mandir=/usr/man \
  --enable-turbo \
  --disable-doxygen \
  --docdir=/usr/doc/$PRGNAM-$VERSION \
  --build=$ARCH-slackware-linux

echo -e "\n${VERDE}Compilando ...${RESET}" 
make || exit 1
make install-strip DESTDIR=$PKG

cd $PKG/usr/bin && rm -f lives && ln -s lives-exe lives
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Comprobamos version instalada del paquete
f_versionInstalada
# Comprobar dependencias
F_dependencias
#Si no existe el fichero se descargara
f_download
#Descomprimir sources
f_descomprimir
#Cd a ruta
f_cd
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales