#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20201127
CATEGORIA="Reproductores multimedia"

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=vlc
	EXTENSION=tar.xz
	GESTOR=wget
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=https://download.videolan.org/vlc
	VERSION=$(curl -s $WEB/|grep [0-9]/|cut -d '"' -f2|cut -d / -f-1|sort -t. -k 1,1n -k 2,2n -k 3,3n -k 4,4n|tail -1)
	CD=$PRGNAM-$VERSION
	SOURCES=$PRGNAM-$VERSION.$EXTENSION
	DOWNLOAD=$WEB/$VERSION/$SOURCES
}

# Comprobar dependencias
F_dependencias(){
DEPENDENCIAS="
dav1d
libgme
libiec61883
libxml++
libconfig
libffado
celt
libass
libdc1394
libdvbpsi
libmpeg2
libupnp
lua
portaudio
twolame 
ffmpeg
freerdp
gsm
numpy3
libtar
libkate
faac
libdca
libebml
libmatroska
libshout
jack
libsidplay2
zvbi
faad2
libavc1394
libmodplug
libcuefile
libreplaygain
musepack-tools
vcdimager
dirac
gnome-vfs
live555
rtmpdump
libdvdcss
schroedinger
libminizip
chromaprint
x264
x265
libaacs
libbdplus
ftgl
aom
libplacebo
libnfs
pytz
python-gflags
google-apputils
protobuf
libdaemon
avahi
"
f_dependencias
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo 
echo "$VERDE"Configurando ..."$CIERRE"
sleep 1

echo "/Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj4CP/Bf1dADgYSu7FL5n6pvg745dpgzgztyjlznaup/Je
Dd1Owk8JnvgaTAWcpAuzRhDf2fns08b2FG9Aj9XvkO1RnmSCN2+qLVfA++zUYLOajTwi/IVovklL
HtlRti5cjnjVYUDzA84I554JRXALtDws8/uNm0WrJDFDrXPs1IaTzuakDmPffdgAAPwnAfu2J3dF
xPGkiuZi4fQasWn9QJr5XZbeOqJhnjuVW9caIh0vjuH+0qRilauNtxP/XxPa6aBdxR2hIbY+1+Tb
xTXBF/xkxAh3VL3cDawNMZNfwNtrNwoxJSkigU2N6QSOpRvxGaEIRkaEsdXB0eoYC+MD0rrn7l3V
yx4QOLQ53mgg1RvLL6C6/zg2RLNC7e3QJMrxvnunPo1ny084fgOD/u1tdU4e51Y5YhNxALK+ehs1
4JVqvmr5alk4nlaY6N/pkS5po1KgIRkuqpDnl3FZ9JnNUZlHItJw8JObhCx00Qp3ATXwgmHlGL6z
eHI9lYTmENJLYImNiledNrLmXz2AB5ZDfgLMsTFYLxg9KaV5FB61wTDgAI6Vpy6ZjvM03D70NUhh
B3cQNEzswRCzs0lhtqaljczSsnK5XAPil230ypClaSSDbajmoT7jQ8juXvcuV4YTi/4nVZvXN1FS
vLUuNgq44P9yfs8ZAXKvoSllSgkgPay10EtvTu//pxsxvD5sX7pG8SfgDewxLhc401Byl54tzyjt
/JdvbFX9juWXWG5AKPVyMt/jWe+f+xyEx4ExmFBKqZjT7LzQImU7nxGhPYtB4Noh0xQktXAYacTP
B6wrhfQcoMJ3m2SWBAHsSaxnVDDFoS8waz86DTtAE/oDLY/n0E9yX649Jfys2/zun6xRLyWbWIOW
bkbSzLH+5eW8mNGmZ6io/Liq8/GnvDzK9BNRX7mywIYxcsOhDYNWV6oRyF9FL3J69Q7NErxjFdhu
doLlA/Mx+yH59DqxNfPOlBwK4nYBqCHXXSM1F7asdWYVksNQxhoZCXEopPVJeJ1nUfpbZ9qmyEU7
Ot8TiDcZEEszPa6g9lS2PhOMmyAg5UIBoU4hd5r3tEM2Jf7PBnz9lKqPplreY3iGTr+nQhJTwfxv
AMQTPL3tlEFvwWIeq0yyaODGCW0G7d4laf9YuX7dv4HdDzAjGSJKGW0Wof4nT/XcR2beF4BqmRYm
5mrWGXJOFUusLCeAhJ7H9EE4KckwKQRyegeI93ux82RxGlLPLFKCEuKi3ue+4W8/fN1eIUtrGJT/
a99J/HKwjzZ6ncF52nVeHVK+jR50jfRY7HU9I2hIW6I4Xezo3m3hI/haqHMuIolYOk87O0pklZP+
C0coShxdO4RUkr2Lof+HbV7zz2GEn/btf4nSb+dfsYbOmHwth675VDI5K8KV9y+1prjeaCCuMBYZ
ID0JeSiT/5DZjsfBau9haNpDUtapKhrQW6VI8xwaRJJtYupUFN5o2cpvpvOegLnqNj/BeHCxaFaq
fSaLsrO8TJ97VwV/VE7JetPSRVDW1uznBftIhbF7WU2YTIyprIZ7BiTlEvVBFM8RUEoH3lHTnPiP
71jp09+TsQ0FMBv99aWuPSj5aZOpCqaQmPUtKjV9JR5sOuRTK/DnmQ4w72ScLi6Ui5g+KL03OblW
Z1QO2sjrlwUJHWhtSvmfoj85Zv843AoHnpo5AnjGBSHS+l3hGNFJutOAsh0lCmS0rs5nt/+uCN1F
fQyPzoTYsvw8ELyYLTA9fm4KSFo0vqdIjQzvoeIRCXBq0ExQA9MuLFtdpuV2pX9BdriExaRWQTk9
PR7FFaA1vPMxyUhIXuNcps8NhC3SOALKlOXUs0NPnIuH6J16P8KMQIlqVO8awEX9kbUn1FOf+nDN
tt+VYpt79NJ0oghufA+d4lgasBxPM26msrK7/xwkWiwLRU7SJLwPmqFYU+pBuGEzFy3Yj+R4Fzop
K19YxeVKoMyUq/oTSoQT/qSVfVIFr3XNBrWakM6Sp5+TqlP3dqgkCSLWxMBbl+Ylva2oVRGXqp9k
2sseCVYzHzPMP+WbGatuLDtmCoPJqKyVcAAAAAAOQtuaHS+tCgABmQyASAAAFBQcr7HEZ/sCAAAA
AARZWg=="|base64 -d > $TMP/patches.txz

tar xvf $TMP/patches.txz &>/dev/null

patch -p0 < ./patches/patch-dvdread-503.diff
patch -p0 < ./patches/patch-dvdnav-503.diff
patch -p0 < ./patches/patch-projectM-fontpath.diff
patch -p0 < ./patches/patch_vlc_cache_gen.diff
patch -p1 < ./patches/qt-5.15.patch

sed -i '/DEPRECATED/s:^://:' modules/text_renderer/freetype/text_layout.c

autoreconf -fiv

CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
LDFLAGS="$SLKLDFLAGS" \
./configure \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --sysconfdir=/etc \
  --mandir=/usr/man \
  --docdir=/usr/doc/vlc-$VERSION \
  --localstatedir=/var \
  --enable-run-as-root \
  --disable-opencv \
  --disable-fdkaac \
  --disable-schroedinger \
  --disable-libgcrypt \
  --disable-update-check \
  --enable-qt=5 \
  --enable-merge-ffmpeg \
  --enable-archive \
  --enable-live555 \
  --enable-dc1394 \
  --enable-dv1394 \
  --enable-dvdread \
  --enable-dvdnav \
  --enable-bluray \
  --enable-smbclient \
  --enable-sftp \
  --enable-nfs \
  --enable-realrtsp \
  --enable-dvbpsi \
  --enable-gme \
  --enable-ogg \
  --enable-shout \
  --enable-matroska \
  --enable-mod \
  --enable-mpc \
  --enable-mad \
  --enable-mpg123 \
  --enable-gst-decode \
  --enable-avcodec \
  --enable-libva \
  --enable-avformat \
  --enable-postproc \
  --enable-faad \
  --enable-vpx \
  --enable-twolame \
  --enable-a52 \
  --enable-dca \
  --enable-flac \
  --enable-libmpeg2 \
  --enable-vorbis \
  --enable-speex \
  --enable-opus \
  --enable-oggspots \
  --enable-png \
  --enable-jpeg \
  --enable-x264 \
  --enable-x265 \
  --enable-zvbi \
  --enable-libass \
  --enable-kate \
  --enable-vdpau \
  --enable-sdl-image \
  --enable-freetype \
  --enable-fribidi \
  --enable-harfbuzz \
  --enable-fontconfig \
  --enable-svg \
  --enable-svgdec \
  --enable-aa \
  --enable-caca \
  --enable-pulse \
  --enable-alsa \
  --enable-jack \
  --enable-samplerate \
  --enable-soxr \
  --enable-chromaprint \
  --enable-chromecast \
  --enable-skins2 \
  --enable-libtar \
  --enable-ncurses \
  --enable-lirc \
  --enable-projectm \
  --enable-avahi \
  --enable-mtp \
  --enable-upnp \
  --enable-libxml2 \
  --enable-gnutls \
  --enable-taglib \
  --enable-secret \
  --enable-notify \
  --enable-libplacebo \
  --enable-vlc \
  --enable-aribsub \
  --enable-aom \
  --enable-dav1d \
  --with-kde-solid=no \
  --build=$ARCH-slackware-linux
  
echo 
echo "$VERDE"Compilando ..."$CIERRE"
sleep 1
make  || exit 1
make install DESTDIR=$PKG || exit 1

mkdir -p $PKG/$(cd /usr/share/vim/vim*/syntax ; pwd)
cp extras/analyser/vlc.vim $PKG/$(cd /usr/share/vim/vim*/syntax ; pwd)/
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Comprobamos version instalada del script
f_versionInstalada
# Comprobar dependencias
F_dependencias
#Si no existe el fichero se descargara
f_download
#Descomprimir sources
f_descomprimir
#Cd a ruta
f_cd
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales