#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20230223
CATEGORIA="Reproductores multimedia"

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=vlc
	EXTENSION=tar.xz
	GESTOR=wget
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=http://get.videolan.org/vlc
	VERSION=$(curl -s $WEB/last/|grep $EXTENSION|head -1|cut -d- -f2|cut -dt -f-1|sed 's/.$//g')
	CD=$PRGNAM-$VERSION
	SOURCES=$PRGNAM-$VERSION.$EXTENSION
	DOWNLOAD=https://download.videolan.org/$PRGNAM/$VERSION/$SOURCES
}

# Comprobar dependencias
F_dependencias(){
DEPENDENCIAS="
soxr
dav1d
libgme
libiec61883
libconfig
libdbus-c++
mm-common
libxml++3
libffado
celt
perl-Cstools
perl-Unicode-Map
perl-Unicode-String
perl-Unicode-Map8
enca
libass
libdc1394
libdvbpsi
libmpeg2
libupnp
lua
portaudio
twolame 
gsm
python3-numpy
libtar
libkate
faac
libdca
libebml
libmatroska
libshout
jack
libsidplay2
zvbi
faad2
libavc1394
libmodplug
libcuefile
libreplaygain
musepack-tools
vcdimager
dirac
ORBit2
libbonobo
gnome-mime-data
gnome-vfs
live555
rtmpdump
libdvdcss
schroedinger
libminizip
chromaprint
x264
x265
libaacs
libbdplus
ftgl
aom
python3-glad
libplacebo
libnfs
pytz
python-gflags
python2-dateutil
google-apputils
protobuf3
libdaemon
avahi
srt"
f_dependencias
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo 
echo "$VERDE"Configurando ..."$CIERRE"
sleep 1

echo "
/Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj4B//B3ldADgYSu7FL5n6pvg745dpgzgztyjlznaup/J2
opDAEwLhmmgGF0AsVWM8Ad/o9xm9gxV/Dzuo2ss4JZ0/Qslcg+Wx4MNgKqcJQnz9Gf2IV6uH1H4F
KteuMjKu0tMub8ZqLCvv2a56xuzjMxDuZwOk0pqoXVYEea+K78p8NpNQF03L3SH8M1/3sjIK9xXi
FuQJJPt1teCO2jC/3eBoMZQZ8uIPSKnxdsJ8LFu+wub0C8YNv+4dbsHvpYd/02rrQz905k8mq8pJ
JSZMlrEjNw/rPIg65mcYrujiGzMx1N+ahhjz2Dar/LE/Eh8nSjkipkrzbtTwEe4Rhv4A2khVR2DS
CDvUb1cSkfXjTDzsSSXLZaGaEXTz/zv9IxVe7wEo+Vm0PlbSwDBbbD6LrQH61WbDXgUoYxw7kOT7
aYnjlkmsIGJohkUTrecX0hscK8kEhY2JbHzWzQB8PuVKvV4g7lft3+aBfVYkVsHAX5vWXf0uiQ8z
rvKbVj9jbGY/9bVEm19gYnPkxaLYgEtr4IQ3debpIxBk9A9sGdnzM+0BczF3W6u02wTK7daEK7lX
8f5mi2F3F49N8qaQceL4qJrHlq3COw5MfVXUYNkz+VO9K7G6BiNiHxqc5mabsQitQsguShPTqjIf
2iEykEc3e2otkUi1UHjIPWBlc3cEF1PG6qZQmHX3k5WSanP1buxo1BL4I5y8YfYr5cJVkDH4Lfzr
LK/388RRjwJ9BjAy+ejM5p58TROOsbarENHefFaZqirlGWKfUKDFDJhxs2KGNFBXKYqcypPu2YEc
HJi4l0aH9CAlypQcE4GNlDCt3lPHg0uokxwh8gMkpk3YZWtcurUzEMy7RoPrDfiavf6SisrGKeHk
k0CsjC1LPYK6l4KLjWSEmoGEsM3Q7BqBQz+eMuk2vRDG29jQsZRqzjjrj1JrsqsYfACYwT7bNoeS
ZyIAeGV8l85OPgENGPJf8HXGLuPSVgiX931vFHFsg11hdL4Lrx0GFI2APaPgPfqgxKrmoMweWr6+
HJp9rnjcHUbQW0sGppteojHhsUBEHREO3k5HRohxJVBICWKntzuu41t7fIF2A1Pdfbp6lxM9bMFS
vrJaa0vBVXnn/FwDyrBCpgyhSlphBZTJ6xoyoxadO/7ed8iN18kNaCSHb3lGICRvTFFcnG9COkeg
ot//1Zs29c7liC3Vlc9tkCBdBk4GWCONTry5x83WiRK0aiODOrEcC/vONbTkhmEGP/gEEmeR31o6
4+gvW0WIxQhtOGOtAkhOfGP+JUP9u2nQ8eTYhbxdpqFexWMPS88VIdRmxedcF2/uw1UiVIJEcesi
DZT8mLPw2qHQ216TdHail6cNLX0tNpwkabRPX0nRsR/xAIysTwXW/XIJ75G///+m+4N31quzv3s9
0d57k+hPtb0q9h18TWzOPuy/cZ2b+J4PlTXC9vXP6tDTbLEjiCWfxd/wXe42G0yzZji/3On6NWSE
QV/p/CMkR8Qf7H1C57FUvCyLyq0cDvdbL6V4ZbyjSS2whNcsUusB4AfukOmTheOXmX3cnvBiRq7I
BF9QInEAHpihSGQEvNSyYVaysTe7DxKfNlqOOnGGw+NJoBkTtGg0wAbA9eO9xqMmJIpUvnv/qE41
p4waFAA2x403RmSR16a+oHwklt/7+bs42w1EO6Qmc29thRle4zfe8cqUGR54vFkDsjbtlDaF8OPJ
PeaaXRXwIK0tUDbP3zDLkL+AQ7j07WkHPlBvZhEMVq4rPoWlmiE47HSoS09vg+hGtozIKuOjNVBJ
IuQBKJl5kZtiVMiQ0MDOaShZfmnkR/Dhvb9oFPtUDl8ub//snthpIn/vC55YfjInWm9Zz6NeD79I
s+wJHiQAMgVE6tEDOFvE+azZDRful3vltJ2UOEG7SVAeO85cmJeJ8SC0+Ojwc8QP9X88k00u5PT7
LKvhHgkrWUYjXgaq4yl9gs4ZOQ5IJ74DlPzyDW8FaNssGjyvJI4bqc1xND5kw0GHNY/pPOzgJhOe
g4C+gcpd1hKkpJAsR3pDhyFPTpH8U6cxbAifh/vGwIdaUX5Lgj12aHolt1Yv4/3svgOBPxJYg8zz
mToHmC+q/cHOVz8cbcbtUVKI/H3kGZ/6JP43ioju0NTgtHXqIEhdxP97the8wXS6p908KYWxd0ZA
71+g5LxX9m5XfM6WsP0msDjmmAL/7VrZMxIUSYtkMzGhvcUpXV8t0LSnS8VLg5WGbgIloJALOp0S
e3h6wmWqEX0Lr1T1RxAsPVbndTIPQqWEicm0n54SnDbkuke6LUGfE6Mycb6ENS/noccQtUHQZ+o7
0u/WUiratoeDgVZmpZsfup2GGpJNhObA9QjZ10sF9xNDsKu6V/IVAhdOwpkbWI2Yd3Yd/kZohnKF
Vx/3itFhF7TxP1j6yq8+BbTaINmrt9q2zoaZyFPV/RyAQBEBVof/dUIkAb/Jh03Fq6RFYT2+JMlG
00eKoEHpA0hxkfR0LTFqgA1zWzWw/U3Dnd6fsutAVxhtrAorUzlrqvFmPTmhqFc1nE1HrWOPUVfM
dq2+dysAAAAAAO14UyrorglAAAGVD4BAAAAH/22RscRn+wIAAAAABFla"|base64 -d > $TMP/patches.txz

tar xvf $TMP/patches.txz &>/dev/null
patch -p0 < ./patches/patch_vlc_cache_gen.patch||exit 1
patch -p1 < ./patches/libplacebo-5.patch||exit 1

autoreconf -fiv

CFLAGS="$SLKCFLAGS  -I/usr/include/samba-4.0" \
CXXFLAGS="$SLKCFLAGS -std=c++11" \
LDFLAGS="$SLKLDFLAGS" \
./configure \
    --prefix=/usr \
    --libdir=/usr/lib${LIBDIRSUFFIX} \
    --sysconfdir=/etc \
    --mandir=/usr/man \
    --docdir=/usr/doc/vlc-$VERSION \
    --localstatedir=/var \
    --disable-opencv \
    --disable-update-check \
    --with-kde-solid=no \
    --enable-a52 \
    --enable-aa \
    --enable-alsa \
    --enable-aom \
    --enable-archive \
    --enable-aribsub \
    --enable-avahi \
    --enable-avcodec \
    --enable-avformat \
    --enable-bluray \
    --enable-caca \
    --enable-chromaprint \
    --enable-chromecast \
    --enable-dav1d \
    --enable-dc1394 \
    --enable-dca \
    --enable-dv1394 \
    --enable-dvdread \
    --enable-dvbpsi \
    --enable-dvdnav \
    --enable-faad \
    --enable-flac \
    --enable-fontconfig \
    --enable-freetype \
    --enable-fribidi \
    --enable-gme \
    --enable-gnutls \
    --enable-gst-decode \
    --enable-harfbuzz \
    --enable-jack \
    --enable-jpeg \
    --enable-kate \
    --enable-libass \
    --enable-libva \
    --enable-libmpeg2 \
    --enable-libplacebo \
    --enable-libxml2 \
    --enable-lirc \
    --enable-libtar \
    --enable-live555 \
    --enable-mad \
    --enable-matroska \
    --enable-merge-ffmpeg \
    --enable-mod \
    --enable-mpc \
    --enable-mpg123 \
    --enable-mtp \
    --enable-ncurses \
    --enable-nfs \
    --enable-notify \
    --enable-ogg \
    --enable-oggspots \
    --enable-opus \
    --enable-png \
    --enable-postproc \
    --enable-projectm \
    --enable-pulse \
    --enable-qt=5 \
    --enable-realrtsp \
    --enable-run-as-root \
    --enable-samplerate \
    --enable-schroedinger \
    --enable-sdl-image \
    --enable-secret \
    --enable-sftp \
    --enable-shout \
    --enable-skins2 \
    --enable-smbclient \
    --enable-soxr \
    --enable-speex \
    --enable-srt \
    --enable-svg \
    --enable-svgdec \
    --enable-taglib \
    --enable-twolame \
    --enable-upnp \
    --enable-vorbis \
    --enable-vdpau \
    --enable-vlc \
    --enable-vpx \
    --enable-x264 \
    --enable-x265 \
    --enable-zvbi \
    --build=$ARCH-slackware-linux
  
echo 
echo "$VERDE"Compilando ..."$CIERRE"
sleep 1
make || exit 1
make install DESTDIR=$PKG || exit 1

install -D -m0644 extras/analyser/vlc.vim $PKG/usr/share/vim/vimfiles/syntax/vlc.vim
rm -rf $PKG/usr/lib${LIBDIRSUFFIX}/vlc/plugins/plugins.dat
rm -rf $PKG/usr/lib${LIBDIRSUFFIX}/*.la
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Comprobamos version instalada del script
f_versionInstalada
# Comprobar dependencias
F_dependencias
#Si no existe el fichero se descargara
f_download
#Descomprimir sources
f_descomprimir
#Cd a ruta
f_cd
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales