#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20220216
CATEGORIA="Reproductores multimedia"

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=vlc
	EXTENSION=tar.xz
	GESTOR=wget
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=https://github.com/videolan/vlc
	VERSION=$(curl -s $WEB/tags|grep tar.gz|head -1|cut -d/ -f7|cut -dt -f-1|sed 's/.$//g')
	CD=$PRGNAM-$VERSION
	SOURCES=$PRGNAM-$VERSION.$EXTENSION
	DOWNLOAD=https://download.videolan.org/$PRGNAM/$VERSION/$SOURCES
}

# Comprobar dependencias
F_dependencias(){
DEPENDENCIAS="
soxr
dav1d
libgme
libiec61883
libxml++
libconfig
libffado
celt
libass
libdc1394
libdvbpsi
libmpeg2
libupnp
lua
portaudio
twolame 
gsm
numpy3
libtar
libkate
faac
libdca
libebml
libmatroska
libshout
jack
libsidplay2
zvbi
faad2
libavc1394
libmodplug
libcuefile
libreplaygain
musepack-tools
vcdimager
dirac
gnome-vfs
live555
rtmpdump
libdvdcss
schroedinger
libminizip
chromaprint
x264
x265
libaacs
libbdplus
ftgl
aom
libplacebo
libnfs
pytz
python-gflags
google-apputils
protobuf3
libdaemon
avahi
srt
"
f_dependencias
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo 
echo "$VERDE"Configurando ..."$CIERRE"
sleep 1

echo "
/Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj4B3/BhRdADgYSu7FL5n6pvg745dpgzgztyjlznaup/J2
aOyc9S08ucJa8EvgH9QFktQTE/zbQLzk7pfV2D1GYRCEfjjF7QXh+9S+TmyUPJuQANlnU/5I2hPa
87xFrQV1WtUs+loYATOmgpL/zhMPWga60ndbKW3PGSO8cV/bC13xQ7OgjYpEINzmuXdydRt3q6YB
oavaQmGsMREkbU9WspFN/K0MbQhqn1l1gwAQGHXZG4uO1Z6c9WIFOKJCTCh3OubiYXztl/ewgp2H
yfZ5MHklLcyqmr4ikzUnbB/QJ37IJtw4DRQIizx7UdJvU4byjWhFc6jasnSwPvKzI1dorjoEvGa2
6IgCWoQFh7uCqEv8CeoWSHIB89rdQpH5YrKsiktt4wRnP6rJCFY1Pj1JIYtzVnT/bAP3flxaqmtF
QdiU7mkkEdm06UESBc5+bJnWMtAMX6jbMSwkw0Rt3BGm/M2W/lWaeWY9h7uw1Iylpw91V/Wx16z7
Nev0Wt69oo4upV3GObIQ3rYRacm12RJJJ4uIy15DcupWMkNajl7eE6nHyWA3EQmZAb8KpdNQjRcr
D82ZD87JOPqHF6yYx2Xm+GY2CJVXnuZh0ThciHp7FFrBu35upRiYpUE3qawEfXaC2bbFxim1SDLr
dVIyDSRtahxp64wDSrZg25MXixeA7ISvb2uJTC1GVJRCDrUdc51L+4Y2TCIxexVCbYz6xdYxLcGc
roRZ+dbnsDl5m+FGGRewtTNG44veeHptzncpJxwDIFPQgm0PIfPAoDf9raUXtL1OIWrwJXmJk3sQ
iWlvqdf27yrUMmZ9TqgR0pykENoof7a6Sfn/d1uUiJvCIuei2YjgKMWafQJUZtOXiuB3EprYWW1T
gH0u5Pcx/0VgSVgRKc/ikMYv7cu3dFAogJ50nws98QqEl5M/SZmOPLl+ZEu+ivDf1FQxSmJu1aLU
+2M+TOS+mU+DcsvfU85xf4eHs8i3ZXTSUAEPdRAfaAOqmVhM7SVrngRNDl+Siqfxn6QThnEa8z6D
whDHySlMnE/CtpvKW+11Py7q7ROscUMyEzyvxgSC4+vM/9Kp9yN4yyatbOAo5MdCL3L72K0mizGx
RYK/9JhTDWdBbCFxcNVHbINIFFsmaFH3w6iWpZj2iwEHIbUy6jd8cc5UeWZFKRPiyUUjBuobUDAx
vVCSJcQEbaoOj/z3xlSzJ4esRfYqU99pva1hiWbzwa+7PVluAdWXS1wBkEiPs5Jec8px6CYC2cbr
ECjW56oBgZgy2YLbyEsIQqbnzQwemhMmI+/XqmvDEp/4DBsAs0XxE9UaCZJPJ84yIQMeyNeNrty6
dtKBqy3XXOaw2VMO5D4OwBjBY1RKJ2CLdDIX0BvkgqlbpFPB2R+Dtn3N8YzX424K8k3i2eP6E8/k
iLX2oRdgeHADXibwppp6Cs6SxPSzSQh2EqQ//uxOEyMG2o/NSJ6Hn89bt/oCzZr0TWbQi1O6JfZw
RTa1ASvGrAR4//FzlKHRHBETRhux6MZvURCZwjlglI2Ykiip1XrBeXIekz96lLtpXphfAX4JMe/5
2xQWwa06SryjK4aylkzEgv3/Y2Y7Das+IZLfUD57h/uGIBOmIctvCOE1VRLGby0NoreD/Lb4opDl
IV8TXDc8vFkI4bFJvE4ueNUh0hYUBf0Phn+o+o9r1ptnRD8IOHaPgyWB3Ntpt7r5aYelusjQMPKa
n8Bk3gQo40jF9oBtSu/4yI1SxGbzMuY3htQGMA7uCpkhuHbVE7N+uZu5Qkh+NXf4J1XZIhPxb0UV
1637q+j3aRlxO9q9d3GD0AYe0C200k2uW7rfoq6K5cXeuCKmGKnMY3lE8qveobgetk+SLB1FYdGu
TRBdihBEH/f3mTQLwUDZlojwjJYT3G8O0iifLsrx5bnyL7LaNpJPO3YOgXa732B1WeBEGCqUXee/
hBB1N00kQVkOWWCzhcc9GRcoEAmcoNxYnEyqXq9XdsXsJNiTu4SrKLEmjMLewxfK1Y2avLQqgoKC
pK8/cNfeWeZ/2iezEXydbGFUTCEY2fQ2FTp1nMp1gETFJ01OY2Wrq4ymoJLUDJ78AIXKOnZEpCnA
AAGwDIA8AABmgEfcscRn+wIAAAAABFla"|base64 -d > $TMP/patches.txz

tar xvf $TMP/patches.txz &>/dev/null

patch -p1 < ./patches/vlc-3.0.11.1-srt_1.4.2.patch||exit 1 
patch -p0 < ./patches/patch_vlc_cache_gen.patch||exit 1
#patch -p1 < ./patches/vlc-live-media-2021.patch

autoreconf -fiv

CFLAGS="$SLKCFLAGS  -I/usr/include/samba-4.0" \
CXXFLAGS="$SLKCFLAGS -std=c++11" \
LDFLAGS="$SLKLDFLAGS" \
./configure \
    --prefix=/usr \
    --libdir=/usr/lib${LIBDIRSUFFIX} \
    --sysconfdir=/etc \
    --mandir=/usr/man \
    --docdir=/usr/doc/vlc-$VERSION \
    --localstatedir=/var \
    --disable-opencv \
    --disable-update-check \
    --with-kde-solid=no \
    --enable-a52 \
    --enable-aa \
    --enable-alsa \
    --enable-aom \
    --enable-archive \
    --enable-aribsub \
    --enable-avahi \
    --enable-avcodec \
    --enable-avformat \
    --enable-bluray \
    --enable-caca \
    --enable-chromaprint \
    --enable-chromecast \
    --enable-dav1d \
    --enable-dc1394 \
    --enable-dca \
    --enable-dv1394 \
    --enable-dvdread \
    --enable-dvbpsi \
    --enable-dvdnav \
    --enable-faad \
    --enable-flac \
    --enable-fontconfig \
    --enable-freetype \
    --enable-fribidi \
    --enable-gme \
    --enable-gnutls \
    --enable-gst-decode \
    --enable-harfbuzz \
    --enable-jack \
    --enable-jpeg \
    --enable-kate \
    --enable-libass \
    --enable-libva \
    --enable-libmpeg2 \
    --enable-libplacebo \
    --enable-libxml2 \
    --enable-lirc \
    --enable-png \
    --enable-postproc \
    --enable-libtar \
    --enable-live555 \
    --enable-mad \
    --enable-matroska \
    --enable-merge-ffmpeg \
    --enable-mod \
    --enable-mpc \
    --enable-mpg123 \
    --enable-mtp \
    --enable-ncurses \
    --enable-notify \
    --enable-ogg \
    --enable-oggspots \
    --enable-opus \
    --enable-projectm \
    --enable-pulse \
    --enable-qt=5 \
    --enable-schroedinger \
    --enable-smbclient \
    --enable-sftp \
    --enable-nfs \
    --enable-realrtsp \
    --enable-run-as-root \
    --enable-samplerate \
    --enable-schroedinger \
    --enable-sdl-image \
    --enable-secret \
    --enable-shout \
    --enable-skins2 \
    --enable-soxr \
    --enable-speex \
    --enable-srt \
    --enable-svg \
    --enable-svgdec \
    --enable-taglib \
    --enable-twolame \
    --enable-upnp \
    --enable-vorbis \
    --enable-vdpau \
    --enable-vlc \
    --enable-vpx \
    --enable-x264 \
    --enable-x265 \
    --enable-zvbi \
    --build=$ARCH-slackware-linux
  
echo 
echo "$VERDE"Compilando ..."$CIERRE"
sleep 1
make || exit 1
make install DESTDIR=$PKG || exit 1

install -D -m0644 extras/analyser/vlc.vim $PKG/usr/share/vim/vimfiles/syntax/vlc.vim
rm -rf $PKG/usr/lib${LIBDIRSUFFIX}/vlc/plugins/plugins.dat
rm -rf $PKG/usr/lib${LIBDIRSUFFIX}/*.la
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Comprobamos version instalada del script
f_versionInstalada
# Comprobar dependencias
F_dependencias
#Si no existe el fichero se descargara
f_download
#Descomprimir sources
f_descomprimir
#Cd a ruta
f_cd
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales