#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20200903
CATEGORIA="Reproductores multimedia"

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=vlc
	EXTENSION=tar.xz
	GESTOR=wget
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=http://get.videolan.org/vlc/last
	VERSION=$(curl -s $WEB/|grep -m 1 .tar.xz|cut -d- -f2|cut -dt -f1|sed 's/.$//g')
	CD=$PRGNAM-$VERSION
	SOURCES=$PRGNAM-$VERSION.$EXTENSION
	DOWNLOAD=$WEB/$SOURCES
}

# Comprobar dependencias
F_dependencias(){
DEPENDENCIAS="
python3
ninja
meson
dav1d
libgme
libiec61883
libxml++
libconfig
libffado
celt
libass
libdc1394
libdvbpsi
libmpeg2
libupnp
lua
portaudio
twolame
opus 
ffmpeg
freerdp
libwebp
gsm
numpy3
libtar
libkate
faac
libdca
libebml
libmatroska
libshout
speex
jack
libsidplay2
zvbi
faad2
libavc1394
libmodplug
libcuefile
libreplaygain
musepack-tools
vcdimager
dirac
gnome-vfs
live555
rtmpdump
libdvdcss
fluidsynth
schroedinger
libminizip
chromaprint
x264
x265
bluray-keys
libaacs
libbdplus
libbluray
ftgl
aom
vulkan-sdk
Mako
libplacebo
libnfs
pytz
python-gflags
google-apputils
protobuf
libdaemon
avahi
qt5
"
f_dependencias
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo 
echo "$VERDE"Configurando ..."$CIERRE"
sleep 1

echo "/Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj4Bv/BIxdADgYSu7FL5n6pvg745dpgzgztyjlznaup/JO
4eXHDmkgIwrAIMPh6iR1pV+e3zRZ4ilVbfbipkKS7gp15/cY/T7XjzvwnOx575jnAPcbYgioZr7c
vWn1bj9Pv8AVso1KP8ytyNXbFBXE7ngeMfn/n7/UeUKMV/qbXAYi3MMRHs1erUQR/6wKcbaCJ3jb
d5i9XumTQ7QjnmjVavxlQYTwgRZQ2XA+uEPW44SCGyv3Z1MDezpJ+Zr8HpDyQNgjJfKO/WIuWwZy
OGnk+KgRbYZjIOiVTR2Ye7gj36GWj0KCIHhUKgmq3iDiPg4RtLLe0hRG/Tn3af+6LDE/uBSvEs1U
Pf5jU7J+revgg8gCnPaKwb61C6OTBCNvXHCq4qrnG5b0odqH/Sv45ETGm8qXYcPEaCj5SJeLN4nC
9ehU1opJP5DTFrKK0x/SFZCJe/kxKDVPpnxEeafChxa9D/fxhnRR7+ObOlWb20mYqf7gPAwYPh1B
zb+EBGp+EZv3mQVGmeFyV9IF7xONxEk0AWXlQwsKwS2ZZWeG7jT6cUFUEN4LjSXHY1uBi9XFqtsn
A6mCAqkTLDEL/5OB4j6ofqFHLHl0HLWiOK22+ns7TjNurzJ1y5oK35zMXe6XJY8moVWxTCrTnDiy
COZ/lPJb2UwyTHhCvG85799r1dMxBGo2b+EUTkiJt97ksB5m4xmQnp/6zw0T4gRI6+G0OEziQtoa
F6xcuHmq94vaTxWai9AyDn3+aYwGDHxYKF2oqfbMTeHQISEQWSTPznWHBPn28UG71kckwED+5kqy
ppNUr27olqN5mscZ5Kj+hAr34IGtI6X0L0GC0vzyTo2cPY5zw7X0XVaDBeX4OLBicMVTB4HrNLnp
mNQZ2w7Vje3WmLZrQQSXQylWVmYqqVELwo70m+9A2jwriWLmqAo4Bs/lAN+lIfYmkOFimVRoOVbe
CcJZa7HPkjOoZviGGV/CnPB3p9XLzo5CaPYNlck+ofg2n4TpzRCbbzTlhQOJALeklLMMWc54u4TM
k3JXpa1L+bO6ChDDVB628e9HMgUqi+ifyjZULEKJTusvS38y4clBKcxgWc7TNW1g18sIp06aEaZf
fMPD/L05xP3a7/VlcTBtjadRBzp876W0llddV1SPWrXWSIqtFeaF36m8hv9vE9Z0sk/GJPFuacRJ
yrZ04teX9WCcqABMqhYt62by3rsi/GdMShLykWE0qNW2fGVeSB0EIeAWn0It71TaOlOOtJd28wTb
GOr9lWwWWaS2NbirbcQyho9t/Zy54KIR+SrjL6HvY4LEc4y+bx+id8mBtEjTKCyHg59sczcJOobs
8f3qdOU8/zaemjRh5DH/acc4yC6RXI+UTnK2yl2L/tQ75hKnVwYCjCDlVcy9rEOWTwD19NPLZrqE
a5CGya8d5hHsw2sbBzwWKOtMUXZs30URXhpAjHLqBBGLtvkpqGRs7Wl1Rh96kjefzPYUocFtswca
M/vhbIew8BZztvTP8k5iTxuIjs/aJEsu7OedA1CanyGCMgvuOLOj+MZn5LI4Ss/9lnoqKMctAAA/
66gW6O9E6QABqAmAOAAAPCcr/LHEZ/sCAAAAAARZWg=="|base64 -d > $TMP/patches.tar.xz

tar xvf $TMP/patches.tar.xz &>/dev/null

patch -p0 < ./patches/patch-dvdread-503.diff || exit 1
patch -p0 < ./patches/patch-dvdnav-503.diff || exit 1
patch -p0 < ./patches/patch-projectM-fontpath.diff || exit 1
patch -p0 < ./patches/patch_vlc_cache_gen.diff || exit 1

FIND=$(ls /var/log/packages|grep -m1 libva-intel-driver|cut -d- -f4)
if [ $FIND = 1.6.2 ]; then
LIBVA="--enable-libva=no"
else
LIBVA="--enable-libva"
fi

autoreconf -fiv

CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
LDFLAGS="$SLKLDFLAGS" \
./configure \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --sysconfdir=/etc \
  --mandir=/usr/man \
  --docdir=/usr/doc/vlc-$VERSION \
  --localstatedir=/var \
  --enable-run-as-root \
  --disable-opencv \
  --disable-fdkaac \
  --disable-schroedinger \
  --disable-libgcrypt \
  --disable-update-check \
  --enable-qt=5 \
  --enable-merge-ffmpeg \
  --enable-archive \
  --enable-live555 \
  --enable-dc1394 \
  --enable-dv1394 \
  --enable-dvdread \
  --enable-dvdnav \
  --enable-bluray \
  --enable-smbclient \
  --enable-sftp \
  --enable-nfs \
  --enable-realrtsp \
  --enable-dvbpsi \
  --enable-gme \
  --enable-ogg \
  --enable-shout \
  --enable-matroska \
  --enable-mod \
  --enable-mpc \
  --enable-mad \
  --enable-mpg123 \
  --enable-gst-decode \
  --enable-avcodec \
    $LIBVA \
  --enable-avformat \
  --enable-postproc \
  --enable-faad \
  --enable-vpx \
  --enable-twolame \
  --enable-a52 \
  --enable-dca \
  --enable-flac \
  --enable-libmpeg2 \
  --enable-vorbis \
  --enable-speex \
  --enable-opus \
  --enable-oggspots \
  --enable-png \
  --enable-jpeg \
  --enable-x264 \
  --enable-x265 \
  --enable-zvbi \
  --enable-libass \
  --enable-kate \
  --enable-vdpau \
  --enable-sdl-image \
  --enable-freetype \
  --enable-fribidi \
  --enable-harfbuzz \
  --enable-fontconfig \
  --enable-svg \
  --enable-svgdec \
  --enable-aa \
  --enable-caca \
  --enable-pulse \
  --enable-alsa \
  --enable-jack \
  --enable-samplerate \
  --enable-soxr \
  --enable-chromaprint \
  --enable-chromecast \
  --enable-skins2 \
  --enable-libtar \
  --enable-ncurses \
  --enable-lirc \
  --enable-projectm \
  --enable-avahi \
  --enable-mtp \
  --enable-upnp \
  --enable-libxml2 \
  --enable-gnutls \
  --enable-taglib \
  --enable-secret \
  --enable-notify \
  --enable-libplacebo \
  --enable-vlc \
  --enable-aribsub \
  --enable-aom \
  --enable-dav1d \
  --with-kde-solid=no \
  --build=$ARCH-slackware-linux
  
echo 
echo "$VERDE"Compilando ..."$CIERRE"
sleep 1
make  || exit 1
make install DESTDIR=$PKG || exit 1

mkdir -p $PKG/$(cd /usr/share/vim/vim*/syntax ; pwd)
cp extras/analyser/vlc.vim $PKG/$(cd /usr/share/vim/vim*/syntax ; pwd)/
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Comprobamos version instalada del script
f_versionInstalada
# Comprobar dependencias
F_dependencias
#Si no existe el fichero se descargara
f_download
#Descomprimir sources
f_descomprimir
#Cd a ruta
f_cd
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales