#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20210408
CATEGORIA="Editores de audio"

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=ardour
	SRCNAM=Ardour
	EXTENSION=tar.xz
	GESTOR=wget
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=https://github.com/Ardour/${PRGNAM}
	VERSION=6.6
	SOURCES=$SRCNAM-$VERSION.$EXTENSION
	CD=$SRCNAM-$VERSION
	DOWNLOAD=http://ponce.cc/slackware/sources/repo/$SOURCES
}

# Comprobar dependencias
F_dependencias(){
DEPENDENCIAS="python3
libffado
celt
opus
aubio
jack
liblo
liblrdf
vamp-plugin-sdk
rubberband
serd
sord
lv2
suil
sratom
gts
graphviz
cppunit
ladspa_sdk
dssi
set_rlimits
qt5
qjackctl
whysynth
ffmpeg"
f_dependencias
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo "/Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj4Av/AltdADsZSiDy301YcmyvSMKU9QdCJQ5x/8br9Z1G
pXNJTIdjNEdQ3JcGSi9y3RjlcocxLmHInpLAZlBFaHtVOYjE32jUynQHZ8eBmxcq98tI9IG6809H
2jRqwAn7sztbuoL7nINKHEuWAHAVhu1jRklAXooothF04b2tcP7ap5veFVJe0QwLgcS0QoJ1rzLP
zw61c3bCnsReGlVeBmKjMTVggNBDIJWroiDBxN89wUo+Mfq/ElBXpAV18gnaI/oz/ARLcm9kFUdH
HGOGGDparWo5olJbw5L4AOd2rSWaOHPK7i30tyVHeq3UcMFxLy7fyaQPa+99wCKxmskI34MDqgaI
Kj2ZEtluJnFgfBrz4Xlnq39tVSWcpAWxqKJPDNjFk/TkuOw31B/c2ZmzdDId2vcvM1dvgw/SHqrr
apvvBrsNPhMlaUazQmk7bO6TAzhnozq9jPxGFPysn2dhEpsvLDGk1HHCYEmKeFaUhHXYVezaBUx7
RVwIw2+98SbeUkZnpmpEvdpcCZjah6UBp5ZN//pQidfmGGZKwIC91w7rVikDrb+b1QEQAW6xE6vI
GeD/3gebw22N7SRxfYrf/DTRONK2aqPes157IGf7x4EgIlYhL6c5redy5ljernUz02axB2I5lS4V
7HEwm9Wtwm7njXazCrSIcgAgreroH8MPaysiKsshFo0CFXsaS3An5LpH13M2P5/8Z07CJP4TtpXs
8sOU1k7fJJbC8oU7meAu2SbkpeMrjyXQV/j/EYYPe/vcJJ7FotzKkdMIo6Y8KYVQ0XZpGV4CKVaW
G+9I6e0pQAAAioSMhtSPXCMAAfcEgBgAAE8fLsGxxGf7AgAAAAAEWVo="|base64 -d > $TMP/vendor_qm-dsp.txz
tar xvf $TMP/vendor_qm-dsp.txz &>/dev/null
patch -p1 < vendor_qm-dsp.patch || exit 1

CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS -std=c++11 -fpermissive" \
./waf configure \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --configdir=/etc \
  --mandir=/usr/man \
  --docdir=/usr/doc/$PRGNAM-$VERSION \
  --with-backends="dummy,alsa,jack,pulseaudio" \
  --libjack=weak \
  --optimize \
  --freedesktop \
  --no-phone-home \
  --nls \
  --ptformat \
  --lxvst \
  --cxx11

./waf build
./waf install --destdir=$PKG

mkdir -p $PKG/usr/share/{appdata,applications,icons}
cp build/gtk2_ardour/ardour6.appdata.xml $PKG/usr/share/appdata/
cp build/gtk2_ardour/ardour6.desktop $PKG/usr/share/applications/
for isize in 16 22 32 48 ; do
  mkdir -p $PKG/usr/share/icons/hicolor/${isize}x${isize}/apps
  cp gtk2_ardour/icons/application-x-ardour_${isize}px.png \
    $PKG/usr/share/icons/hicolor/${isize}x${isize}/apps/ardour6.png
done
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Comprobamos version instalada del paquete
f_versionInstalada
#Compronar dependencias
F_dependencias
# Git clone
f_download
#Descomprimir sources
f_descomprimir
#Cd a ruta
f_cd
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales