#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20200923
CATEGORIA="Editores de video"

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=HandBrake
	EXTENSION=tar.bz2
	GESTOR=wget
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=https://handbrake.fr/downloads.php
	#VERSION=$(curl -s $WEB|grep Current|cut -d: -f2|cut -d '<' -f-1|sed "s/ //g") (requiere gtk-3.20)
	VERSION=1.1.2
	SOURCES=$PRGNAM-$VERSION-source.$EXTENSION
	CD=$PRGNAM-$VERSION
	DOWNLOAD=https://download.handbrake.fr/releases/$VERSION/$SOURCES
}

# Comprobar dependencias
F_dependencias(){
DEPENDENCIAS="opus jansson lame libass x264" 
f_dependencias
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
CFLAGS="$SLKCFLAGS -fno-aggressive-loop-optimizations" \
CXXFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --launch --launch-jobs=0 \
  --enable-x265 \
  --enable-fdk-aac \
  --disable-libav-aac \
  --disable-gtk-update-checks

cd build
  # Fix underlinking by configuring the gtk module first, then sed:
  make gtk.configure
  make || exit 1
  make install DESTDIR=$PKG
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Comprobamos version instalada del paquete
f_versionInstalada
# Comprobar dependencias
F_dependencias
#Si no existe el fichero se descargara
f_download
#Descomprimir sources
f_descomprimir
#Cd a ruta
f_cd
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales