#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20180526

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=aircrack-ng
	EXTENSION=tar.gz
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=https://download.aircrack-ng.org
	VERSION=$(curl -s $WEB/|grep $EXTENSION|head -1|cut -d- -f4|cut -d t -f-1|sed 's/.$//g')
	SOURCES=$PRGNAM-$VERSION.$EXTENSION
	CD=$PRGNAM-$VERSION
	DOWNLOAD=$WEB/$SOURCES
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo 
echo "$VERDE"Configurando ..."$CIERRE"
sleep 1

NOCONFIGURE=1 ./autogen.sh

LDFLAGS="-L/usr/lib${LIBDIRSUFFIX}" \
CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --libdir=/usr/lib$LIBDIRSUFFIX \
  --sysconfdir=/etc \
  --localstatedir=/var \
  --mandir=/usr/man \
  --infodir=/usr/info \
  --docdir=/usr/doc/$PKGNAM-$VERSION \
  --enable-static=no \
  --enable-shared=yes \
  --with-experimental=yes \
  --with-ext-scripts \
  --with-gcrypt \
  --host=$ARCH-slackware-linux \
  --build=$ARCH-slackware-linux

echo 
echo "$VERDE"Compilando ..."$CIERRE"
sleep 1

make
make docdir="/usr/doc/$PKGNAM-$VERSION" DESTDIR=$PKG install

# Don't ship .la files:
rm -f $PKG/{,usr/}lib${LIBDIRSUFFIX}/*.la

# Meto una version clasica de airmon-ng
mv -f $PKG/usr/sbin/airmon-ng $PKG/usr/sbin/airmon-zc

echo "/Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj4I3/F7pdADCaSquOCryy5gSyFPoV+nQ49gTAN4ll2OAU
JM0RiRQgn2d4ady6ZqPqibTaaUmDt8iYhyXSB/WEKV9rHq2OqNFEsR6KHERnvg6rZBJF5TfoHmJj
s7CBi/9imkvd6AITA8tOsLoMUEfaYOvW66OWgPa3980cXB03eu5v1zTdtaIcJWjoFbFOCoE3Chks
l9FTWYBWhp64JxSSKKKkBM7FfQ4T7d/0eskT+2gmhrc4vjg8yrT4P30jaSUT2Gb9yCm8YS7uCD1s
8s1GXuORJOo0MfzCHYMNPx0Q/yLemsg6btYtOa1IF+pmQEkdyee7W+8bf+AFp+OrBy7QnGVb6ddJ
TW0+AnvVKqXgPlrrJkf9tjizvVHSDRbesjjDtNtr2FIuLssI02TRV1cRAX1kWafa9G1F7Ry0h/os
S40M2M/Re1MfumPjI/h+ii5ybk5njxt8SPW4677wuMf8SNeRLqfTsu5IhgyT3+Z0tzaTI1iNSYUD
KJhJYIZMYt8z5wmaMn3TzfRzeuMPkfGo5c9zaaqTPiFif0s+eU3mQi5cPUSYVsJvItTc6V5QAl3D
V+Lf6iiW3jKyUO7XsrffjiM8EY3DqfXi/3jMQoDLBEHoialX8Lpu4+5XYLnUlN2SVZLam0wOPSuC
3Dldl03KeDNlhCa8VWtZgbCJZztxFyDm+YyNWqjwsskT9OpNYLJUX659X8FFGjgrkQmxxrBVJBof
kxOprU2H2caVNDB7TULBQ+wZh1nZ0M7zVYwXgTClkQO72CRhQK0s7bNMFpSRoQgVqBxRa4yXNM2d
KoMaqWl62ctDUfAC/e3STXT0Pnsb24GB5cPwtFfDQynsJ1tWRJGRkodmWpm8NXvKCeg1o5PjBOJq
jwYDtmPHBrJenvGQW1GcVc/Ng3fRCy/1Otj0tdwMnYhF75NCQYSyT0JS5ewKMqwd7dXbON77zi4C
/zqCmmlyepqnSMQcB0MMehL9O8/VlsJ/RPWuwI83VIFOc64ZCz4BVtF8cBeY/qjewXbpCYgAFd4P
CJkfNZPSBwWH81FWZaZ3kZIA84ucQXNQIN2VxCxbGmy0Fq5gPgEu56K/RItPjfhZW4NQ0AzPyg8s
X2lphtgsQbapkt6/Bssc8VzsuvK3xyCYGG2805sa4ILxwRO5zyoU67Nw2YYeBuZgqEmCR3SKmm1D
zvcJSuAlsDw2g0aTdLLc6cbRuAcThPTu1XZQ8CpFuxoBo+Pv9rpea/rBgC5K7LYC+E76wxchyBBB
UIWqFJSlH93QtUySI/ZEf+0WddAVacOjHHquPr4QxBp0Wj0gUweqpP86yCIHUq6OpmWY54yjz5xK
clB7Fwkl2zTJbPnIFXXf1upJKDzoWWYXvlcGQanMN7DUIg2lrcS2wLx6UywHXjmTVPFOdhiRUkiz
y+7p6GCS4cdIFJPIyjj119FT/g9+lGG6YIgDqnJmh7QFHiYxXTXnoeeJOut6UCquMXv95E604gRX
VLAAjm+oXWwvOyehLukB24EmDdwMTYTzN/etPHtGfP1MhWtrr9VfF2OMNhpQPt+C6a7H3jjJ9OcQ
d/rGPVWL+qsIoaN0U7uqImQuRAEekauLreXoAfP36s7W3AubZJZsNhhnGoS1xA9+F4AAZM0z5X/A
6sxalcseg99NB+2Lz2mozlxsxyR6te/l8Kzy02fvRgOaS/ZtCmvTFBbiMFOUdbeCxARKLgID193b
B2wpWUD/WvpbSdc5LDGucpOPwiOVXJYplliPgl2VKpZX64TsqIS2gArT2sJ2EAppQgcHaNNCB0LU
cV1LSxwa8utSXTcgHiXPCerTVMMCsIRNT7PVZneSgNZzb0l4EkCtc07wQ9gSmE6IUtWY07MdLrwC
Xsr5P34KoQUPMp0N1ViYizL5XLxFDVTuo7bgNxBRZzcOimYSzFEaylhh1J7rEkltA3xml56tpqRk
9iWhE4EDNf6dox6Uu6t9SXAlX9ivd692+u8YfAdApTq7xwd6Wku6cprZWV3kaQ+XMHLj/IAz76P/
9p43h9J39tYJaHf9vVoV+DqqOCxq13ctLPKMnwRhd5U2QTkRtOehXSiUI4eHEa8NPOmXkyaEac6a
T+MlAy3qrbH6JvYGYHC7O3GftKtc0qhBPNoQ7V5iCVx/S4xsSNyex6szbgM/p2GqtVhC2TWgUpIu
2gMSFCI/2AuYXH4WNTaXVzz+Pq0AaKpHeVakl5VN5DSMxAjW6moTKUcvOTQI6yoBESEAMCdUHAPP
gIS7Udy/XRp4Q0yYiFA72yL42ccc7Fi4iJpb9t7EGvX/LJt0NemZIPvmu1rud/XvopwBh1rD1KfZ
xnxn6eitWvrGg7bMRvaPw7GXgYOf/UwElzKpP3/pH9tLckoBog8McDX7Y0ZDf1uzJS9TzDJiWbBP
FsYV+6kZvpA1lsbAL1di4Q/WOq/a4R5HcSsQM3QBVWUFAyWQ4ZIpvaFqU8sTOx4/u/K8VPcYx8Ji
xDDueKQpqpRNks3b7qu4PDcHGyXnoFbc3WcwP4i1bz3tjXR/XWpZXCZPvwnSVoriHy+gPjGnuRdh
S4JOC58D9abnV24e9wJqbn+cdqAfs5HZuYGn0e1BeA7EP+VOf0vEFuXlJZ6++0DLzzToT3tz/HFx
lzAX8NsZhds2vo57Am8929IlTqErZfsMGJoFjo9GTFmFEWZYrDAsZKEIN3xke3NE/gIIFeq7LUSk
HD6YtUKNA1UHtqkCuyz2N/6QST+MWC2mdWDj8VrB2iZIVBkjzOoaLfKm1raWLm2mX2tfrHpepcfA
1mDnOj4R3y4WqQkwWw7ju9wEq80JDFv7RklXD5pfSEZvIAFjEc5oRTfb8lWdUmBVJPpNRjdtDgm/
B1E9MEizC0wWlouezP+yXzR1FClIH5VftZ0Tav7kfLpY2gPzA07pBusMS0mPbejTJwVvTamZYoEc
4mx7k4HvvkJLduLN+T+ZgGhsFOSWz6Q0QrHrJiAtoTOBU9KwpUKbRcjbRjYOvLxDTadc6h9n1QW2
w/8LaUOpJuQVWFnUbePVhEa+F7tgrtMQ5jAhNMJIdDv8AzqVVGc06X8VOLZN+yurXqnblc/AUrri
ExnGooiAqid4bufm8tz2svm+W8k/thivLWWTza696qA+lWCUV0B7jG9QeWmCQk+BzbJnXtZZLN55
dBmjhnqWToGuhARANRRKfp1/1oInxbTE3SXTVX18InzD3g6ONsvdDiCeMOCJgjgVQkwPX2I+x+0t
O6N2f9ry7icHgjpYFsuf3ICKuOmsYuBGv3DLVM6hSqOS8s3AG3NDZdEnMYxdOvH0NHA6K/7ykLxf
ahaQ2LPgK36xrePJHCkXuYCX2GOV2XCfKmOuTAz5uoSwkHm4aZjogJB9tMsBFnba/hmSSPx0iRw5
5qDmshaSfWbJDcpA3IOX0ZYS/2E+FYdNB00+XzBefG5CFjN6EwXTocgSaak+p8V8b9omAOs2oH/w
p/cxsf9Nk5Ss3MH5SClun5h9+xyhdlmkqXj5OaN2R895ChIB9qee5FL62U6Pqw9jt5e+xjxWDZ3/
d4S9f4ehXE9n3mlyg+rMfX7tSDzOs8OzOUXSWBS1UpMUa1UkBtdFO5z3rA0NKtf5vFVbqOSWm6yy
f+X52J2GNPbhSK8O0DV1DyEwt4ToVgOMngVlhXinXqhOF/x9rcAsY+O+b9RIzGc6icMB3sLQtUdM
FBU2rRBxwqvALm4zmFGAg3B+Ax5JLvBH+0sMGk/qK6ngXm3kjhI5VrAZS9JAeQgXGl36l2kVKt3U
9WY4Dq2Kc3Db2BECpyeCEDF2KkiwXs8VW92EnOfb03PeH5KE1UqMD96PCaNhTcZujW/YdKnWWESb
gnkg22xA8zarG8VTWLJkaKgSXHL+dSxKYssMtDrMNu4ub5i41fJfQO2C36oqlyNpX9e/7L3x86LK
fDFn6z+cXuBhDUe20UoBHVWYKSJt0EgE22cXmjxUtx2JrhsjcaN7H0iK9nmwlP5X525RgaNUjvkv
VFboz8El0B/Lcvvxr4hjTkS6CzEgnqzETsQb9VTuUWLgCwEKaXzpziMBVhYOfE2Gy/3NKQax4O2m
dHJrMKKPtpc+RyPuWRN4tZxLgdKmtVO+KQGVshfHt7760QZxxop0yQBPUpt3J3hO8xaSaswopga5
ST7qpnhByomdm0MEsCmS516bYDyYUuLUsnLVCx8a9Bco8rh7mlrWZ72hm6kpJKr69wxlVj+ildWM
zLeYRWgbRaGflZb0MYNUmYzv1I3voRrIwp56mKi9IQ3SyNEmWodqPutSLFfZ+RPS2L3b2Jz6Ihrj
klDyfE5wB9xiRYeoStbQc0HlYV1zGWqhmehSJcLxT58eGXe4KZOF7L0saFxgHVMQ26ZIwnJxtliU
7cyVZcS9gaAUGdxNf2P35cbm9PO9uVZJdQNM+He3nnV8m1SYB10R3ZkOwsfIXJiQ+w1XzupgX7p9
Y61SOAD3opXa+RAh4rdcoqz0NSTfNm+WWPqLrKj6hu1vylKcQzVAF+b9WGOvXlYBisJDuq5es3bm
v7Hls8Qolis5qIZ44nlyJVKVS0EtlYPH/zB+Ssr95XRX44N+gZFOCsTBKnY1p9rz/DI0+ktyTYO/
IY/0S2PySHOObG0bZYysDSywqfn8rnKudYb/KMyMDIpfn36myPyOAK0IVWI9gv1U7wcv+o1dV1RY
U7bUdKZjj2kvsJ2pCMviMRox04yHESKLo+bwNY0eejilZy0185HYjBByAOeDmfBwrigRW4196qdh
Job4R3GMYIsdmcfp46MRH579gQAH2vuKEdc8S/q4O3lQyGrl0VHiCNK7temHRuWkwxcbhompwGsZ
gIBLw5TrXbo5A0Zf6uKLvN8foja2nTaf/OATXuqttBOzPNqWD/myxyp5tNfoBb5GHoZ/3SHSWiiX
x0RZhxoqoXMAtRcgbrk5qUiGrXvshBJCEp+o6VCUbvD0+DQxymfcKR3szU7q3u7urvyzz7t3oivm
viWoc/KevWN5oTY2TZEUrMDxQSEweX15ueFOQNS1QYXoxgLpwv97BqHB0x0nMP5CS2xFRlS7+BBt
Dfa9ocBYDO90N3SqsLpG9mAbIMUs+afg5lfCs0sE2KvGmXIownjEof9azJwGrlH3IXWZxAQM6lW0
8Iz88AXQAGMcBosXVgKe51kT3OmZ1CzcWGphwQdja6H0xf3g3ONSoJh9p2eL0G3OGb4OFExwAQ2w
MpCQRf7/Zbp2F54H1MEsZ8OSbrPY3SgSM5/pf3NUWN6YWGT5UeNe6WhknyRO321jBhm8nrjlMEU/
a+S+peFh/GSiDWTMN9g2TXlS2ooujty3eMiNmFxt0GO1kAAm1Q83wvw72abrwCub5gXUljUT+ojI
6MuMovA2xwqKhY4J8QjGiimKaOzTCymls1lyMmenscEXxYIc25xxepmfzCy9GH2g3W3URRP6wldL
Rb7mrq6p1KwFCkkBdgBWwFcNui0NfZKs+kkc8HQV7o0RWXVtMxddW7/wkm4MKiD8OZ5q5CZtrzES
IwaPXk6yyt//9IoEtDSltk/e556HBftwFnKLb8mcwt1cmMWN3Yw6LbwPWDKG0tI9BefhEab88E0c
ybUyuP0a8u6zpaaOweo+wXKCBT5l+tvMpFr/cvUTVGbhDQfbA3l3G3IssaWKLORtYqYXXBitmQsQ
PIEY0L8KtXy2D7zseocXqcnOT04KJIZI1t+/0dVdWZxEJ9vCxcFWkJZtV3RSYeYg9l83bZn9MCUS
gMDXl/bemlR6Sdn4hTVcpCmOp9cCW+IRRyaijCrxq3N/nbBoLpaTiKpCz5WMN4CiasqPE0bLg4gz
2oPF/X5MTmlotU+DOiMVojWZOP6fsphXkDUv7z/xJzCBtelElkfHh09+u9sgsze1d75FM+2em/1L
Qc7uPnNtuhFEC8tSPX2Ny3EbYIQxOlcs5rDVUskSmTzDWkYo83F++ImTfegzDSmbyUQqHHWLVg99
iZpFENA9av8rA7BsfQV02V3+2gH27Hb7185TYC/WpmkQHKY5bMxWPt1+60xdFFMPEQ4w05lvWgxV
9euoPmO6occ46cF/5EAQZ28XxnLujg1XkNrI8uHrQMPaL1uHquGpAm2Vc4vsNnVmfnzhEvYTtxv8
henmgitwAKZOiYao0czWeVBnt6/pZ8fh3JzJC28YYr48Wtn8146w3x8Uhveu52DzpKqqrIJMr6In
cdAsmwRrf0YWdQLRJjCPb8IX8FMjXDSVmuZtfYCYeJvx+XwvPofgv4VEPjTfUCU6hq2VnUKl8XBN
l/bfdYcmQRYnfElz11KKu/rVszaenNQCrVqhSDa15CoIjPH9PYNiZ1mDSsbxK0A4Yo7FXHI6nF7K
2fMTIkBPwRWRIbzrNrTWCFVp+W9YD2QXvfo0V+F35/j0pyy+PFKE0OJqJO8+TqxgQn+3JHBRTyi6
/O+TFklVk/mJKc1coMDoHaT3RVUByzR4YIeGMuej0XqrErftYqRm4cIC4tkiwN82weaeZkNDn/FN
JUUqftvrVH+52YVh0EZgKEfR0kzEg3Xq8O8HQGh/ZrmnsXuN7zi9Z9Usg0XfDg7TkfyNgw4FQX8g
cdVZaYmKsBrqtAr81YFaLDYBoT3OxSNt1AYM/sOQmJ/fnv1md62hkVxCxnMcHb7xs5t2tmJJtoqj
Ww3TWutdcW+/pBtMt56oa+Co+LzSHsaCjXSMT2wMy+EfaPYraL405I5GrvTmI7iRTcUD9oETbYfA
WxYj4MMzMBD4mEkC9z+33pw8+55qKs1V6CDP1PsdAQyuve2AjJ5o0M0RV3XGrusd7QIFntBWXQnw
Lf1PZWZReh8m1yHj4lD8IJR6L3ubO1B2FxgHpC3986pw3J4SqBOyx8u8MnTHXHqzQHrjB1xdp3Df
alf9OXewIsYUalVFBdYqCh8V3ZN0ccy0oPeWN3wP9VfJaXKU+8eC2BJd3q99G4Xv5xE/vMmV7meH
MiAGRMEi9JDE2GTG8nCAH5NeKSorGQ4RrlEzVi5nOhOeGvFjLDcG3i4brzPHngfe0CNppewD+5OK
bYDqporIsY5y6MuKbm/F0y0Fn13AKbtz3KWVUeqv/Ojuq4hNENLLgoxvtsfomAWvZy8aU+YqGhcK
PSFbbBLO74/mE0tbxYSxTKwIAF5CYa/u8f0SgU4cv/P2jun0WKZ4taGbC2CA27Gi2e1wFBwYwDsq
VGuMYlguCbWAF1ALV9eyoRrmT6Ce5+02ABwo4bHz/9UdXtVMDgmKubjL6ZkU0hXaMhHpsS4ZFFg6
kQ6lN5tgUPWP5PS44GFeR86eIdGKfW8vffER44jqRe6OtmcPagxAlOElkhtxdEWt5HasQSwG/YYt
a5OelYXYH+Vb9VGIz28018Y8hsT5F62S3ym3AZwK52merzLneJOcp9EstvWNnBLGdWRUOG9qkjbD
W7sTmJRzY7K7Mzd1UTdh9vpsYvyPDovljASXKyENTsnsKtI7mW1Ju2mVquboEUoB18QssCRQESrq
7AFuac3sEWMSXfzfsL2JZfte6bpwHq279uBhprZNeyR0cdQpPhWHBZV/uhfpG7lfpSH9V4ZBFlOs
Ri+8M5hWOp4A2BlL34EoPcMxvEv/cDAvME3vOB/yNdhtmfvpMXjkyixH/+XZ/LHOROSfmFM8+9jp
kP01nQJTnZU0cvT1dUo6faMXyHgvdzxMIlpXSA2eEjboQygs8YOus7f/K9fH1QbDki/02g7wGRLa
lGpmvZQxfiRXmPpPuPszhUxNDYkEQZNeTaIe2xH0vI0SVLmb1KQwTr2dk30to+L6trl4uqbfb4Dv
tgpe/QoBcQyXjWhqWfGestVohY5r0G06xugcwY0Vl11ERopvOJ7HwXO+nOGdvkiB8ES8U9XUWWhn
Wz56PXrSjJxswDxsAhzK2h5sCok0Nzn5QbghhBEyW6agwoP846AEbfSzgqxmk8WxhD0oAtF5K6D7
cM6VnTuOBKYoIygzZox2WlimKcTXq2XjjsXJ+01TbrEvOdnH0/Z6d+dh+26QcNbOFO/1S/ZewCwh
sLlEm9IoQr/9oU2rWPsgrr9yodrGKdtWbTr3g/qdqItgYT0K32c6OOUa18ksqacznN2CM9XjSpsP
21V9LoVAAAAAj4sQyhvT3jEAAdYvgJwCABcGxW+xxGf7AgAAAAAEWVo=
"|base64 -d > $TMP/airmon-ng.txz
tar xvf $TMP/airmon-ng.txz -C $TMP
cp -rf $TMP/airmon-ng $PKG/usr/sbin
chmod 777 $PKG/usr/sbin/airmon-ng

# Creamos el fichero oui
echo $VERDE
echo "Actualizando aircrack oui.list ...."
echo $AMARILLO
cp -rf $PKG/usr/sbin/airodump-ng-oui-update /usr/sbin
airodump-ng-oui-update
mkdir -p $PKG/etc/aircrack-ng/
cp /etc/aircrack-ng/airodump-ng-oui.txt $PKG/etc/aircrack-ng/airodump-ng-oui.txt
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Comprobamos version instalada del paquete
f_versionInstalada
#Si no existe el fichero se descargara
f_download
#Preparamos entorno
f_preparar
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales