#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20180520

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=arp-scan
	EXTENSION=tar.gz
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=https://github.com/royhills/arp-scan
	VERSION=$(curl -s $WEB/releases|grep $EXTENSION|head -1|cut -d / -f6)
	SOURCES=$VERSION.$EXTENSION
	CD=$PRGNAM-$VERSION
	DOWNLOAD=$WEB/archive/$SOURCES
}

# Comprobar dependencias
F_dependencias(){
DEPENDENCIAS="libpcap
perl-net-http
perl-www-robotrules
perl-http-date
perl-file-listing
perl-IO-HTML
perl-encode-locale
perl-lwp-mediatypes
perl-html-tagset
perl-html-parser
perl-http-message
perl-http-negotiate
perl-http-cookies
perl-http-daemon 
libwww-perl
perl-Mozilla-CA
Net-SSLeay
perl-Net-LibIDN
perl-IO-Socket-SSL
perl-LWP-Protocol-https"
f_dependencias
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo 
echo "$VERDE"Configurando ..."$CIERRE"
sleep 1

echo "/Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj4An/AaddADmbyI3LPOCbhRpT/bL8xkExluYKu8oBXO3W
H0VEhCLLNzZNMGdcv1TO4vw4m6mX0IjMFJdTD5MIPk/OSpMBWw7rAlqVKB556o0BT+uN246SkiDF
YyVSz2Z5DC+VNd2hobi5N38R2d8nDXQdTzRCMwelKVYBeoITtJhNYseHxaoJnaQr/3teTmw1n0R5
IMkdK2rbXRQdXzW5bYsbhV3yXp81FYz1v+oShNtNGZP9PfFg7snVYj2KoiJd2nucw150TwQQC5LD
dJ3ZJ2Gf1Yp3Q7Fs5MZ3Imh2xelyTXlwLFxNDn7iaxIxhN3i3P6D+ft8YjDATuaW+MN2BjW4Qy3y
P3jQ//T4GCinhn1qHwCeOcgUB7EnD9Tv9IqOw/4hmVSYaE0g5VRodXYB2QrKzsCXSJkOX/9RyYmY
IjH3zninZhi41KKDxaW456Y1tES0ZQmiZsxdX+NxSzpiWUWgWZHBIcPHsdooxbb93lI2tcm8nm1l
YMQueMxBxJkBZVqk3k0FzB3/xKOSrOd533gvRwVWzg5LyDV1OuVjdhCmzmea8rXWUcuR9hZKAAAA
601Zb7ohvuoAAcMDgBQAAIB//+WxxGf7AgAAAAAEWVo="|base64 -d > $TMP/patches.txz

tar xvf $TMP/patches.txz &>/dev/null
patch -p1 -i ./socket-error.patch||exit 1

autoreconf -fiv
CFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --mandir=/usr/man \
  --build=$ARCH-slackware-linux

echo 
echo "$VERDE"Compilando ..."$CIERRE"
sleep 1

make || exit 1
make DESTDIR="$PKG" install || exit 1
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Comprobamos version instalada del paquete
f_versionInstalada
#Compronar dependencias
F_dependencias
#Si no existe el fichero se descargara
f_download
#Preparamos entorno
f_preparar
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales