#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20180421

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=ettercap
	EXTENSION=tar.gz
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=https://github.com/Ettercap/$PRGNAM/releases
	VERSION=$(curl -s $WEB|grep $EXTENSION|head -1|cut -d- -f2|cut -d t -f-1|sed 's/.$//g')
	SOURCES=$PRGNAM-$VERSION.$EXTENSION
	CD=$PRGNAM-$VERSION
	DOWNLOAD=$WEB/download/v$VERSION/$SOURCES
}

# Comprobar dependencias
F_dependencias(){
DEPENDENCIAS="libnet"
f_dependencias
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo 
echo "$VERDE"Configurando ..."$CIERRE"
sleep 1

echo "/Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj4EH/DixdACGVhKr2tHACSS/2PTHE149wl3slQ3ajRJto
O3N06eX4b0cRFJv1QTHj4C+y74CE+0nbQE+kkbYJtpus/1gdPqDouuwWjvjvd62E0/DoVi+TcPx9
uoghPj8c6znceQXUEna5mbckV+tuXbkcMXP6PaL+ZqvqJN+cnFmsdOgix/H1t/bokNEf1IbDpDBO
7NjmdTiCCOR1sQGifUXoB0nALz3VBs3pQLX86MH+R409FvE7uxIJbeRHrG8BJsROFUJO8xIxEl7u
5j3TS6yBt1y9LhJZfLiW+UtQwA28AmB7lXC09YJ0s3JtZ6O/EmEJiffuJ9+nGEu2/ENEpl4r/DEP
rllY7ofBP9IhzsueqsM5UWA5gV2VWID66ebHbCsAhyExHolW5Z3wMBd6hGiL+EloJ3WI1ZHTgQai
nbj9MSpUCU9K7QMepJNVndqfs6d5twvTMgWiItKR//tlr9wiTP1HMluSo4JRszptfvKNzvGo6oPU
XGzqPsGjTlzNHGid8/J1QP8NeiF0+JB9WiNDFXEdXy4/ZwhrDl32uoawqDCCG0N5tkS6TB/O0b3c
hBds4BSgowyWFNh2MsSra7C2bNq8A+h1nTHMeLxGK3xudUfNAXXLUp91Z70ZIz5P+Db04GL01B0s
HwNO/xd1qQkvv7rHqnYlFsEGq34EJCc5UoXgjhanL/+ZwIxi+LLHQatNpaz1W3D2W3OjepJmdPhB
g1OeeWC5WqSlQzYVYY98QmmdobpE0HPZp4LIk7GFiwgKpTpDMsWghXSKcK1FOXkr92VaME8MW80y
PFp7tWyqrSK8LvFGqQamt1P1rbP8+zKrYtht9KcsfhiyZZN7q3WkX50uSUUKNcfpazUlHAbZc9EF
C6gINhdtQ4OEaABJpppog1LQjLfbr+j+2DLyZnlrjaezdyriEpsX5D2SGzuDbE+QPowK5P+SodmW
dg6hQ6q6ZeCc2KgRG+b2MWS1TRKK8ATW4NAgVlI/pOj52bHRE2W1WLID1C2bl77dS4JH4DjrTRf5
UZzs0Y8Fy7EBdl7mgiAEY4VMtRPKuEFy57hdgg+01u3un+q57Oqx43jfVcz/eAC9vBz7tuGvylA/
97X+1tBwDTjGtqmDYzCbk9m6Pk67RYDnvMIiZkKNxrYX6dM9zs4rAYDOzrZF3UjCkGBDSu++GA6o
WB/jigUd9UqMFcyo2DMu/U+rop1AEACAD9M4JSg1tcNF4ah7xuueZT/qW2sPNoTMsaLYcJR7R20I
oe3HwLwaR31rv2Ozv6J09z+xd5TCdRmVSqxk7S9l1ToUC5ZHRQ/KTmF53J/HT4JlfjOYJJQEL7rO
XWX1V2nO4nRrPSsJsRtcA7e3YtPVe9APxZGmzB3iQufGgnIf4bYwNAewvNEeXEfuv0g+mokD2tMJ
pnuZVGyWRnxOUP2wfBLbkWI9dUuHO5F3ezkuXhMrEr9Lf7nqh1wxkFEgIW1cOdl850u+0lFjZbZC
WuJBAwmrhaEKShlcggn54zI7kJ5PCv2s8fIwLFoftbTY6cQVWPKu+VGeaOeBd1S9wFq/nrlDVD4R
4akjlKziyw7h41VoN2fAVlbnlog6ia/I8PB50nZxulGanrlxCECGjCBKhPU+VLC47Yfy6q0RsH9o
LkfUgxxw7hPqQcTymNPb2WmZsARwjK3//B0HN/CcJW0cdizPy2/2rzEp9bQK54PgkjHRXhFTxs/k
T6XDu2a7y09s884inND6jcPLoVT0LKhl7oKv9ZWO1tUv0GDu5rNT1HXq8WS/Zfyh69R2b3O8rvl1
r3DN2ZFAHoiCFGNztkztDixxgNZMHTRCMwTCTVyU28+AHZQxEEB+Yms+RNEIHM9xEa8aELUsOejE
pweVu4D9d7TcsVT0D1PoBngof6H7pJDa3WMJXmSeu0ftKVWLrsSSLM9c+0AAT5yYZoY1xIShR1aH
PKe7sEpHKF022PSpthhLWqyHFEuTotR7nON1LjhwMdVooWH0Ue98c+j6Zcv30vugJ6/L7EzmIBDV
PvZLJS122IHvOYyDBXiE9Vpw5xYvc77Iac8iBskfcJwkzjJlawjImiVcrZoNrlgCT429b/Jh15TA
/X62ZitzkTUPryVDZSeARWU1vjoBpmnHh+PUNL/ZeVSkvoIcfQ3qdmThKsgPZVWgmcoYiPXgrm6c
xLtAJ4mVsSKCmlSWa4ONY5z6nRkGK9kYnJcG2ycMvdOiYbxHi5/ZtB60avdiUDf+JIs8Ga707hbS
d6gYQCJPZm3/f+RrESoMS5L/JGFsNV3zOMHKxt00IIwYYk1A2EmBA3RGSoz7jQJrXxmacGBNEb8X
cMwgNReHGRammABgmGD6RQejW0tP5+Ua0gweLF5qtL4ech5nuBRAyBQbFAgDAzoX3QFp9as2/xDN
QrqyaLnYXBa+rrA2ybON7Bf9LN2ZsNuMBwo7IolbXa3N7z5C/GBZxLGgPUd1jupjNecRQVtierI1
2BTSGJ9tb2VvLR1xOgSQ8PCZW4RM025a7nCQ0CSSboqVrV4l8teeFB5b+HcHi2BC24DjWQjqtqdc
zTU7xIQdIH+aP4TzNHOUPszytTmz+ZmL21FGrMJ0lBYvk9SolBnLZSAXulKXISv09IubdwPyZAty
0m4CLG2Gyq8GxMl9nvuWAAf3y3xZz734Irx3yRmxJdpSD8wS+fq0wsiasptlXdn/pDrFJMRJqgTt
4hL5rrGtS7Me3gphJQN2zjbvbHU3Q67NKI+hpFV9I5hhLQHNfbtKS/HBTfg7oCiMFq4IRndSViVV
xpacbR9grOEOs4Mbc/4Wn+AambYVtf4WNrtI5N6MUz9Geu4aKweS9mDTq9iyJYlhsiUuTJ8aD3RH
0mN0E3SyC7CMPOhgc63auRXdiZ4WqId+HExU0VkGupHt0lcDBfwiUNNQIKD36Y32yYEFL+gAv4Jy
WHSrk9SXyFQ4cSX2xCf0DrlwnaoukgZcyLd9JS1H51ayEtPyY7HOU6ijAUOuolKsxNrgmnsY3oTb
Q1RsXzLj0h9CWB42hbEeyctjA0irIuyU8HtFZhOmTXsU7Thm2saSZSKX5YUEYB394dn3DBXbJvTr
2e2Gp00cy9aiH2DISaTVjYXZeSAA9ieCqSY12xMSJE8NRNXY+ovesaCeoVkWmwHoaS6EfpAHC6FR
0TqBl+jZITs6rxK0t9ThavjjaIoKmj/ro0WJ5wPm8DXwO2Jgi52LdQRGE5U4n8C9wnkgoYC36Sgk
uzVl+TnnuHYfS6IAMnd4GahMoiAG8WqC8me8F+hOvMwcAhijYTvNrFUjnCKwcmBYV3CMyKKv3A3O
In83vaRijxXEueGdetzz5EEbG3vB8NVn0evvUYaJXUGFMEQIdstVkg7BCk06Tu9v12qB/7/aQTW5
0YtnIlqbu83TXz0Y5CrhtHR8mIh/FFogMAXM8i9TXj7LE24VpOfz1FjGuy5fW1XM6yiisv2TyRFt
Bzd3Df0rA5xLAQHnkkYKo9EVi6OKJT/22XzN+RCwYaZvRh0KEJ5YZm7yW+Q0oCsAJO3MsjgQIsdD
a+XltAmT2kl4y0r3sw/9aArdS38G60YZ0w3DoAymotQl0rEIw5sXOhU7ez6xc8bI/z1c2AFbvWYM
RKk5f35fLJQT0z/ns/2W2dbk2pqXPIQxFP1LV1U7G8BqkPUlJTh2fBekzUyi1tiaLsuZgbBu5UPA
pFe6NpVYm2x0BZLyAc7jO7dBedfaN0g0SfeWTPrfZd4R1iOP7wVT58IG26ZI3Ba3LZnFN1rElsOb
qmy6Q5jnkKzT7roxV0Rq3LnynKmW7NAt1gEh0WnAlqCGKIfYEh1PUkul5nFE2BvRC4ZosaBRWqMZ
OpmrY2FGSc0e0IZD5yAlVsHRTs9Hak9vwg/Wj5urV5jMxnSTnhj9etSmwKUYeBL3lgoeFnyGhngH
cDzRBYhocaylRLAR920R1XnNl/1G2xNtihVtbzFmmfa1jrbGm7Wpm2bOetj6+FodkaZvB4jIWLPN
X5FohEUZ7fhCH7AXcOiDLKwKVD1NaK042641iHR+HluQ6tPUcQ7C9EundZf88U3qaY07sz7SjCMp
PQ4gsDciysx5kCgtEbvTefVnoSrduKF3Pr1sU/P06j5yqOLzMqRQJ03sigQ4QUA9fdL5GyMMua7V
XRf+eB/skb1JPxLWYB/4guB+OBwAYeuybeqtN+kTr+62at1m2LeUGnZEK2BYilUnSH+Bfzt09S57
+hjzhZgVqS04dcYxyxazG/2Y/c4g7NgCwpO3p9wa7HZnIDb26nWsRH7Jf0o0Wx4oy+uxlBixk+wM
L6M9auZyVhwoS57RgqZjN8dZ7/mbxfodeIdZMQw3sGjYfXCy17oek5sjhNMnlIWOVmT38wcvCVf3
QictjjH9MXXD6IO/1na8ppg8Tvg9rvCMNq2iPtDqXfd7J9I8QKnN0sUpDCRpMVqNObfXcvqnegdX
vVP/6EfGK2IXtBaHTmS4f23p+lATZXinrhHbjM0CRcKdy5zuzImOb1aqVqM+uYijrkZi6pGR5MAx
WKSsRctwmy07+A+mVHB/rUwkBYV/iSIBJRYT47vGLtmlwgsH00UUK4CwHcUkiy89pDe7I7VOgsN7
9yhJG4EIncBkVyRdyeZaYUIv5wXNCEKe+kt24nF2TikvrqWt+NSvVcc2KZBTECxkkMP64EcBaDog
M37//6alt2S5OpjpxLdUZvGkODEFCHflHj7tznxaMu80bg+0MJmGfS9a5iJ7BYlOf6U1yrPce/iA
aFtIUawjps7hwNDHSk8+mSthstdZb9+FFXeSyOsTKtNOcfb4Ch0vx0vMhSLP92cLzR1jwIR2XOa1
wWny7zGHqUUh3QAA7Fw3Taw66AUAAcgcgIQBAKEGgImxxGf7AgAAAAAEWVo=
"|base64 -d > $TMP/patches.txz

tar xvf $TMP/patches.txz -C $TMP

patch -p1 -i $TMP/CVE-2017-6430.patch||exit 1
patch -p1 -i $TMP/CVE-2017-8366.patch||exit 1

mkdir -p build
cd build
  cmake \
    -DCMAKE_C_FLAGS:STRING="$SLKCFLAGS" \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DLIB_SUFFIX=${LIBDIRSUFFIX} \
    -DMAN_INSTALLDIR=/usr/man \
    -DBUNDLED_LIBS=OFF \
    -DCMAKE_BUILD_TYPE=Release ..

echo 
echo "$VERDE"Compilando ..."$CIERRE"
sleep 1

  make  || exit 1
  make install DESTDIR=$PKG || exit 1
cd ..

# Creamos un nuevo desktop
mkdir -p $PKG/usr/share/applications/wifislax/Redes
rm -rf $PKG/usr/share/pixmaps/$PRGNAM.svg
rm -f $PKG/usr/share/applications/$PRGNAM.desktop 
cp -rf $PKG/usr/share/$PRGNAM/$PRGNAM.png $PKG/usr/share/pixmaps/$PRGNAM-gtk.png
echo "[Desktop Entry]
Name=Ettercap GTK
Comment=Nework sniffer/analyser
Exec=ettercap-pkexec -G
Icon=ettercap-gtk
Terminal=false
Type=Application
Categories=Redes" > $PKG/usr/share/applications/wifislax/Redes/$PRGNAM.desktop
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Comprobamos version instalada del paquete
f_versionInstalada
#Compronar dependencias
F_dependencias
#Si no existe el fichero se descargara
f_download
#Preparamos entorno
f_preparar
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales