#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20181028

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=hashcat
	EXTENSION=tar.gz
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=https://github.com/$PRGNAM/$PRGNAM
	VERSION=$(curl -s $WEB/releases|grep $EXTENSION|head -1|cut -d / -f5|cut -d t -f-1|sed 's/.$//g'|cut -d v -f2)
	COMMIT=$(curl -s $WEB/releases/tag/v$VERSION|grep -m1 commit/|cut -d/ -f5|cut -d '"' -f-1)
}

# Comprobar dependencias
F_dependencias(){
DEPENDENCIAS="ocl-icd"
f_dependencias
}

# Descarga los firmwares mas nuevos disponibles
F_descargar() {
echo ""
echo "$VERDE"Clonando $PRGNAM git ..."$CIERRE"
git clone $WEB
cd $PRGNAM
git reset --hard $COMMIT
git submodule update --init
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo 
echo "$VERDE"Compilando ..."$CIERRE"
sleep 1
sed -i "s|/lib|/lib${LIBDIRSUFFIX}|" src/Makefile
make PREFIX=/usr SHARED=1
make DESTDIR=$PKG PREFIX=/usr SHARED=1 install
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Comprobamos version instalada del paquete
f_versionInstalada
#Compronar dependencias
F_dependencias
#Si no existe el fichero se descargara
F_descargar
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales