#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20161203

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=pixiewps
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=https://github.com/wiire/pixiewps
	VERSION=$(curl -s $WEB/releases|grep tar.gz|head -1|cut -d v -f3|cut -d t -f-1|sed 's/.$//g')_$(curl -s $WEB|grep /commit/|head -1|rev|cut -d / -f-1|rev|cut -c 1-7)
	DOWNLOAD="git clone $WEB.git"
}


# Descomprimimos el fichero descargado y compilamos
F_compilar(){

if [ -d $TMP/$PRGNAM ]; then
rm -rf $TMP/$PRGNAM
fi

$DOWNLOAD
cd $TMP/$PRGNAM/src

CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \

echo 
echo "$VERDE"Compilando ..."$CIERRE"
sleep 1
sed -i 's,/local,,g' Makefile
make  || exit 1
mkdir -p $PKG/usr/bin/
cp -rf $TMP/$PRGNAM/src/${PRGNAM}  $PKG/usr/bin/
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del script
f_versionInstalada
#Compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales