#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20180723

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=wireshark
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=http://www.wireshark.org/download/src/
	VERSION=$(curl -s https://www.wireshark.org|grep -i stable|head -1|rev|cut -d ' ' -f1|rev|sed 's/.$//g')
	EXTENSION=tar.xz
	SOURCES=$PRGNAM-$VERSION.$EXTENSION
	CD=$PRGNAM-$VERSION
	DOWNLOAD=$WEB/$SOURCES
}

# Comprobar dependencias
F_dependencias(){
DEPENDENCIAS="c-ares
GeoIP
libdbus-c++
libiec61883
libxml++
libconfig
libffado
celt
jack-audio-connection-kit
portaudio
krb5
libsmi
jansson
nghttp2
spandsp
lz4
snappy
"
f_dependencias
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){

# Configuramos
echo ""
echo "$VERDE"Configurando ..."$CIERRE"
sleep 1

echo "/Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj4Af/AT1dADIbyAMZLj8ePy2fI3xKp7ZGyzx38+Fs27KA
gRW7JAGBqsRX86QM2uuDq1jBzbKeizv+5l412P5LWY+ZZMUO+zoiCdpEG3zrr6h2HgxJd1Yd7dpL
BQ6q3d1YnZTutU6cw4M3BT2CbTndRuxHUFraolM6/wMhEVVNK1oyeDDmxnNrVuDh/EJAizRHW/NU
pj5oASxraEyE7llQvRDcZlFv/a9XEk2Fz54f4XifrEa5JspzajUaue0aK8g5X8d8ZRWaUU+h5kCq
j4+pne7HbUs49OljZAGoH1AN8ohqyw8usIO/1ADtb6AnzGTarI6Ek1zy1TZLpmz4odPReFD3kFX2
9bySnYHwk7q8TsNJ2NoWsbNGbJBVnkIA0xYN+Da5xC7OWZZSfb4N3zPeZ1wBcJ8ZNwCZD01NL7zk
qZAORDkgAAAAAGYBDA9G0HvZAAHZAoAQAAAR39t9scRn+wIAAAAABFla"|base64 -d > $TMP/patches.txz

tar xvf $TMP/patches.txz &>/dev/null
patch -p1 -i ./do_not_use_svn_version.patch||exit 1

# Esto evita problemas en sistemas multilib
sed -i "s|/lib)|/lib$LIBDIRSUFFIX)|g" configure.ac

CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
  ./autogen.sh
  ./configure \
      --prefix=/usr \
      --libdir=/usr/lib${LIBDIRSUFFIX} \
      --mandir=/usr/man \
      --docdir=/usr/doc/$PRGNAM-$VERSION \
      --with-qt=no \
      --with-gtk=3 \
      --with-pcap \
      --with-zlib \
      --with-portaudio \
      --with-ssl=/usr/lib${LIBDIRSUFFIX} \
      --with-krb5 \
      --with-c-ares \
      --with-geoip \
      --without-lua \
      --build=$ARCH-slackware-linux

# Compilamos
echo ""
echo "$VERDE"Configurando ..."$CIERRE"
sleep 1  
make all || exit 1
make install DESTDIR=$PKG || exit 1

# headers
install -Dm 644 *.h -t "${PKG}/usr/include/wireshark"
for d in epan epan/crypt epan/dfilter epan/dissectors epan/ftypes epan/wmem wiretap wsutil; do
install -Dm 644 ${d}/*.h -t "${PKG}/usr/include/wireshark/${d}"
done

# Instalamos entrada desktop
mkdir -p $PKG/usr/share/applications/wifislax/Redes
mv -f $PRGNAM.desktop $PKG/usr/share/applications/wifislax/Redes/$PRGNAM.desktop
rm -rf $PKG/usr/share/applications/*.desktop

# Corregimos nombre de ejecutable
mv -f $PKG/usr/bin/wireshark-gtk $PKG/usr/bin/wireshark

# Corregimos entrada de menu
sed 's/Network;Monitor;Qt;/Redes;/'g -i $PKG/usr/share/applications/wifislax/Redes/$PRGNAM.desktop

# Eliminamos los ficheros .la
rm -f $PKG/{,usr/}lib${LIBDIRSUFFIX}/*.la

# Creamos una config basica
CONFIG=$PKG/$HOME/.$PRGNAM
mkdir -p $CONFIG

echo "# Main window maximized.
# TRUE or FALSE (case-insensitive).
gui.geometry_main_maximized: TRUE
# Warn if running with elevated permissions (e.g. as root).
# TRUE or FALSE (case-insensitive).
privs.warn_if_elevated: FALSE" > $CONFIG/recent
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del script
f_versionInstalada
# Comprobar dependencias
F_dependencias
#Si no existe el fichero se descargara
f_download
#Preparamos entorno
f_preparar
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales