#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20250407

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=four-in-a-row
	EXTENSION=tar.xz
	GESTOR=wget
	echo -e "\033]2;${PRGNAM}_updater\007"
	WEB=https://download.gnome.org/sources/$PRGNAM
	#RAMA=$(curl -s $WEB/|egrep -o ">[0-9].[0-9]{1,2}/"|tr -d '>/'|egrep -v "1$|3$|5$|7$|9$"|tail -1)
	RAMA=3.38
	VERSION=$(curl -s ${WEB}/${RAMA}/|grep LATEST|tail -1|cut -d- -f3|cut -d '"' -f-1)
	SOURCES=$PRGNAM-$VERSION.$EXTENSION
	CD=$PRGNAM-$VERSION
	DOWNLOAD=${WEB}/${RAMA}/$SOURCES
}

# Comprobar dependencias
F_dependencias(){
DEPENDENCIAS="
gsound
"
f_dependencias
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo -e "\n${VERDE}Configurando ...${RESET}"
sleep 1

meson build --prefix=/usr
  
echo -e "\n${VERDE}Compilando ...${RESET}"
sleep 1
  
meson compile -C build
meson test -C build --print-errorlogs 
DESTDIR=$PKG meson install -C build
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del paquete
f_versionInstalada
#Compronar dependencias
F_dependencias
#Si no existe el fichero se descargara
f_download
#Descomprimir sources
f_descomprimir
#Cd a ruta
f_cd
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales