#!/bin/sh

echo -n "#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=$(date +%Y%m%d)

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=
	EXTENSION=
	GESTOR=
	echo -ne "'"\033]2;${PRGNAM}_updater\007"'"
	WEB=
	VERSION=
	SOURCES=
	CD=
	DOWNLOAD=
}

# Comprobar dependencias
#F_dependencias(){
#DEPENDENCIAS=""
#f_dependencias
#}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo ""
echo "'"$VERDE"'"Configurando ..."'"$CIERRE"'"
sleep 1



echo ""
echo "'"$VERDE"'"Compilando ..."'"$CIERRE"'"
sleep 1


}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Comprobamos version instalada del paquete
f_versionInstalada
#Compronar dependencias
#F_dependencias
#Si no existe el fichero se descargara
f_download
#Descomprimir sources
f_descomprimir
#Cd a ruta
f_cd
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales" > /root/Desktop/$$_updater

chmod 777 /root/Desktop/*updater