#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20260115
CATEGORIA="Reproductores multimedia"

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=vlc
	EXTENSION=tar.xz
	GESTOR=wget
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=https://get.videolan.org/vlc/last
	VERSION=$(curl -s $WEB/|grep $EXTENSION|head -1|cut -d- -f2|cut -dt -f-1|sed 's/.$//g')
	CD=$PRGNAM-$VERSION
	SOURCES=$PRGNAM-$VERSION.$EXTENSION
	DOWNLOAD=https://download.videolan.org/pub/videolan/$PRGNAM/$VERSION/$SOURCES
}

# Comprobar dependencias
F_dependencias(){
DEPENDENCIAS="
libsidplay2
zvbi
live555
libdc1394
libavc1394
libnfs
libdvbpsi
libgme
libshout
libebml
libmatroska
libmodplug
twolame
libdca
libmpeg2
x265
x264
libkate
jack
soxr
srt
libupnp
aribb24
aribb25
portaudio
schroedinger
chromaprint
faad2
"
f_dependencias
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo 
echo "$VERDE"Configurando ..."$CIERRE"
sleep 1

echo "
/Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj4Av/Ag9dADgYSu7FL5n6pvg745dpgzgztyjlznaup/Ke
xmcw6hscA46jeLPjahmr3sLXjaUJlHL60YiPWDZBkEp/BKC97GdmenZOC7oAz/o9rphcjimovbj4
XApdsquiAwjUHKIa0UW4A+2EdtSirC6eYMljpUY8g+X+d1evESOjmapW3hE/QEwgSITEPBJnd+aS
RKAUXkiLEFeA4+0oSfCdlrQJ9TP9dp805beUQCm8fY2qjXQ11aPZp85wJMZYY+HP1wcr9irWTtef
HCHIaqeYbK/fTvW2yHkV+Oi+ehnRLd4WtkX7o1dUm0F1icpL8KQNNTuFmoWl7zEKfm6kOv3HLM6l
Vrq4AJGtK2SWMYYk4/fyVj6nQs1b8qkztqwpDTZpTPfGgb/veShij03eXBzF8gow3C6avu934zC4
1Ykx/hCEqqYbxoAbrj3D1HL86oRd1BrWWZL8tZFKJU1D7093D1SZDoD22MgMDjgSnThcCrSlr9A+
a4MWuUyXpWX/JPJDbofBaRi3ZUMjFLr8jypiVusfAxtQ6+pSRO3/umrlHN9GEWy3dHOqdQ6w57MQ
PqHqoUQMMvTbhyMfuXFcMvREIm0+3FfMqzffoAxQH3iyQW26UD4b95eAlLszMKRQq8FO/vKIdPGF
FO8HTKR2PbJ2ZLUEd3mHKm5floIZNib73HDw+OQjIVW1hdx/TN6lJHNsNNb+AACYHYpmIDQ8oAAB
qwSAGAAAw9diurHEZ/sCAAAAAARZWg=="|base64 -d > $TMP/patches.txz

tar xvf $TMP/patches.txz &>/dev/null
patch -p0 < ./patches/patch_vlc_cache_gen.patch||exit 1

autoreconf -fiv

CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
LDFLAGS="$SLKLDFLAGS" \
./configure \
    --prefix=/usr \
    --libdir=/usr/lib${LIBDIRSUFFIX} \
    --sysconfdir=/etc \
    --mandir=/usr/man \
    --docdir=/usr/doc/vlc-$VERSION \
    --localstatedir=/var \
    --with-kde-solid=/usr/share/solid/actions/ \
    --disable-fdkaac \
    --disable-libplacebo \
    --disable-opencv \
    --disable-rpath \
    --disable-update-check \
    --enable-a52 \
    --enable-aa \
    --enable-alsa \
    --enable-aom \
    --enable-archive \
    --enable-aribsub \
    --enable-avahi \
    --enable-avcodec \
    --enable-avformat \
    --enable-bluray \
    --enable-caca \
    --enable-chromaprint \
    --enable-chromecast \
    --enable-dav1d \
    --enable-dc1394 \
    --enable-dca \
    --enable-dv1394 \
    --enable-dvbpsi \
    --enable-dvdnav \
    --enable-dvdread \
    --enable-faad \
    --enable-flac \
    --enable-fluidsynth \
    --enable-fontconfig \
    --enable-freetype \
    --enable-fribidi \
    --enable-gme \
    --enable-gnutls \
    --enable-gst-decode \
    --enable-harfbuzz \
    --enable-jack \
    --enable-jpeg \
    --enable-kate \
    --enable-kwallet \
    --enable-libass \
    --enable-libgcrypt \
    --enable-libmpeg2 \
    --enable-libtar \
    --enable-libxml2 \
    --enable-live555 \
    --enable-mad \
    --enable-matroska \
    --enable-mod \
    --enable-mpc \
    --enable-mpg123 \
    --enable-mtp \
    --enable-ncurses \
    --enable-nfs \
    --enable-nls \
    --enable-notify \
    --enable-ogg \
    --enable-oggspots \
    --enable-opus \
    --enable-png \
    --enable-postproc \
    --enable-projectm \
    --enable-pulse \
    --enable-qt=5 \
    --enable-realrtsp \
    --enable-run-as-root \
    --enable-samplerate \
    --enable-schroedinger \
    --enable-sdl-image \
    --enable-secret \
    --enable-sftp \
    --enable-shout \
    --enable-skins2 \
    --enable-smbclient \
    --enable-soxr \
    --enable-speex \
    --enable-srt \
    --enable-svg \
    --enable-svgdec \
    --enable-taglib \
    --enable-twolame \
    --enable-upnp \
    --enable-vdpau \
    --enable-vlc \
    --enable-vorbis \
    --enable-vpx \
    --enable-wayland \
    --enable-x264 \
    --enable-x265 \
    --enable-zvbi \
    --build=$ARCH-slackware-linux
  
echo 
echo "$VERDE"Compilando ..."$CIERRE"
sleep 1
sed -i -e '/^#define _FORTIFY_SOURCE/d' config.h
make || exit 1
make install DESTDIR=$PKG || exit 1

install -D -m0644 extras/analyser/vlc.vim $PKG/usr/share/vim/vimfiles/syntax/vlc.vim
rm -rf $PKG/usr/lib${LIBDIRSUFFIX}/vlc/plugins/plugins.dat
rm -rf $PKG/usr/lib${LIBDIRSUFFIX}/*.la
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Comprobamos version instalada del script
f_versionInstalada
# Comprobar dependencias
F_dependencias
#Si no existe el fichero se descargara
f_download
#Descomprimir sources
f_descomprimir
#Cd a ruta
f_cd
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales