#!/bin/bash

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20220129

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=firmwares
	SRCNAM=linux-firmware
	GESTOR=git
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git
	VERSION=$(lynx -dump -width=256 $WEB/commit/?id=HEAD | grep "   committer " | head -n 1 | rev | cut -f 3 -d ' ' | rev | tr -d -)
	SOURCES=$PRGNAM
	CD=$SRCNAM
	DOWNLOAD=$WEB
}

# Creamos directorios , eliminamos sobrantes .git y movemos
F_compilar(){
echo "$VERDE"Compilando ..."$CIERRE"
echo "/Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj4BP/A+5dABhoCEWkVCEyh/JK0ItzgRmFhm6NLSuMjSLX
N+iWTi2P5fbAJfF7FiBrn8C2U/Ic4VLQbBVS8pjvN0/eI45Kt5OsnOzkYfEr9fYV2V+7A5Ji7uD7
2Bs+UBDGCAMZiaPgsrLyKRbByRYvVfMDMeZV6Hu5KqKQIBZcuR3zpPdJ6SzVr0Sx7v4Hg2OIdyyX
r8D/k5GE4CGG9Jwl6js1ZWmf3KBKIBDOiYvjuNiHZCmWAg85YonG+Mbzak1uf55Y5DJA3soVHGlY
b/Ob2mZ9i8c0kasoz4844ui+ezf27lMO5fqH2jO/WMkDIyVsrx/VVGUs1ZEGiwYh2yjOcASwIy/x
S4tOBzdQhGk1yvJhf45tzrIvPEqKtPdm/dyopL84Oz/kY/2Qeq1CbxhJbwy552OkfJMubTm74NQX
Q8SEVyRd4cXe76Wxz2X9csmsB7Hrc0ROaLy8piaF8fZc5a8RAHFyvPobHywqOXuKpCxDEfVSlkaC
BdnSLyyukuo5y6wHb/DB9LFDPZ9VbNqOGJD9TUbEFll/2BwctfZ2e2HCW4zoQkd4YRJV61AauBdv
RIxthbwzpX+J2mW9DPfovydM/uoZ2XHUrTtTB5H4buu/f990uqG84LY3hVhSltBFNPvodQyet8JA
2cNpb9SgMZzzzbkCb+XW+On3/LX8SwDY0S4XEd9BrRNnGwK6ZWUtILjHC96ZsUr7pq1BZ6pcKevB
BV8RX21SMLyhB4gM9WDfdRtiuuBT2WMkdvPXLglePFyQIGc999QcLYDEzGfZ6j/9ojAeWdbt5Owd
PGThN7URBwcbPZuptKHMTlBRsd3PTz7cjbYTX3P3OlZ4mEBjVG3A+uZ7jpqjqggQ7LnGPsL5MQAv
sgd7iWzAOe61OAbE3I9XztYFdRJWUESGIePIwJwrQ7UVJ1lukUAc57Ph48a/bhE3m3vlNh3CpuIQ
g+y7A38T1dLGwpc39Gm7X7dB/5AV6H+rr6mGFUu2Y78ClxuSPU1x3Qg23HxDR8jmsa788gXw/2AR
KSfko2kkectHUqpecUEdxx1wbwF1nsJp8146pnd3t4zKYLTgq24ji7b0NhuxAr/+ZAvB/e0PNZ9B
WhQLQUx3lIro2ylJ/jA623ELwjuQ/ke4f7ToFWG0nwKj1DifZynRD3RanJm8p6NnyPeCUt/v1T47
K0iIdwap+U4X3U6kcIcOKaR9NzPurWwR/Zm0YndHoOo5Jb28QpXsKW7bydhaKUsLxFNoZo6gnWXl
nY8JXH/k6RlKDt543WHeKEFyW0LBsRsfVm7FlgfSLb9LVFQ78blEJ5zG3sproqUFyimc8EICEkjK
AIjmHYaribawZqAAAACUMgWGkcwrGQABigiAKAAAwQkJl7HEZ/sCAAAAAARZWg=="|base64 -d > $TMP/patch.txz
tar xvf $TMP/patch.txz &>/dev/null
patch -p1 < ./0001-Add-support-for-compressing-firmware-in-copy-firmware.patch||exit 1
make DESTDIR=$PKG FIRMWAREDIR=/lib/firmware installcompress
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura noarch
#Comprobamos version instalada del script
f_versionInstalada
#Descarga los firmwares mas nuevos disponibles
f_download
#Cd a ruta
f_cd
#Descomprimir fichero descargado y compilamos
F_compilar
#Creamos xzm , instalamos y salimos
f_tareasFinales