#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20250407

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=slapt-get
	EXTENSION=tar.gz
	GESTOR=wget
	echo -e "\033]2;${PRGNAM}_updater\007"
	WEB=https://software.jaos.org/git/$PRGNAM
	VERSION=$(curl -s $WEB|grep .$EXTENSION|head -1|cut -d '=' -f3|cut -d "'" -f-1)
	SOURCES=$PRGNAM-$VERSION.$EXTENSION
	CD=$PRGNAM-$VERSION
	DOWNLOAD=$WEB/snapshot/$SOURCES
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo -e "\n${VERDE}Configurando...${RESET}"
meson build --prefix=/usr --libdir=/usr/lib${LIBDIRSUFFIX}

echo -e "\n${VERDE}Compilando...${RESET}"
ninja -C build

DESTDIR=$PKG ninja -C build install

# Copiamos nuestra config actual al paquete
rm -rf $PKG/etc/slapt-get/slapt-getrc.new
cp -r /etc/slapt-get/slapt-getrc $PKG/etc/slapt-get/
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Comprobamos version instalada del paquete
f_versionInstalada
#Si no existe el fichero se descargara
f_download
#Descomprimir sources
f_descomprimir
#Cd a ruta
f_cd
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales