#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20220502

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=teamviewer
	SRCNAM=teamviewer_amd64
	EXTENSION=deb
	GESTOR=wget
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=https://www.teamviewer.com/en/download/linux
	VERSION=$(curl -s $WEB/|grep "*.$EXTENSION"|cut -d* -f2|cut -d '<' -f-1|cut -d ' ' -f3|head -1)
	SOURCES=$SRCNAM.$EXTENSION
	DOWNLOAD=https://download.teamviewer.com/download/linux/$SOURCES
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo 
echo "$VERDE"Descomprimiendo ..."$CIERRE"
sleep 1
cd $PKG
ar p $TMP/$SOURCES data.tar.xz | tar xJv

# Remove the dangling symlink first
rm -f $PKG/usr/bin/teamviewer

# Re-create the generic executable
( cd $PKG/usr/bin; ln -s /opt/teamviewer/tv_bin/script/teamviewer teamviewer )

# Create daemon
mkdir -p $PKG/etc/rc.d
echo '#!/bin/sh

teamviewerd_start() {
  if [ -x /opt/teamviewer/tv_bin/teamviewerd ]; then
    echo "[1;37m[[1;32m+[1;37m] Starting [1;36mTeamViewer [1;37mDaemon [0m"
    /opt/teamviewer/tv_bin/teamviewerd --daemon start
  fi
}

teamviewerd_stop() {
    echo "Terminating TeamViewer Daemon"
  killall teamviewerd
}

teamviewerd_restart() {
  teamviewerd_stop
  sleep 2
  teamviewerd_start
}

case "$1" in
'start')
  teamviewerd_start
  ;;
'stop')
  teamviewerd_stop
  ;;
'restart')
  teamviewerd_restart
  ;;
*)
  echo "usage $0 start|stop|restart"
esac' > $PKG/etc/rc.d/rc.teamviewerd

chmod 755 $PKG/etc/rc.d/rc.teamviewerd

echo '[Desktop Entry]
Version=1.0
Encoding=UTF-8
Type=Application
Categories=Network;

Name=TeamViewer
Comment=Remote control and meeting solution.
Exec=/opt/teamviewer/tv_bin/script/teamviewer -r

Icon=TeamViewer' > $PKG/opt/teamviewer/tv_bin/desktop/com.teamviewer.TeamViewer.desktop
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Comprobamos version instalada del paquete
f_versionInstalada
#Si no existe el fichero se descargara
f_download
#Descomprimir fichero descargado y compilamos
F_compilar
#Creamos xzm , instalamos y salimos
f_tareasFinales