#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20220827
CATEGORIA="Reproductores multimedia"

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=exaile
	EXTENSION=tar.gz
	GESTOR=wget
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=https://github.com/exaile/exaile
	VERSION=$(curl -s $WEB/releases|grep -v beta|grep -v rc|grep -v alpha|grep [0-9].tar.gz|head -1|cut -d- -f2|cut -d t -f-1|sed 's/.$//g')
	SOURCES=$VERSION.$EXTENSION
	CD=$PRGNAM-$VERSION
	DOWNLOAD=$WEB/archive/$SOURCES
}

# Comprobar dependencias
F_dependencias(){
DEPENDENCIAS="
libdaemon
avahi
cddb-py
streamripper
mutagen
bsddb3
pluggy
py
more-itertools
atomicwrites
python3-attrs
iniconfig
python3-pytest
decorator
ipython_genutils
python3-parso
python3-jedi
python3-ptyprocess
python3-pexpect
pathlib
pickleshare
python3-prompt_toolkit
simplegeneric
traitlets
python3-matplotlib-inline
backcall
pure_eval
python-executing
entrypoints
python2-setuptools-scm
python-jeepney
secretstorage
wheel
asn1crypto
pyasn1
python-toml
python3-semantic-version
python3-setuptools-rust
cryptography
python-keyring
asttokens
stack_data
ipython
functools-lru-cache
python2-soupsieve
python3-soupsieve
BeautifulSoup4
python3-webencodings
html5lib
lxml
python3-rfc3986
python3-sniffio
python3-anyio
python3-h11
python3-httpcore
click
CommonMark
python3-rich
python3-httpx
pylast
musicbrainzngs
bubblewrap
geoclue2
libwpe
wpebackend-fdo
xdg-dbus-proxy
webkit2gtk
gst-python
python3-sgmllib3k
feedparser
" 
f_dependencias
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
## Fix manpage location.
sed -i -e 's|share/man|man|g' Makefile

make
PREFIX=/usr \
LIBINSTALLDIR=/usr/lib${LIBDIRSUFFIX} \
make install DESTDIR=$PKG PREFIX=/usr LIBINSTALLDIR=/usr/lib${LIBDIRSUFFIX}
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Comprobamos version instalada del script
f_versionInstalada
# Comprobar dependencias
F_dependencias
#Si no existe el fichero se descargara
f_download
#Descomprimir sources
f_descomprimir
#Cd a ruta
f_cd
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales