#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20210925

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=libquicktime
	EXTENSION=tar.gz
	GESTOR=wget
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=http://downloads.sourceforge.net/$PRGNAM/
	VERSION=1.2.4
	SOURCES=$PRGNAM-$VERSION.$EXTENSION
	CD=$PRGNAM-$VERSION
	DOWNLOAD=$WEB/$SOURCES
}

# Comprobar dependencias
F_dependencias(){
DEPENDENCIAS="libmp4v2 faac faad2 ffmpeg lame libdv schroedinger x264"
f_dependencias
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo 
echo "$VERDE"Configurando ..."$CIERRE"
sleep 1

echo "/Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj4JH/G55dADgYSu7FL5n6pvg745dpgzgztyjlznaup/JO
xF1EYi3Gh2PqZw7VHmy2ViuVIYj4MSKpWCMVVJk/KZ0NbV12WM3GOvDmYYX8CAC+MitmbZxSvDMr
X4BjBr+0d79KC6zcr2vMRV7A6QgNdivjwN6hfkcwlbWQz/cfu+wlmZOOR+bT/vdEB7F5hQiauya7
ihiu49JNoxwQzcOl+l5HzXyU11fa/kR3v+vRDFBE+qdx1EFH4tHMp1Pi4dYDaB0q/24SIEe+kG6X
u8YckpVgjV8xYDqB9oUS9VNHQcf6M7NLAlGYMu0F2gbq14cK4jhTbGByzuRFMAPbTIeYr2RAp2Eh
eFITuVE6rutNDYKC3TXxqLLc6kxxuXjW8saMLgen10S3eZ9Wy/Hh6b+JvhqTkNY3E+sU15tTCYR2
lR9BYdy78JLY1GWmbq7Ypz5B2HWCfuv2nLrfQckyE5iThQ0qn7i+KbuiEfopf43ONI3LFxXvCHgR
hmephVFF1DjeB6+yVWouiHvEMOLcDByw5ISwEU6ngJ2PiYsScYh5TURQyYXhn3VKowHMuBnjSzwX
+V9iEnJUpv9RObNNWIg16LPxMsJSIXfx/PKo5wgfceSjZRnQOD/cQ7iPF5Pk6YtDrlmYGnipl6Qz
gaYLT48v01VYhR5CEmu+1yZYJesz1ljM7DH8FD06+dUMAqxkX45I3uW1uJ3YADHq4M+dxUfJ94CI
3BbtMXQH+IX9aEe6Yc8Igu92i2ZeiRP1gbFeZ6XroAV5WU7UKvlK4MEJKwGWdPoLVBxrpuF8POVL
EbgIwWKhSLW9FR7quiIrNXg7tKZNS8EUNsNWPMdfUUHPFAKC8f9MbVDRiQBIadRYPLVkYfUvlpCn
f+WSIzuBn0akM/UBa8OBynMuGJi56pi+fVU+NlmnAJMHvnpLyP+4aHPPTqCYEkoNWusJl8gV+D99
JcbyBkHhGUjJEUfR10WfkxeOE9pCFhHM+U4xLve6c0WIlByE8skHjcDWiBQnJfLv1zNCzIcAqdXi
5S5DdEszwmX2IkLOqZ8wGF2Vg0QCwokxx48r3RjpthOhW0L8IkOGRR37eS6i/O6zh6hHG2xSVR98
URok5kKtNGs7RrcS6dZQlskJ+XtmTU5z0uLRqPrjMcV6B35paheGZLTVgJ6XrcfGfETphdKdcTiq
24N99rBYtFuG7VJGyPm8yk6t3yDS3JL+31PMNUdF4pOGVKTIFjMZR9HveJ4YTWFFmB/pKKBeUUXC
qeGI7luYaHswziDwicqzxnkxe7XKNZ9mijKfbmvuNw3fc31XH//Vhu4CRQTrnc0PH5DgIskElH5g
UHFD9OK8YZip03CS+M3xNr1pRAOzCFtOzUNMEMJCvUN6aMlqhkiojoHyfAqDKj7k341H2CHrEvua
seUNfVcJ9gN52iLj09g9JmWN3RoKoCJZ3FtZ1ZxfEHzr/0tATZtZjgYbXjT1CmshgwNLtFpvKLCx
ZB0+GttiWkkicpb5rUOxfgSqy74E0p0mtIlaQGGb5Gn2ERSogVW+DGw0qIPolvnHqs2O87NXLycK
Qc560KRg88DWMfva53Ow/8HIQTTUnR+dzJWXprCfF2QgVA8uIGxcSd2mVKf73Vo5vmQea8WoPNh4
iDCN6JSHB3ui8EtmahugvFn1Qce51y2bcoNF9FICvfXYUZ+yiQkxbqMHp5Gzx0R9O64CgkWGd3lY
wyVOQHyyhN/OKiFYhrQqxBNy0DHFizzeS0kIA8ueUkB88j7NsdseWLoX9HTfsMQKwaxg/pogbloK
1HEdO/nqHQmJiF8y2Slax9AZrVyxpKk7Ge2syxS6D6mu8a7Vn94BcogP36trxzbVG1PD3nm0VBcN
9fVwEKw7sdLK4hoYMbDSPZL3llprhekty5AOFFiswm+4iCgQr6p1/d26uVaH2/nvk1RwoXmTDv76
6zO1ar3OlNBRJN9+Dh1Zs3MltdwAjMwVvv2hUoGhI3+prkESlWBHuBP6QxIb2aYPnFhY6Fe4Ka9k
gXRtvltKJ3BZqcsJLjkDzviaU7q3tRaMySs3yamCJsUS5hDONNyBKKIbpeAfnqPx6/sMYZRkd6+c
p3kgO3pXTVqLe7Xx9byfKXPD89iMZ6eD2KXylItwH+9NjUpO2vYqBj/62FHN7c4StFFslVgz2eLT
J26jQRY2akymKWNO16dgOTJzw3brOhHy6xxnuBnL4UTXMxmePAxFWxLn7zClTyzYQCjE85abarIt
bR6txTZdfpO8dwmNeLDOWtOlQ8RQekJoHisRbXXJepTRLBFdEFQ3d8gxq1FPw9a1DcttDMwM6kik
6rRqjW0u/LBT0QuMr/Pc/3kytrWdfs+fTibINdL9kwDvT0T+9NrP2WVeshoOnh2ZgTSgkSrJrDpS
OCSWBXVhIxhrOHSwSedrPOpkXmH6T3WAQxXkFGwSeTR/2h/9zkQ4mGEmexCr6vBe9LOcqcQJr5pg
SuslMR8lDOBzTOaNlyDWOkmJ8JYxbYe4m/AbCPPo/NKkKwQ7+CSX3iAcNulEY4oXUz/9mxhOibWK
LEjH9jDcUYOVGwz9xRtD9xdw2d6kK0B4JPnYYh0Bc3SGGZT/uWUO85S2oDVfqn3IKO277RO2GdcR
vldLGjzPXPuOC57l630CorLMHEis4YDLOWWA8fULqrdsdvxM4qzOEGuMbUXBRC+AFAUmNUfjP/zZ
oN0Eyo9Ze/YlkkvNfJm51NS9zTyd6MoKZxLNN173QUxgT/9VlnUrlSVA8+TSHNfgHByj5bvu1v6M
aq7GgxiHc0xXoHC7PzLDJEA/9igWKEaMxzjlv+cV5kdkYIfZDw/rYViiBMm3e6IcLcSkfZikTm5O
9fmfz9UJnY6Q5jD3gl+kCLZ7OmqZlF+ThXQsEPmRW1EVkHFxHbtYH6BS6ZHNeYAT32SPcp6Tpuiy
+HKfX4mSmPElYzubo7rXMF1Bcsp5rXcP5jIHTuJpavBZtYsJ8ylr6p83WhVr/I7PY7zXKJeFYsGB
2nYohzLHy1Mxb/s7Zaswn7r3aF/ar9xp0Iyc/f7cLUh17B+mQgqTAb5cI53CtJ4Kit93fijOTRDQ
2ZucW37Mo4LThvlJtT/4L4l5kjSwVro+mmmh30JMgmjOLEKn4LrGyu0hNfJWlJIGyyMd2bZkLPpI
alHcOjRHQOHGka/LiCL5kZ6yAC37RvGvMDEhDFTpiHZyWsJJtsNCxygGdo+oSPDtHAHuB20P0byR
Gdqe2NArBZdo2QRkupPuyD5hUgplJ6Ei37yiYCv/Bsm/YfTz/hSCuGY5NXGBMviyohVMndWy0yi1
eOnWFvSgk54a/V/G24Q+Q40u24uftZ58II0dQHOvXxaaw4NtqZMB8bXF2vbcuKpOIO/gjd+UzyoJ
iQ0DC/BtAXrCVm78eStxdMUjAxxENJtNAJ5I8JwlUo6/4VamE+XaEoqjs8CAiWsDvjEWtZ3/UCS8
TzbPlO81ENRiQkPt0XZnoAvgdYggP9D2pQcCwKmDOPRre2ZtOAoC0ckt2grVqNrkNYV/KRra70uA
XaIh7SfFLx4oSg6+NPiMkuOG1G+83JTfEjYPWX6+GGoOB74RNvaAA6U3LfKkRcyCyvme8uCZiyOZ
OV9MbJO1EOCh5V8mI6Drj3/vEZpLTkHGxwez2zySAA03lGPLm5ujouuT1B2UAZLzvE/pY7r7+ivo
MsisVt6p28N5pOEkaUvzXGWVlpbm+nGfbGw2ZAbtpFDIWB1qjTWZZNs60z0imQT2dnESMJ/6+05B
g9mh5Gouz39Is6QqLK+fUNcKtCyj0VWV8ZYO1v2ut1xcKWa38JmjjwpJKdO/Ut9YBOEhylwme+Bx
E3oHtsi1ub9XVidQLKBNSIKc/vLAAwWuu1XI2NIWWWuFcoDDbZY5oJWYU8QIY5S4OUQQM/fRAOaB
D6jv5+mRmWOQMB8dH95ZRj2uPZ2a0rkEIVzYm4RgTwO1gjSvbywV+4Ivtb+qILCAWHgZ1TjHfHx3
nuG8/K9xSlv0lXh5tb31mmQ4gmUSxs8QxeD1dRa78+0TNKqQZ74yy0Wr04LjRjl2fKZzZbbXsgwp
Xy6wXPUIcqZ/LL2ZhsQA3koM9AtwYtIRZ6EFXnqdZmK8NJXRzUEoVF29oqBKoJ38A4hC5gYF0qvj
4q/X2/TNpECQbVCGftkXN+hMTRSTY24SeT2PrZ57pXB+yfjsL1hWpm1rk0YaE9MTVuTO1zJ9WhJD
O8tmYiEzjD6toV7vXZUnvK6lISJWndFmFuPbGBb4QIprPk6S9o9G7idHkanryy0QMbVsHotyh9qh
23sEGtYfV/W7tnly3GMTlV3g8tGgci5hMH9ggGPlW91LZlS/GbNfks5AZkF5zfWs41kgc2nSjlWY
FReJItTSfZFLzrlYqnFjfq5nTPVlTpZ+uqFant6bYURBR9mGTcZGMuaWo1kPCY19j06JZztEMIv4
VtgtsZkPex57J6nDW9yaQNqb1OXrskswROmvr8uBHqOsrwA9LDelpChCebqP6VOpkrqiTqoKoCLl
fVz3eTsDtXM89MV3D8tFma9Sl6uNdy8B19APFZUM/kGRDALQeaT4xfKH8+CESuEulyw/VY8dTMpx
/cb6MMYj2dzMD5IDuwNP+3QMubv87EyfYU2i/kbsQOFEYO4wK47PCQULlnt7/WTnqLwjxBShPFML
aKNbbkvCHoyikveYkMjatDfgxM+NBm0xqdIp5wKfNfC3wAi+5PfbH1kwbUmz50TFA9zdNS15FXvF
TARxUsST6/K9fUCeBDwRn1Q3oJcVVED+uurMtS4JZAQNs+BikNqyLxsHUFpYuyohX8r+2W5YS11J
SXaBHp2Ogog1IejdLRBghL/WWN/RZUF/kUZZKh7FxOf8luUbC52Ecchs9PGzNKpWwYSACJXx5d3X
dZg/ntXiyeSDWYK/uiQWOR+XZyO47Xx7a4CmN5WYo4akTuJ5XXZIq0plKGuDLBytB4H70+ft3K/y
VsQQTGpXuXMOfsaXKr1iOBgdsUKrnJoBQcQvB2Bx8sJ2et8Z6bWc11JHCgdfEy3gdBVBdlM32qCK
/T2Gu6OCRaRQMcEae/ZyuJzN/LvrRfTxi/XcoH4UCLBjstcB+/F7U3OTCxipDjAUI5j3ePsDAOk3
8eUewZBJwBhil+lOSmfVfunI40agUrEW7uP3n2P6V0UQ/FIUwrifvQVMNXLuiKHI5Fqvqx4t0AnS
73oOA2Ixk+D5g6T12YXrn6O3npWiyxBnxIu0j/BchEWXjskWG059SyN/qelZXgzNoP9ZyUHLeKXH
FAoCONfmboZ3lhnUI/zcgWY/D+M2QyTLpC9usaYMwqXC9OqMLIw5FDZxxwe50VbBE7S24EwrIY2v
UXBnL1EBNoUij5p6u45WsUFbEdW6tzyr8XNuor65u+h2XYjpn2NU+VlBs+hY8/qdHTPCgcuJRsG7
5i9EXEhs6z6HNWjDHtngR4u3ERMMuvMX8UvT3nCSZpVAHiJuGMeMU0mfKRcRM8u/3Ge4tAy5RRdq
gEvhfnz02quAbxwZVIurOQ12h8FOuYUbsZnhthxA75pkb25eaForu6ATJ7teQemVmaew9ZIkzcro
AmdThB6EtT/WRRtyFdKwC3Bf98F0Q8ZcSmFJLZ4xCMxfqf2vCiYcFDrgoYlETrBziLXI6Bx5/s6c
f/zXuqbXFAIlSmA2+1jA3f4bPEcZr6bduXYLumGP7u1VtBIkSq7Eg9LJfLCNXoHAscSZ323PlEs/
9tiBJ8rsAuXwwU5pQcgaEUUqXyjqmNsfNT9vM014UQ/AA+Ub17eQxXf8AMDloijcR2bW2PTFHRXV
20qXgrH7RuyuFjdkzR/tZiAxwrMgQRxtKKDa9bPXaZvOKgBBY4VeJjAZj8IPBeuHGFxItfd8KPxh
h9ARRW6MgajFjiD55AWjgILD4myq7oR7zLFvrVQ3ARuKK4wFkb0FzyfCiWwJSz0qxiJzeMM7wVPz
JTEMlZP8QWFw0gcAPqhxbwEUpGXyk2diw4EOwhoegbT7o/lLGixklnpF/mewiPcWLyu8K/EEYweJ
Hq7nbyik58EtXgQxEFHIvn6cR2NvrQk4ehz8fCaU74DPGxKm2io+/ECGPvjBGtjNZMebVTRVQBv3
6W5at7QB6GUQFXJl4whWZuSJMM+G8F2j+ke4nWcCE7eKECl0/W9eG1xFNZBisWeSQEZRL1RZcEgT
CUmS1oeMkkYcHAjO8ZiD7TOfwu/bgj/n7sQ3xNk/WEtnwXmrZ8QU6mkg+jVZjxTJN7nUIglZTPOj
7fOaK4R6ViZgOoGMIQK3BTTOTFpsr/Bg6WZ46uD7k+aH+5FSgn8VpSVZ3Z5eIkxE6mIV21zsKGs6
KF5wdid+MNqVHyGpZRtGFU/mXLVTMRMiLxfhVF+p3j9meF1tzkMtjzMG0YDE2I/WgPDbPKpsAeE9
3QEVky1JMjOTNF03L0/R6/U7NjQYawBokWY9xQRTP5pOoQ8DmYd+fLBEPe9lT19w78sVW1sEycU1
+KLuCQ1fodL+f2W+wc9O7513ixg3lWljh4CbzIoPWSwTFYkPJ7rfd9kAJFG80IFHW8C83iTaabbE
T42DLBWTdjrGToQUe2iwHsq1tZLxqQcpbhXy58to4V7pAJ71NBAbgbXTnahnUSv9klMmDpYGPRc7
joioHL3rbseWJFQPWRC5mjJYrG7lC2Cv2dhtWxoJ1QfY0zU66Y5yYpoPCb7z48j9HpmiAS4Rgz4y
kOEPKkcmPMb+bsq44J74CXhNrafISpXnbtv8yLENDWiPEC0uVzw5OieRO15+7MHKbmAorpblFP4G
nPiRcZNdGd4Tt2T6xIbah8nkOtsuvvJFuyw1joPtSsfXkiKT7I2RsUJISbiq37rIK6I6T+JDlF7l
vCQFTxjGk/vMBfsrEV64ol88Ix1GX/d8YZp5tildZWHbI20mo1DWX+XxZx2Xf8lzuxZzvZ1Yj8qx
nMrNqPMIeQ1GqdajJyNNCojtRIbAB3+ffgMzO0c7vMEmhl2A/0laUZZIZNm03giTf8cqNOjOZ+Ad
9W8YCqiqbjDo2UXykSjxdnPFnA/if/8ZpJQjZ5iUjZrlNr1irWd5hTXOZ3G46IMzLMS2U2iaK+qb
PvfRnrX7pOdRQ5x3Amjgc2IwosxhEH0rnw2X9+IFKLWz5XPgeRxnVkzNxnToWbWJmlVqs0mdX6eB
rqsl8P1Af0foRE2AaxC9Wv+5x3w3QbvJs3KjdQQ1bzpLmPRLo+Ke7P4oqehp4b6mIPP8QsKrlnsN
UIBOpaGumkC8TBlbGTU/BXXqqg2i1OW/qVXEo5Asq7XWGT7zhV8RcH9AXeVez/vSxL201NryLcT3
fcIKNmemg/d9J9wg3+kT2jcTqa0dUKuhN5MfX+qFymC+CBIIVzVJwpJc9O35zWsyApRUzAJ0jmMU
5FF3hlVFG4yZBofd5DRMA1qm2HJds72eDS5YFwIGCFe6y6AmE8bofGscI1ubvwTqNFWQvFBtEvtd
372J8/J0dzUcmLe1/jVF4Czu1a7vPJvVYtAC9neuqIB4s+OMSzOxniDEm/SAoFJqdtpVcPm2SM90
8bpSWBhDV2hfAd18Hm9IYP2KZohX7c+7seebuQoQ/5iat7v/MiT52Xdnnp2EmXTrLUmFNGJpeVw9
vjStYlDRhGBpjjFg43DKyb/Z4+q+PAfHE1Nws2peqOELfZWPCo5d2l7hYXdsQHgZ6F/NmkkqwiNx
ImGu0TuinTc5kUQxSkJFje6hPWjlVukcIsbKluk3M3fNRnaFOYHNjp+iVc4gigPNZl2RCa/yah7K
4v+3BO7Rkg1SSS/7ayJy6vpafNnhcsOwYcm6OPZvqOHuz353vWUeYYhMzCiaJaa+OAFGz1g8IMGf
Zc5L4TApmistn761HKYAj3K+wU1xD/Hrll1XWhzco+UD1W4MklWrQo4ugd89l51a3Brc2bawKASG
ZxdXoPKqamTJTF8ht3vzJdCeIzaHdUk+XWqLquryr7WofUymJ4QYqYl2noS5BPIkoJ8Y4R1ykgKU
N5zGHSCRS8fXJEHpX+MMVZKYUMIkFF2JgY1eBP3Q6Lm+ilslhdH1wjZrljpFiM0VxQ4QhA0gu8N+
YCLTVvx7Asu48aXKjWE01VMKO4LYbO2qONOtV1Ax5Ck4qHf8EErg4+y5fiN+pUMPQ0GqFLOnsIXj
TMpLwA5Hq89flx7yWcEP1DBMiOEOKGGjFP7wITSEbpyEZNQO2/YnCIhqPzUxwGG7LDzuHo/82a1Y
lE+EQmuXvdvhHbZW/p9eIyyklSFt7qHz4fBa78PviTPwwOAxalOANFDVT2GyGpmPGJffOjiredME
R3Hfpf0pLnZyrdMm7R3Gb/BnhHkA0JI930LwnFhBKtIGldhxjiVciMx/gqAj9ttmYjk9Goi4P8kH
b7U3iryLXVjpuYl3aC1/1mbXUZ9HPiRgIQscgxMaZKBxOtle/PxYuV3zp1ZlOvb4zNvzncdIgjNf
u8JxV177bircrudnMFK6YGhe7M9D81SUlGPH0OiPgQSC4axnxVGs58OgYO/qZyeuyjDh9BfA2Bsx
c26SGOE6Rh4FZWU5c5L6K2MzbY0x/UCwAf0y4Cjbz3O/CX2WrxBtrUcubqBckRM+5fkeLK1MRduD
4QNaYhSVgEMfl1nDYyh4piccXGHp3V6XbsgZk4u2zNPp1sQvGfoFlnCxrmSfqy54L8RIYY8aXnll
asdH7Go/kGvO6a/lr1B2jA1OkACEONnvj44Dyc/sRxidPff04fBxMuYcVdLf+dY5QfJa/3oPlpz+
rVAqaWiN/yHckMQqO/T18HBj1rUY9VvAnSyiD7pkgfdpWH9R1xyOP+GtTH78ON3hPBOxuva53rt5
EYROTdSODFRi/Blsq1rkF0zjQtmKYD7HywfYwtSqSTGiNUurhvg0h32RoHWnshdF+Q3KAtHWFUG0
qwh+V75Hg9hLdUCaW/Ge8ZyKXTiZmifbX6A1Hz4y7Vr2y6xkjeSmiVIkGwuerY7/7/5M1QI32+HB
Cl2HgEZEoM+ZHsDwx/FcO8ALczpbDIEMYj/IB60qtfUYcsViyLW7ylXYxcfKVckY7dEIKLJWWOb4
pj2robJlLL8v3cgMvmtVX0DS1WMisAzvPUHU+B2jSVLygxtLcdxY99P0e+jrvsoaVTaRw81xQgE4
oZxMdpdpwn0wGrEKRLmXcM8vJ+II/jt9tVmq+5HZ8fm6qBW3GpRdnjxmCPzusL59KcjZNOHM20QT
BVVu4iAhVdo5lJi32vTFD8KgZwmWTHt01iLr75WPQEvcYloprFKakH/u2pskoF+DWT9JVFPTi6W0
Fno5ymn8wyVnMxCVkkhdGISJC2aInH6RAysWe+Z5/SfEejzaQUamW57HbN2Npz18x1lo21jpWhoI
gqfQULBTrfOi7JVtzDcP8U8s3opPvm2tO7UINUN7b+QAAAAAb7NjnyR+ihcAAbo3gKQCAF2hG2qx
xGf7AgAAAAAEWVo="|base64 -d > $TMP/patches.tar.xz

tar xvf $TMP/patches.tar.xz &>/dev/null

  patch -p1 -i ./patches/CVE-2016-2399.patch
  patch -p1 -i ./patches/libquicktime-1.2.4-ffmpeg2.patch
  patch -p1 -i ./patches/libquicktime-1.2.4-ffmpeg29.patch
  patch -p1 -i ./patches/libquicktime-1.2.4-ffmpeg4.patch
  
  for FILE in lqt_ffmpeg.c video.c audio.c ; do
	  sed -i -e "s:CODEC_ID_:AV_&:g" "plugins/ffmpeg/${FILE}"
  done

CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
LDFLAGS="-L/usr/lib${LIBDIRSUFFIX}" \
./configure \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --enable-gpl \
  --with-ffmpeg \
  --with-x264 \
  --without-doxygen \
  --build=$ARCH-slackware-linux

echo 
echo "$VERDE"Compilando ..."$CIERRE"
sleep 1

make || exit 1
make install-strip DESTDIR=$PKG

# Don't ship .la/.a files:
rm -f $PKG/{,usr/}lib${LIBDIRSUFFIX}/*.la
rm -f $PKG/{,usr/}lib${LIBDIRSUFFIX}/*.a
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Comprobamos version instalada del paquete
f_versionInstalada
#Compronar dependencias
F_dependencias
#Si no existe el fichero se descargara
f_download
#Descomprimir sources
f_descomprimir
#Cd a ruta
f_cd
#Descomprimir fichero descargado y compilamos
F_compilar
#Creamos xzm , instalamos y salimos
f_tareasFinales