#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20181122

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=flashplayer-plugin
	EXTENSION=tar.gz
	SRCNAM=flash_player_npapi_linux
	GESTOR=wget
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=http://get.adobe.com/es/flashplayer/about/
	VERSION=$(curl -s $WEB|grep Linux -A3|grep '<td>'[0-9]|cut -d '>' -f2|cut -d '<' -f-1)
	SOURCES=$SRCNAM.$ARCH.$EXTENSION
	DOWNLOAD=http://fpdownload.adobe.com/get/flashplayer/pdc/$VERSION/$SOURCES
}

# Creamos paquete
F_compilar(){
mv usr $PKG
mkdir -p $PKG/usr/lib${LIBDIRSUFFIX}/mozilla/plugins
mv libflashplayer.so $PKG/usr/lib${LIBDIRSUFFIX}/mozilla/plugins
cd $PKG
chown -R root:root $PKG
chmod -R g-w $PKG
find $PKG -type f -name "*.so" -exec chmod 0755 {} \;

# Creamos config
mkdir -p $PKG/etc/adobe
echo "#Hardware video decoding
#EnableLinuxHWVideoDecode=1" > $PKG/etc/adobe/mms.cfg

# Hacemos visible la entrada de menu
sed 's/NotShowIn=KDE;//g' -i $PKG/usr/share/applications/flash-player-properties.desktop

# Limpiamos paquete
rm -rf $PKG/usr/lib
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Comprobamos version instalada del script
f_versionInstalada
#Si no existe el fichero se descargara
f_download
# Descomprimimos el fichero descargado
f_descomprimir
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales