#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20171002

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	WEB=http://www.abisource.com/downloads/abiword/
	#VERSION=$(curl -s $WEB | grep . | tail -7 | cut -d " " -f5 | cut -d '"' -f 2 | head -1 | sed "s/.$//g")
	VERSION=3.0.2
	PRGNAM=abiword
	echo -ne "\033]2;${PRGNAM}_updater\007"
	EXTENSION=tar.gz
	SOURCES=$PRGNAM-$VERSION.$EXTENSION
	CD=$PRGNAM-$VERSION
	DOWNLOAD=$WEB/$VERSION/source/$SOURCES
}

# Comprobar dependencias
F_dependencias(){
DEPENDENCIAS="goffice gnome-vfs wv"
f_dependencias
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){

CPPFLAGS="-I$TMP/$PRGNAM-$VERSION" \
CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS -std=c++11" \
./configure \
  --prefix=/usr \
  --sysconfdir=/etc \
  --localstatedir=/var \
  --mandir=/usr/man \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --docdir=/usr/doc/$PRGNAM-$VERSION \
  --disable-static \
  --enable-shared \
  --enable-clipart \
  --enable-templates \
  --enable-plugins \
  --build=$ARCH-slackware-linux

make
make install DESTDIR=$PKG || exit 1
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del script
f_versionInstalada
# Comprobar dependencias
F_dependencias
#Si no existe el fichero se descargara
f_download
#Preparamos entorno
f_preparar
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales