#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20250123

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=wifijammer
	GESTOR=git
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=https://github.com/Theelx/$PRGNAM
	VERSION="0.1_$(lynx -dump -width=256 $WEB/commits|grep commit/|head -1|cut -d/ -f7|cut -c 1-7)"
	SOURCES=$PRGNAM
	CD=$PRGNAM
	DOWNLOAD=$WEB
}

# Comprobar dependencias
F_dependencias(){
DEPENDENCIAS="python3-scapy"
f_dependencias
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo 
echo "$VERDE"Configurando ..."$CIERRE"
sleep 1

sed -e '1s|#![ ]*/[a-zA-Z0-9./_ ]*python.*|#!/usr/bin/env python3|' \
      -i $(find . -name '*.py')

echo 
echo "$VERDE"Compilando ..."$CIERRE"
sleep 1
python3 setup.py build --executable='/usr/bin/env python3'
python3 setup.py install --root=$PKG --prefix='/usr' --optimize=1 --skip-build
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Comprobamos version instalada del paquete
f_versionInstalada
#Compronar dependencias
F_dependencias
#Si no existe el fichero se descargara
f_download
#Cd a ruta
f_cd
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales