#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20170105

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=edb-debugger
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=https://github.com/eteran/edb-debugger/releases
	VERSION="$(curl -s $WEB|grep /$PRGNAM-[0-9]|head -1|cut -d / -f6)"
	EXTENSION=tgz
	SOURCES=$PRGNAM-$VERSION.$EXTENSION
	DOWNLOAD=$WEB/download/$VERSION/$SOURCES
}

# Comprobar dependencias
F_dependencias(){
DEPENDENCIAS="capstone" 
f_dependencias
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo 
echo "$VERDE"Configurando ..."$CIERRE"
sleep 1

cmake -DCMAKE_INSTALL_PREFIX="$PKG/usr/"

echo 
echo "$VERDE"Compilando ..."$CIERRE"
sleep 1

make || exit 1
make install || exit 1

mkdir -p $PKG/usr/include/edb
cp -a include/. $PKG/usr/include/edb

install -Dm644 src/images/edb48-logo.png "$pkgdir/usr/share/pixmaps/edb.png"
install -Dm644 src/images/edb48-logo.png "$pkgdir/usr/share/icons/hicolor/48x48/apps/edb.png"
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Comprobamos version instalada del paquete
f_versionInstalada
#Compronar dependencias
F_dependencias
#Si no existe el fichero se descargara
f_download
#Preparamos entorno
f_preparar
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales