#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20230830

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=tor-browser
	SRCNAM=tor-browser-linux
	EXTENSION=tar.xz
	GESTOR=wget
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=https://dist.torproject.org/torbrowser
	VERSION=$(curl -s $WEB/|sed -e 's/\(<[^<][^<]*>\)//g'|grep "\."|grep -|awk '{print $1}'|sort -g|tail -1|cut -d "/" -f1)
	SOURCES=$SRCNAM-x86_64-$VERSION.$EXTENSION
	DOWNLOAD=$WEB/$VERSION/$SOURCES
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
mkdir -p  $PKG/{opt/Tor,usr/share/applications/}
mv $TMP/$PRGNAM/Browser/* $PKG/opt/Tor/
#Permitimos usuarios root para ejecutar Tor
find $PKG/opt/Tor -type f -name start-tor-browser -exec sed -i -e 's/`" -eq 0/`" -eq 1/g' {} \;
#Cambiamos de propietario
chown -R root:root $PKG/*
# Hacemos nuestro desktop
echo "[Desktop Entry]
Exec=/opt/Tor/start-tor-browser
Path=/opt/Tor/
Icon=/opt/Tor/browser/chrome/icons/default/default128.png
Type=Application
Categories=Network;
Name=Tor-Browser
GenericName=Anonymous Web Browser
MimeType=text/html;text/xml;application/xhtml+xml;application/vnd.mozilla.xul+xml;text/mml;x-scheme-handler/http;x-scheme-handler/https;
X-KDE-StartupNotify=false" > $PKG/usr/share/applications/$PRGNAM.desktop
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del script
f_versionInstalada
#Si no existe el fichero se descargara
f_download
#Descomprimir sources
f_descomprimir
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales