#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20161229

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=opera
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=http://download3.operacdn.com/pub/opera/desktop
	VERSION=$(curl -s $WEB/|grep [0-9]/|cut -d '"' -f2|tail -1|sed 's/.$//g')
	EXTENSION=deb
	BITS="amd64"
	SOURCES=$PRGNAM-stable_${VERSION}_${BITS}.$EXTENSION
	DOWNLOAD=$WEB/$VERSION/linux/$SOURCES
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo 
echo "$VERDE"Configurando ..."$CIERRE"
sleep 1

mkdir -p $PRGNAM-${VERSION}
ar p $TMP/$SOURCES data.tar.xz | xz -dv | tar -xf- \
   --transform="s,/lib/.*-linux-gnu,/lib$LIBDIRSUFFIX," \
   --exclude="./usr/share/lintian" --exclude="./usr/share/menu" -C $PRGNAM-${VERSION}
cd $PRGNAM-${VERSION}

mv usr $PKG

chown root:root $PKG/usr/lib$LIBDIRSUFFIX/$PRGNAM/opera_sandbox
chmod 4755 "$PKG/usr/lib$LIBDIRSUFFIX/$PRGNAM/opera_sandbox"

}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Comprobamos version instalada del paquete
f_versionInstalada
#Si no existe el fichero se descargara
f_download
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales