#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20200203

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=rtl8188eu
	GESTOR=git
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=https://github.com/lwfinger/rtl8188eu
	VERSION="1.0_$(curl -s $WEB|grep commit/|head -1|cut -d / -f5|cut -c 1-7)"
	SOURCES=$PRGNAM
	CD=$PRGNAM
	DOWNLOAD=$WEB
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo 
echo "$VERDE"Compilando ..."$CIERRE"
sleep 1
make
install -D -m 0644 rtl8188eufw.bin $PKG/lib/firmware/rtlwifi/rtl8188eufw.bin
install -D -m 0644 rtl8188eufw.bin $PKG/lib/firmware/rtl8188eufw.bin
install -D -m 0644 8188eu.ko $PKG/lib/modules/$(uname -r)/kernel/drivers/net/wireless/8188eu.ko
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Comprobamos version instalada del paquete
f_versionInstalada
#Si no existe el fichero se descargara
f_download
#Cd a ruta
f_cd
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales