#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20181022

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=rtl8192eu
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=https://github.com/Mange/rtl8192eu-linux-driver
	VERSION="4.4.1_$(curl -s $WEB|grep commit/|head -1|cut -d / -f5|cut -c 1-7)"
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo 
echo "$VERDE"Clonando git ..."$CIERRE"
sleep 1

git clone $WEB

echo 
echo "$VERDE"Compilando ..."$CIERRE"
sleep 1

cd $TMP/rtl8192eu-linux-driver
make || exit 1

mkdir -p $PKG/lib/modules/$(uname -r)/kernel/drivers/net/wireless/
cp -rf 8192eu.ko $PKG/lib/modules/$(uname -r)/kernel/drivers/net/wireless/

echo 
echo "$VERDE"Instalando en sistema ..."$CIERRE"
sleep 1
make install|| exit 1
depmod -a
modprobe -r 8192eu
modprobe 8192eu
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Comprobamos version instalada del paquete
f_versionInstalada
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales