#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20201029

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=pocl
	EXTENSION=tar.gz
	GESTOR=wget
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=https://github.com/pocl/pocl
	VERSION=$(curl -s $WEB/releases|grep $EXTENSION|head -1|cut -d/ -f5|cut -dt -f-1|sed 's/v//g'|sed 's/.$//g')
	SOURCES=v$VERSION.$EXTENSION
	CD=$PRGNAM-$VERSION
	DOWNLOAD=$WEB/archive/$SOURCES
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo "
/Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj4GP/GqldADZh1NoxsS/myVo6VNIgmOGZ4EelrK0k6sOB
+X4taTJL7cE076Mt9F5w86cURbZc9Ol4a56iUJtkzR8daoWHaQ6cmv1UdSXdhldhoTubrSsXiWXd
mHezyvLuN4OJDINEmn1rqxt/nNIae1ZZlkO97zmFrv3RYlteI+PhYnHWr9S9eKjCF4hhgdSjYnMa
+YHoBio7HC1NHhwjUcJUMplMiyJ2jUGw3CMbnhkSXFMQSp85Yb5RJjve0E2tIMdQ5Se9jAP5XyqV
WmSeOeOmmT1Mw5cnyeDCNxQRuVUc8bC40oAKC8tZOOd/WDNPjD4e2wiTlR66O3jNSk/+MPmUgBzD
fPnaFxzwQcB6PfR1ctm8FNkiXd5fSDIXJFg1Ef2PeENVHKuWR5PkjVj4c+VF7WPNo5r7afr1B4FH
bUeqRfSHKhm0CAbcJ+Yq3iHy0RZgqVRzekVndA0usiGoTon+kGj+4ElgK83SjmZyqfMP+192AO9B
XlTXyg5Hg6ze2Tncst77+oxzbTD/Pz5E3Q5D+vh4fHXP+lE/zSlWZttlUnhUvugAaJXHC5GKO7FY
/BAejoi2p/q/a3nQ8cWopWrxExkICA0Te6tOg2BWekve55zzBBb+5dCHhQr3pRJRJjvNurpqznRt
XMfMa9CLQiOrQFpai6i2HXxyQpQA3FgeH7pv6Q959Vv46nyo71ppN8O9ut2yo+6RwLtljqwBH20G
dbXKDcgZ/mk8HZ3tAGvVa+f2/SeWGL2QrUA1UcXD1R+TwtI2kyYEBJf92phqAokuzeRSHp5IPg2h
Tv3nn3aXINgTX7kZra8m/VcbPa226ZOIF6PiLX+RXtCizThNRxhum1sD7j55cSCt262jvbwNr2pl
B2agbQdBQpuJC62FkYVcfkoeVW5q7KOGsFc9gfXElMgUZzbPoq0VfsWW3qBi9mYCn6oEdF72MPT3
rqkt1G1phx8oCDxQ+XA6auREYteC0tdgvsmJGvd3L2n/OCQ6FJqsbpIIt/JQWJyUIcRA82xbmU/y
hME9p9ou+4PCWhwDTeg5Dz/vnGnRBT0weCd0NBn3Ih3d82IA2F2CVZ8fS6F9h35wSWQYKUhivWTx
kkumS/W0oyWsCdpmyHS54+YDiYR5bkABzeF5a8YoAq8qMN6jmu08aK8UPFuespzPK+swkt578cEW
K1hbtLrPfPJh7MFubQpy5/j/flHgVzlla/iHcDeWRZ3Ai44ERvPA4QgF1gxpG7qBDl/dHuRqwqlO
ndAye5AghJckLN8RwVby0Q3ezg33tMJnZ3DM8zV2bMQJYvS0HX4u1ZTsRYlErGJawjv5NIwRBfSR
zjgwMbjVSo3et9V9fBm+z7iuAw/f980VHRmAjM+g8W8kT2tLVKw7RuDO2YsDCDsdqJOda6P1HY0k
LTFCUD4B3ueOuDC+L4OLpFIQR4pkd4e/T84lrEzYuW++CSmciipSYx6ZbOir6nmisjTh04duPHS/
XEmLz5NpkIUdR09LQ/D3qBNeHOCUOKeo+6BbVJI6ksmvr3gwTWb3jPy/9HHTVIfB5fefib4F+2mf
gxb2oah5A863jSHkO8DR3mMHpJk0mh7CAYNrSrWSguzLdDfp4q23kNm7yvCVdtJEULjq4nHMjkZI
nshZ5TfvCFoflsQUBaEGxkcrbhAHL64S//aOqmjhGu6PVeSRpH/7D5pNInUEUtP26lPa5mX8UPFl
wx5e+9wfVRTPd/lUlEMTZYGFDSpkD5d6cLzxhcAW+Cj36wLhHQo2LZVtoEK7SB/VkdZq0qmj6DJm
nglIdoIRMtW0yL6+SnzHXySMx1CD8i42P/bgAaUNV5gTxuwf9ka3SRgGOJ+43ZfXXemdm79gXRfv
DfogfBlz/QdbBJ3JD81dTwTluH+voGqc5IOqGMHaBTK+6sbNwEo5xQdcWH/TF5vKxjfAsS8h8P4M
4eb5jgA+kS9i7e4Quzt9U+EQtQSbvqpEgPuHBjsyli3zQ11BNoLxY1miYFM6XHV9Vq3kUGR0JO3F
1UFR6cnKH7ce5pmvrgXN0oTKhoUKY7I42GmZI3+LM2eulVuxrzcnPA+pZA5eXWHsSKsakWK23B1p
XHNizMTM8dzeB0pHW5wmLYlzTJyBvsEyBYQ6j4TEdp/29pajqSsGJvuPS0P64XDhTZOzbYlGgNqU
ayRwyJZOI5KRo3vP5ZH1E4rAzhvKYswgqpmBWxvJ547uz7YhnwFYQGzmQycc5a1SD6CSzXGHOz9Z
NfN4F0X99jrecUVuKp5a2kz9IcGKOiJQSYzKgi1yGCfiplRcss7i3o0/dM/cguRLcMBGFqjrA9vN
nMKKBH+XjAQIs6hNilDjcP/1qk1E2tbpQfCFKjqAUFaYnxEjanOESXWqrath1mEKsl2TwvHq7IXg
BWiodlLBQImHjRMjmjYVbtlx0ActsRvn2s5M9Hgm05KNGT7I4nPZezxXeJu6nnUJEEiWSF4nxkxf
Xof/AuKXuZcXqDjZFoc4+xDM+Af7qlKDdeDrn6Qu+cS7Y33Yp9314ioaKzdoktEUZTfmBmWCig1j
DhHcH/BN/e6nRhbcyZq2d1rzAigBofmsgk+rJX9UhPxWmUm382OpmaaerKOLZitFx9VMQy0MaCEs
4WIG+e3Jf8p04mdF4XabQauXGtUSgsWDAc09/z5xJvvrkqlGq9pdej5zFMDDPCwIRrW7x7xgvuVl
nUQS7Tfdu1kexyaBanx/Tx0nXCAFBKpEFbpFXloULT1JeU8S1sxvtMUL/EUJwPfyrNs30mOeX9Pi
5TgY7eVitSsPW9Rrpe7rffjsZanRfXH5DdNeTxich79OUsFyQbCbBzuTRcfUt46RBdlK87MgNmDK
2vnjKdsUHzf4Vix23RMUU9qrsVg0M27wu3qL/4PG1Z7CXwNGlDUv2Rba9r6cFxPLFY/kGp+0YjEJ
629LyylaABG7n1EBiDyiLW/F8EMRHDk2jlLEDOJHKNUoo+PaA5Jz++0Ro6uHmo+W1XFN0WrLEZfd
tdtMfkqPJU2lwtPk4nhxWHpcLpn+8gUoo5chSJnRNGZCxrjGRCj4b6hE1S/z5YurEHK1oqpARLpo
iSwl7CgwKStndZhbh2xBHtF6o+NXZnC2vAAUTVsqmL0CcwDJ4QfjOv+SmXWxhkgMyx8h1F14MzXX
6Ds7wTFSrHbaEaKLgFoP+P1y6dXNjQI2BG9+4kPhUBhA53dGiVvDx1QU4IYI61+kCtSjSoAnKIVp
roAspPbODgBtr3dGXM0PD1nuFQ/0PJ6I3sXa52d4JC5k+D7E55qVRErEOEQntQEIIJsPgCtEbCcf
vjtOZzK0D8APp8h4VxzrSLhB8ISQJn3geh55nUB3KVhV1IX/Dg7Xm5D/uSezAUm8qNtrySBrQAYM
zjM+QRjOAMsLlX6o+1LjK3TD8rfd2d4UiI2azqqNgPvXelzvZKqyN2CPrhD+MnO2mGcFehBcsYw+
JkzxalUuzeGNz7JMHwiUaf1rdrJB0udiEKODbHj50JFMMJRpKEbEtYBLCwOjm+KVNTqpPa2GvPS2
5ckCDANfOQ2PP55EBOk8Zoc6msAAjbMjOHuaw0WLS5Kl4NUFbGMGr083hK0DPFBX6YXpXHCGYZ+3
k+DNTc87uaQeZbOh+mozgkVbcQWyY+MNkBFAgNmBf+8b6NQKnJnu+gDe8c3d5HWewgxKoNT+0sXT
1cnV/x4HR76i3s8aYVdMSKHcTQyilpdPCm6cNAvbCK2dSGxMch90g01uqIekMNWT1qULVf9KZjyF
NvyHxmyj41YtmDkavzw1MtzzZL8P2uakO/zywT38aSn1thk04aUn6V6DbJvoAPjRB7m6E6Y6adN4
EcNwALU05vHu/yYfwtlvnEBzuQtH/TPJQlk4aMi30+Y6w0NMcNBpqFJYzrJoB+MaU5wil8yOLyiD
gNa/eLXozZ0dNMCW1K+pUdx8J7qJdzVMg9WOif5638C8Z7YZ49W0f/R6W59dj8M3N6nnI6KZTO1p
P0+HhS8qX1u+SbbYzOxGV3zQQv5UWfjCLOeW6NBN3LnEd2ZxkE+QdYNQ78rx+MlMeBWdpP4gPPQO
HEYPr1nRBaeo0rC8zkni02/TdXNeFL4TY4ZeQb5lOynNPLR2GjEjKaDjhwQj94iJQmaYkciP+FmL
tO1l4NgmwJdx3At5UCTGxWtF3qL3HgSYIv7iR6/1SG6IAc1c19hGdcd6SqGL9VmE8/rB2+0CpgAJ
Zoyxb5r/+s+EwCd3UaLTU/atYigLNDWu94EjEq3eqjpeYucPT4h0ploNxGlDpPQKsV9FJUSvMMez
M8DGnCSNzPogEoIM6c7PUFZDcBDa5VKJGFUW2I9TE6oCtL3Rd/EAXZ6ujrDOX6IIx/1y8cyEpWDP
zsYVzQXE2DodAh+GOVnvCbJGUKbdrBYGdS2uktwp/SUIl8Zpqpa+qxXKecM3fH/OtLiT1DLFRJMC
oPj2MQaH1rkxKIYhjPjIT31gzipCOEJv0c9OHliPCrEgU+dOsQAYcanNEIohRz6rQunrx4R238qR
gkocb7BMOIw5nZ9qRVHunycc3qH1U3hPeWgXJqkfBtiQzuzv5eXZ+2As4CmV+O5mZTUJgpI0m+U6
ZAoCuLQyyNBhx1oKYaIV9MW3nkZLZbFV9ZuRDtjT/d/65BA8sSGEkKPNSj1Hmt15u1ujlXb2rOkz
M6z5VAIeI/GXQmMYRERW2sUK6qS5XnunKDi+V3Xfdv3RG9uYPlhwu0eDqrjZbZ/0jCPEndBslKe7
2vYJw2blFyY2qiue7UjB8BgX6dTQZl19zoTLriCqL90cP2YBBfqUWSt40x5jKWcV/UvPHPneGe5j
wK2zcLxg74T7B2OeZ4RbIgt4UHNTSwuTCPTCWh0+hemIy69Ooa0iezrK1rCpE7mx0yFDjikQXsYC
cq60pmg9JglRFQtHMpyanDg2yr5ZheXad/3Ddwtd1ALvGWZFkzo7Jj1quQI+rFAEU/T2L0FoBQnp
cWURrh7pFxiXyfP5za2MoBbM3kaKu7JOAtcnADNPu2cmLuxMjyBM8ysyBd5Wr+3ySRMgn9Kh6o5T
Q6LqVcwSM2ZkO+ArgCWO09CYBaWu+48RiaExCMFmji0HD9BLQZ4IIuXyKeiH0H843QfIHHlR/NiY
gTkeyGB0gRaXYMEVopT+eB1ZT0wkQomJME/MfvwUy3Ko34X7yHP+02+sFbQY48wgCn/NEoqnuDMf
QgFRxorm9i1XgdjwPtwC9hA2oR/bWypVzC6oslRD/EqXN131ExiLqPxWkpupd9beJicEw0oMfDgX
H0RWlawJvENWMUOYZMwaQB8rgaq1iTUAmV+8hp2la9y2zyu6ykLj8IJ7ze2jq2sHG2QbIsbS/3IW
25vIRe3tK2D7JjGgMLqeEwpwu1dF6aqes2y61C92niuqo7wk+FJsgKi1WadXFOnIbEE40MPBUDsA
L952m6gF4cUlnPeyOV3rMSNqpt6N5/wIwEarTbj1kA00AW8lxsNkzqjbMPBf/xpEQFEj/JleNpak
dUBIqOadyRADhQAKe5awuqJudqty/n1Gr8HsnLpMJmv8dHSvTww2bv8wv6Ujf7ekzGhtWZxd2bDw
VZGs6a9yC/WShbX4ZpbDNX/Ap3zXi58Cca37Ajd67/4mYG5teGFeoVmVBWJLDvgyWeJaYh53+nAn
XmAtpWUidFAvEkLfejD0XZ2v0RaEb7YlF0Qi+hOWCRZ7Yi9u3Gn3+w3AvbI32CdgcrL6EFwUhDgy
XXQKbdjfmXwAVI2yy5hKRHjulTtuOk67Zs5612yQJxL6/hjNzMQuGoHQaic6GwSn4/ERYpfVdPA+
1x1jUD35rMSnLDc/QMog9qa0r0h/bsaaupHpDR1KBkXVWFgslMoZOl4XjMzRZIdckulWCCYy2df8
py4scZ3l0+F7msMFpHFDJl5wrvSvzHQ1O0/Wr+HoSoFYnEszVNDwF8sowL9l8bH9seRMavrQS2WK
exRSQqeMgH30tsf0pSDFY5mSood6vS8sQKnN9I5n19Jcch2bjTtbw+HZtgcKmvsP+v5WlZyfkjSb
4GuELdAjEYmiqhpMTZvtKWVeuTHY8XEpMgFQwh0eWUgU2yV+hCacRWmw/iRztvvyGPF4PWExIoH4
oggysmSkBzSbakWPkczflzczJ+6b6afT2zpnenjC/YO9GQr0C91BmV6aGJ0RZFr+sE8DtPlLEp52
9xGp4RQQIOZZMZbrlLFm8MEaYkgPxN8habCzDuyHY7OXa1dTrBdIf/y2fqs1Z/WsKDBxCXVBTD63
W2C/jnQJVSbz1RHOpo845617NHp+k3XaV+uV2A4ftds/A/DCw76xgwRdDdm+XR2g+mf0RxueJtsT
hkx9+mwsRjdMdqrH9ltkYo1+nAxTeUVfU1yhpVF27N+jUf07hUDtIAF5G4SYPpvviOY5zc0FfKML
NIXZ9KR49M7PBHaOfZUQ6HRbQIouDgtkdh/v7cHkF4wuJFrfytTdvdWWW/ZNoy8O+nGucOULhkW5
wwbzO/o01sMlfa8lTJqX8nttSdJj2zYp2xyRTIPgfwtXNPlHXYKUfg4QF6kTfDK+ooBYI4xiIaT/
oVHrizIfnE2LnnUOgD2YfgbdjBNWMV3gwI8s6doMv/GaAb7/opZIqzqnauwjERegysVG8aQn9Wwb
ypq4gbqASw/PJv5iiNaoe0cF7fzPMIuu5dvIdzqlCScFiSiNJF4KZTuK7DEO0biepWndLYIpCgK3
M/yHN99osj3qMO+ULPbkDblTSHLfEsqzb1a0+j/SxcajbQaxeW6/UgdEbT2X+lc/AU1DoAkhAnDq
UN+ZP02cFn6Q02upyTCnR3F3WnPmYz5iz2wr9jCaLLgsZVU8V4Npf23npt90TvCXYBJtHu/ddX/v
ulAYWSROkP7dCg5qUb973iOEoq054aKu6JPvcIoGGVbsdBNPgzInc+v/u4Y/369KXO9GNUqiy97h
rR/HMn1LxXRmAbAyH2/NAUr/Jhn5kpaSvQEWdVEeNnSM6TxzeI/hk11ppTRfD8k7Q6sFXD7wCv4N
w/2oZ8myNaE0XBjJArAuhmXd/nosBCwt+sG9OcVsE2Ytv6+zN9AziESRqYI5kOhchQ0sCdJkgAMI
GeWlNWLaiozFGTLriILMhc4QFuI1GJuHheiUA9szVPhfha2cO7rrQYthRUQo+3Bhxaps71R1mcuq
R4r4h2IIMPZGg9ARTjjAdskfHgTPpsCMdI1Y3wJvjFbZog4dlNwsEK0rD2ppS+Kt/P4MWif7R89q
i8YH6nSV+IEEuavPiiiuN4MKR7AGUdbspe/P5LbEBFq16M0RCrZw7e/o1Zb+g0kOaLMT7YbHTsva
c0a4lN4capKIjwF19Y2QH+OmInOFnRMlBHfNaOT140PZYEQEPtg/LYIR/OVShwphY9/ROk5yNUxG
Qz1r8+BcvH+5kK+/pFPoYDudh64hX9HhRg3fVgz73b4gVpW3o+XcfX9dYd3GKjOszJt6Zz7rexHn
4Uw21QUgxEqfa/5FeadYdXU+BYfrRA12MOAJTyAD6mgJyr4Kh5Q/mPz45IhxBjm6ikHMHOL6696j
erSihFXSQhPcuF/7t1WVxsJgzFUU1mvlKguVgxA+PJydZ8CoUE24qB6iDOHedOb0zbZd7sDR7E5u
oEaSSc+QCRX+gLzKxaw4/KlfOZEFVYYfd4nUJOiWP714smhOMeCC44EsgkK+3vBd1NHDS0vJvz00
6xpCtDhTKpE1iqQzFu+YCdXGNTrIk7CmevSCtVw1G1oHwjvI0ogAMdF8xtL7FRvcABN9ur9lKXxk
599u1DNhDQiu+WNmWWkTXKB0mJ83eV8r8f2L0wsKM3mE08KWVN1o/8O1/aVcszj5HOxXCFRrT/4k
Rc40oz6OdmJIDRFFyhHRmpLiqMasZFSkHkLHDf2fMMqAY2r27V2aOB3YYpGSsEDKg6lGkRSMFAEI
HczZjbXggVLMeQ8jcSG8dCssx0XOWpSQa69EHx+EygI4PCFfvg19NkSrFBp2LpuNrBANH+XXurci
+VPTBQh7DhI9CilbDL6N0330TGdmgpAsQ7LYg0i47N77f4APNkh5oGVbZGk2wnYII2DwVw+6nVAM
uukzqEQxhR8stBQCBfwsZ5qSfyFTLyBxHgsFlRoU330TbaXqpgDMOh/H/RJn8Nki5BW4w2ZDppHW
i0RO4KmRsVGZghy9rAMoqxC9Gvd97eCUnfmb3MPNOi/WGsu21ZbxuzBuOR8SqacWq1S5H3ejBq3K
QwD6pjp61rdqC9NG/u1rwjRrxCgJenS8+mk+HlvlvQt6RuxsNwGU/xc397IIRk5TS1LeEGkcVgp3
nVTGZkk3nHLLkPbVh8sgPmxrF2ZwLvpOd+zL1PvUMq0e7/+WA5dbi2U1gTc25Mdl+7BGLh16V49v
KL2+iKRdI0S4IGPmc00uq82k6hcM0CqBdCxsV30rhPEv6UDC5noFlX6hut15zKQ3fm9Tb7TCGH71
l551RyLxvIA6tznzjNUTF1YXEXzCzQoDXMyKntEctV7FLJdWPHW7X2d3TeMxBo23CUtll2LKtu8n
Io7r0Kj9U/k6c3sahlQGNYezBpsHFO+ELsArxyMyVc1DsYBevMVUS1ALaYZRWa82jsCEpa09JBP+
h8zIun2lc75M07XFLDtGTLKLgIC05lXJWyXpmC1JRXp67mamcD23aUk20gcKbYRyai0yqglX86QD
dHC8LTKM5njT8YverJaQFkyYd/7zuET7vs09P26cEqpaQEET0Z+eqVxKDDgq5ScdBYVAtxjLeZHa
0/dxKraVfIJpruyNZ+NJMHYVaclX5+K7DHx/dSGlO/OOg6JwD2Fke0RqjReMb1ciEjJkhd9a+x6F
P037YdUV1HjqF8Cg+yYPe6vDvTOhuphWBrMEjvJXJecfZ1yKspjDlhaE935VpK5DSNc6nzaFAXno
D5IYjbpzOrOQFx1VLRkbD38ADInCCq5x4WyuHj51IdbxG+pbJhD1P2fnvQm/ma/gwJsSlrtTbXrk
LnDFQqK2moBThB5VIv8O6lDUP9lOGJ9r/0y215IpqTHeF1CjMLcKVYhR7tXHh2J1U2F2Ukxq54+j
Unmt9xteyrT/AKkgZK6JAAAAAABMc2/3/jZUQgABxTWAyAEArixPgLHEZ/sCAAAAAARZWg==
"|base64 -d > $TMP/patch.txz

tar xvf $TMP/patch.txz &>/dev/null

patch -p1 -i ./llvm11.patch|| exit 1

echo 
echo "$VERDE"Configurando ..."$CIERRE"
sleep 1

mkdir -p build
cd build
  cmake \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR=lib${LIBDIRSUFFIX} \
    -DKERNELLIB_HOST_CPU_VARIANTS=distro \
    -DCMAKE_BUILD_TYPE=Release ..
    
echo 
echo "$VERDE"Compilando ..."$CIERRE"
sleep 1

  make || exit 1
  make install DESTDIR=$PKG || exit 1
cd ..
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Comprobamos version instalada del paquete
f_versionInstalada
#Si no existe el fichero se descargara
f_download
#Descomprimir sources
f_descomprimir
#Cd a ruta
f_cd
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales