#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20210724

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=steam
	EXTENSION=tar.gz
	GESTOR=wget
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=https://repo.steampowered.com/steam/archive/precise
	VERSION=$(curl -s $WEB/|grep steam_[0-9]|grep .$EXTENSION|tail -1|cut -d_ -f2|cut -dt -f-1|sed 's/.$//g')
	SOURCES=${PRGNAM}_${VERSION}.$EXTENSION
	CD=${PRGNAM}-launcher
	DOWNLOAD=${WEB}/${SOURCES}
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo 
echo "$VERDE"Compilamos ..."$CIERRE"
sleep 1

# apply roundups for udev rules
sed -r 's|("0666")|"0660", TAG+="uaccess"|g' -i subprojects/steam-devices/60-steam-input.rules
sed -r 's|("misc")|\1, OPTIONS+="static_node=uinput"|g' -i subprojects/steam-devices/60-steam-input.rules
sed -r 's|(, TAG\+="uaccess")|, MODE="0660"\1|g' -i subprojects/steam-devices/60-steam-vr.rules

# separated runtime/native desktop files
sed -r 's|(Name=Steam)|\1 (Runtime)|' -i steam.desktop
sed -r 's|(/usr/bin/steam)|\1-runtime|' -i steam.desktop
  
make DESTDIR="${PKG}" install

echo "#!/bin/sh
exec /usr/lib/steam/steam "$@"" > "${PKG}/usr/bin/steam-runtime"
chmod +x "${PKG}/usr/bin/steam-runtime"
install -d "${PKG}/usr/lib/steam"
mv "${PKG}/usr/bin/steam" "${PKG}/usr/lib/steam/steam"
ln -sf /usr/bin/steam-runtime "${PKG}/usr/bin/steam"

# blank steamdeps because apt-get
ln -sf /usr/bin/true "${PKG}/usr/bin/steamdeps"

install -Dm 644 subprojects/steam-devices/60-steam-input.rules \
    "${PKG}/usr/lib/udev/rules.d/70-steam-input.rules"
install -Dm 644 subprojects/steam-devices/60-steam-vr.rules \
    "${PKG}/usr/lib/udev/rules.d/70-steam-vr.rules"
    
# Eliminamos la restriccion root
sed -i '159,164d' ${PKG}/usr/lib/steam/bin_steam.sh
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del paquete
f_versionInstalada
#Si no existe el fichero se descargara
f_download
#Descomprimir sources
f_descomprimir
#Cd a ruta
f_cd
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales