#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20161208

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=capstone
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=https://github.com/aquynh/capstone/archive
	VERSION=3.0.4
	EXTENSION=tar.gz
	SOURCES="${VERSION}"."${EXTENSION}"
	DOWNLOAD="${WEB}/${SOURCES}"
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo 
echo "$VERDE"Compilando ..."$CIERRE"
sleep 1

make LIBDIRARCH=lib64 DESTDIR="${PKG}" install
cd "${TMP}/$PRGNAM-${VERSION}/bindings/python"
python setup.py install -O1 --root="${PKG}" --prefix=/usr
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Comprobamos version instalada del paquete
f_versionInstalada
#Si no existe el fichero se descargara
f_download
#Preparamos entorno
f_preparar
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales