#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20180526

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=ffmpeg
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=http://ffmpeg.org/releases
	VERSION=3.4.2
	EXTENSION=tar.xz
	SOURCES=$PRGNAM-$VERSION.$EXTENSION
	CD=$PRGNAM-$VERSION
	DOWNLOAD=$WEB/$SOURCES
}

# Comprobar dependencias
F_dependencias(){
DEPENDENCIAS="SDL2
gavl
frei0r
ladspa_sdk
libiec61883
libavc1394
enca
libass
libaacs
libbdplus
libbluray
celt
libmp4v2
faac
libfdk-aac
flite
libgme
gsm
libilbc
libmodplug
lame
opencore-amr
opus
lua
libquvi-scripts
libquvi
rtmpdump
snappy
speex
libebur128
libbs2b
hdf5
leptonica
tesseract
twolame
vid.stab
libwebp
x264
x265
xvidcore
zeromq
zvbi
OpenAL
libdc1394
libxml++
libconfig
libffado
jack-audio-connection-kit
opencl-headers
ocl-icd"
f_dependencias
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){

# Fix linking with flite
sed -i "s| -lflite\"| -lflite -lm -lasound\"|" \
  ./configure

CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --shlibdir=/usr/lib${LIBDIRSUFFIX} \
  --mandir=/usr/man \
  --disable-doc \
  --disable-htmlpages \
  --disable-podpages \
  --disable-txtpages \
  --disable-debug \
  --enable-shared \
  --disable-static \
  --enable-pthreads \
  --enable-libtheora \
  --enable-libvorbis \
  --enable-gpl \
  --enable-version3 \
  --enable-postproc \
  --enable-swscale \
  --enable-avfilter \
  --enable-avresample \
  --enable-gnutls \
  --enable-libcdio \
  --enable-libssh \
  --enable-libcaca \
  --enable-libsmbclient \
  --enable-opengl \
  --enable-libvpx \
  --enable-libpulse \
  --enable-libopenjpeg \
  --enable-libwavpack \
  --enable-libfreetype \
  --enable-libfribidi \
  --enable-fontconfig \
  --enable-libdc1394 \
  --enable-libmp3lame \
  --enable-libxvid \
  --enable-libx264 \
  --enable-libspeex \
  --enable-nonfree \
  --enable-libgsm \
  --enable-librtmp \
  --enable-libopencore-amrnb \
  --enable-libopencore-amrwb \
  --enable-frei0r \
  --enable-libcelt \
  --enable-libbluray \
  --enable-libass \
  --enable-openal \
  --enable-libiec61883 \
  --enable-libilbc \
  --enable-libmodplug \
  --enable-libopus \
  --enable-libtwolame \
  --enable-ladspa \
  --enable-libfdk-aac \
  --enable-libflite \
  --enable-libvidstab \
  --enable-libx265 \
  --enable-libzvbi \
  --enable-libgme \
  --enable-libsnappy \
  --enable-libwebp \
  --enable-openssl \
  --enable-libzmq \
  --enable-opencl \
  --enable-libbs2b \
  --enable-libtesseract \
  --arch=$ARCH
  
  make || exit 1
  make install DESTDIR=$PKG
  make install-man DESTDIR=$PKG
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del script
f_versionInstalada
#Compronar dependencias
F_dependencias
#Si no existe el fichero se descargara
f_download
#Preparamos entorno
f_preparar
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales