#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20170818

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=libquicktime
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=http://downloads.sourceforge.net/$PRGNAM/
	VERSION=1.2.4
	EXTENSION=tar.gz
	SOURCES=$PRGNAM-$VERSION.$EXTENSION
	CD=$PRGNAM-$VERSION
	DOWNLOAD=$WEB/$SOURCES
}

# Comprobar dependencias
F_dependencias(){
DEPENDENCIAS="libmp4v2 faac faad2 ffmpeg lame libdv schroedinger x264"
f_dependencias
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo 
echo "$VERDE"Configurando ..."$CIERRE"
sleep 1

echo "/Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj4KP/G3RdACgYSwSGSBse52ctkNNMlj+104pwANfUHUZ5
MBN/0xh3BvQtWsAHSXUpX4LlhaxHm7dNIDrQwz/rffUdpJTVF1Kb6VqDOrlbKBh5oqFi/eKi0BM/
lUQuujdOBpEz7eDm40tSkfbEZXjuvkHg0mN/BMG3r/aMfXpM/j4VKNAg4hEiNzkHBd97Taq627Xg
FdUW2V2Z8JBkSbaAETCwGwH/A2G1ELTpWwuQDR5B5YZqB0iCtWJT/XungrtUYmnhZBO2UlcPz5F9
gFFoegihUInF7ZWOPzKmavcPp7eueBooP2VlecPH+51EjL/XN3ae6Q8+JZIwaF/xNEnBEBJlFoPz
FJFA8T/VHRLvRM2mZPiWSJyN0TKgdfJe4Xv3ys8nwuj7/SU0QvjzRewdayqNGO7yGdDt8GAKu3xi
bRw6+2Y/K8YEfhVxcFJ2dQ0IfiWqynemIdMZBB1RxYRYJ0mOG8VewYoMTw6tyzsiCwewq4BDCWOz
Ov6YV2oJYJm/uaekDCRXk1R+aQllM0z7w3aVLhXhjSTEOqrCba+7ZShbmsaibpkK/6utGIVP7NOo
j2MLf5SpT0rNOQ0LOJKzGbHbSs54TJ66Uc7PUFsjb9VCswlC8TQfwL5J8D4TRlTYiluntSOSV/KU
D8cxdUV/egHwrTCZJn6x7Srtvkylfzt+bYeI7RmH6hPcMX+U8UnkTxcMtTLXo7PDVEn3lTb6NTQS
hjuxU3kOXsC6aBoEgxanvtdWL+JlorAMcYlS5UhhEN7t4C0TQ9LVImyxdh4agsum2Gmog3sBZyMQ
2gE07pLaKt4N51Vk6dfCMcZd4A6JuDblfTFlom/BTPV99Q8dfSZwqJZFpGITB36/OPJl88Cs3hNq
p0HOKw7ZiAdKQylFkprKDzb4qmyodp6Ha/epOsR78hKDwe8GVK4dH31JPDuiSBEz0DJivQN5Yuq9
bxFfqsmbbQMX2bqgbijOVResMzjYvdm75fpMhMGatQVZAkOVy3WI/lD8u+c1RiLmhcOlqpEC78mm
6MZqQw/FL4XfxxJNXo3ZU2c5IqsGoIgmpbvOsM0viF0N66zY+kyw/IA7DwIjLOsktAk07hRPjKSO
02jOwLzVsw0KIQIylq3FV2+nrHLEVnGTLIdhRQA1OTOy3RyrFjuZF5x8D6oPAUmFmYYKXOV7XF4+
BHAWSi6cBx5g/4wwylJ+mz6soFPgNAMw3mcJ+E6Ck1xW6EMWWlMuIz2dtUmbjL2MC2w+V2PPeJ8G
9ihDeYVW7Xda284t5Xjs8jSSFmktObbaSygjbfjacb8n2hzUAV+DTksB7+7NfIAWxMtPg6Nsfv57
weDUULDbZpjwlAtGbwdqTPuOb2hNZqTXduTg6I3+lEKUrWpfNPyZC5LQ5VA6jzDbOS88eahPgBAe
rTP0aCu+myo79sHGySJtKcoAvzvddjGT2jqbRPU39LLwHVQ3yHzoWj2DRpWWPX6/kr8gfSQX3TjT
ABTG6oZ8p5nje5I3WdZ2ba7nB9pZP8k+YMchiReDSQ8n0NbBf7GluIFoREIBWy0Mn+o3xlwvx7Sj
dgXVnSd2/uIIkqMRscMZt450HlSTxt5byO0LcGCHMeOnaEW57Ic9f85z8SGP6w4AHaUKNW/BkVZh
YuRUlrTOzi48OolFErnIEx+i4JgDJQZe2gzPbRl+SidAxsqqHK4ovAlalV09hAb4xtTkAu9Khtie
QHWJgraslMWJ5AHLTdcDhQKD11wqi70ZB/iYDhhgzne4tOHmenyYji61F+UMz+8xjzOXKhk+Bkm8
/mnjvgMpyZjhvwN1o9x8SVu7Sn7KAV4Hfg+Dtay+JPO3v4/orV4pPmm8YzZEohYmSO/hMHZpFQCW
W8LWVOLJMCJ5/qrOahKQaWmp4omy8kuA+z8smxbWfLsqnrF/Pr1CvVpd858Gteuv9YuEbaxKrk9u
FWCeRod3Y0MwAp/b86NH8zl2My2sm8SzaMDAOdIALnoWaUGqwdmMuCPuQZGdqxE1mg/TdF5BTOEy
bIHXWkf6iYicYCNhOIHpaf2yU4GJGc5GlYmPP1qC9T51riUg0AjO3uYCMNmRzKjRDEWRJYNRfS1R
0H15TjUmF/6+x+3S7gKBbyK4pZGZp/WxLOKtFTkyhxXq6SGuztcoSCva3zJGMGJcNAXihOANlh5H
fS91DxmBT6KeAKvRw4lbbr85S8VQ6h39VBzz6dGnf9uYCJXVXsLJ27hkUdIHQqVMhH3KCz4AfwKo
qjxjv4t4VdwobTlQu5SiWAf5ZUio4ARAPkYBPHLea0ZZ7fiXvdPeAgbLRzgnAzRWcSz2026l70Wq
MffgAqgmxydEyk+KmY6T78xtw9ofKuEj7NtJEO+5Rd01YIFScmT3dWNHPGZkaJrL7sQa9pF+na6b
4v5knb31YTQGUt2z/4DewfkpYjKscKV+vro31p+t1lDsviy/SyQK8yr64Jkg0C4PKMAZ7bHFjanZ
PKwzUndOnkNoWalUNBWCD14GDCfF636uEGQKaN+ZpZ6NicAUCYsH5NLdibb+3RhqkaZ6TJvBiKq6
kZT794flHeJe21X9IH/sRfYatf0e3p3TLFib5ThjBop7RHX9j7ImXIzqaL7ciLfSzNyvTmQ7wcJy
fAREJ5/yo6t7kXd8HzoapaJ5D5Yi4pIYbOIWP5ho73ACuaDKSPVjVu/BslEmJOqY/LtzXEr+obPy
McYvfJVBd5hmDPjc6ikPs9oHxHwcH2omATACcVCkXbMQ0WZqVYQn9FfmRuTxoGSqzpBuaRSz/68L
zKKTNhZlt4K0iRSJ6fCTUccDRhlpxxGmnmfmqY4DRgs0PGFVvi78yq8xuM+BF0F8Zs9wB6ykzh1U
3Fgpl91SKOvsvcBH3U9D6EqHmz3j110dCXld+ivO59JRqQbjaWJZ0RdNvw+Aw2nfypC4BJTvpHZX
a6r26S02QlF0Jl+WVS61tEcbD+WE5Ltw/98SwAlbE4PHEcabw4tk+wbysPHeHnkD9PkqgyjUgl2N
lf60aDD0gX1yJef111M5Nbl8zUNWIRKV2T+QOpWbjEX7mCJy5a34i8EPXhfkQrkoXjFXM6NfuP+t
oY2MxXECuysIeDOlT0k6EVXHvVp0Nm7mSL1Vuo2qarL4+Gk0CEDU0pFQ9hbtk7m76C2dlDqeYLuc
zLf7dPwi8ek6aI5DFMbzonJy8QGV3d/jQZTn2lTHRwIJlO2jIfR0D48/esjKeC4RcPOhsTpMq6tx
uF3ey2zkA+6Jg6Rgk+hiYpVtnB3bCpX1agXVWO1hlDYQHBRKB258kX3pPyRBgDAg5gMd1bKh6y4F
ljJG4/aAB+7oBAw064wcyU6qmc02AAsIHhp6rvnZHxqvP6eZbv+KBdIUPsrUnM41l2gk850A/fu2
+aWN9zeb/U5Qxd8QZGtkYfnk5meDi3R5NPxXl7RzdG7RF4DTcg1e2qXe39+8YYruGw95xyzftZzo
/zFLBF2Oc8XNHRLNJdC3s5crJ5xAvu5FnJGA+lGAVT/eT8prViUOWsa7+qCoRh7Lkb7R01rQCT4t
1NU4n4sc/CRyU51dNx6JgumF4R6dVOlue4z/6WRL6W2WvPQ379MwC25qm1d4G6iD0ZsZ/v06OdCH
R0fXri179E8NT1GVdXbyQckZiVa26Ks5xsFw42e2izdeY5BR1mGencF/B+MAizOh+WyFNclNy6t0
KObjF8BJ38yTnm8dMHDMULwHm9EXH7y7fdxPR6LaHhQi7+R6a6RIWrdA/caMFSs6uU2MyjJ/0D+s
8xePP7fCC+gIpdXTeIeibKHST2pKE6y16XGNB3sFMGhYiuGXVhlDhAIkhaXdjTIcEunBorr3/aic
ifXPOMziv1sMgPdbmF2DZzz5E+umeors8x7B/U2IKh3lVuwfA2PDjpU2La2iimKnusBPkZOtuk/U
0SvFmMP3Ya0CwCA8zxvLMJKKkzIptc2cuTbm6FYzq3qCgTw50AWHjNiaV8rU299EhsuHR7XKhBx2
3NJpkbdsiQB9e4CncRwshbocBL0ahd2iQcE/7ySHz8bz4kkOAffTAbtrXBFuTcLXCtJDJc3Hudbs
E8/MSrmDkPS7oLAA7otcJQpro9zxKX/SY4TyNYf9+ZtHEUbByogJT+mx7cyLZHt8rwRnxbT8bAfk
ivO+e7Y4GEn0HgRecDrpaq5ubM7tzRl13a65W+s3kCo+mjPj+4DTPxz+Vubu3i5psj69MHpx9hQe
B+PiU3EeTVFJHb//S6ZQlUiQ8oYY3S4EvudCCOM9cZk45h9/oXORYkysB5qjosB+RKjOTQsFRbox
RzApDXmpcrn9clHpGSij3d8OvVbluGkiDwbn3XCi0F3h5PZOihX7nbbUETqXjXBPuNIty+3BGOfa
GL5bVTDOW0Tn6TGDkOzfABL8YBsn1LDqlsKy9BHYeME3zIG8aPZmeoF9qZduSbCwo3K/480n6G3Z
7xLklu0nQWcLYN3CSzqJbFlWa0HIoSQQzM0ZnL5a9aWkmfujVBmSevHAyjehXyNRXaJ58X7YwK0p
yT6AzYYAUbWoVlOpE4xUIQPOgKYueab0YCBoouDJeKCixAwDXWnRZq7567cheQWZBJnm952u1QHX
AFWxK9X7DNtEuBjQfvxu/9hSmMqyRYCTSH9DuzHtuHkvvUIYVi94SqCC065PR0XxTrxibHSysnYZ
tcDaDFbiW9+H/7IeaRcP/45W89+Yiav82BRA1ObFOr0tDgnG89GRfikIGuNFLEhRaPUO6Osl3CJ1
TI2m5z09e2DRsQk02ni5ikrEpjT3vF9A71X0z0gpuFgKSwOmZbDmjoZZjhY/g67SEhN7BJrrcUNN
L6IpFbdctW1LoOi5Dz1RL9fXQFnN9gNYbbfkwFWjx3pLxUhwY99sHHh8SfW+pj0slZCa58VGG+32
QgjRnYxzn7miQ9lzSh7187UqYaja2OKjUDtEwlJ/gs9U1z/bdfl35uI0lS5nPlw4UQ10bRGUPJEm
cGzchN2itjjh7guq4LH8sZJv9Q0ie8ZjrJgggHua8fbm6wG1t5i+iwEyVwB08o+3UkmcST60V7b9
bb8YUQZsYxeWGIDZObVaU/R7Tukx/upHdDh1hvEmRVoI/9uA/27UhTKE5O4KiriNwM/i6JBFN2aW
pz6+zKeCyiY4waKvNih6Cv/ZjGjnea+yt4PDaltGjoWMMBAQJ10jWFTUs1+OI02au7JXxlM/XuEw
P2cU+gV0MuMeGiBbaOR865yr18pS/IZSmEChGvIr55QVDqoFTUuzOP+u1iF711TSYkUhx6iud9Eh
YnGCl67ygso2TbAI92HSFtkNZ7ejLGn2XQi6uZd52ArQeeZeUFALNTNPyGz4J16OWuv5Bj5eOTbg
ldfQozAN5BSr/vf3YPE3GV3pxgfu77ehnH8XCcZT4/D4mbtcmDIXgbFMcBNyywxUAVwsZpKgEvDv
l5C3/3rF/RfP1WFCWH4hJ+BH+GjtG8RpG1/8o0lADbBjx1KktGQHXitA0yeriKK8sI5kWjk8AneH
cOqnFp3FZaJvjl0SN+sJzfxJppN4h+shyZSdVPSJ5j9vFt2bybyUgEioEj1NgBTtdMQRcA50dh6Z
QIvL7El3hlu0mvX3E2fT84fU/QEyLR2hvI/lxaZxkNpcYPy2rV6NnUPFL6yRidI6a3BWc9S3oX04
tkfhPQcezLWX2ctNGH/Mmw31jPyJrfzfONZ+QwLAHwM/C+cDdS2GM6/rBaB2R0xxc1+4fe2eVaSB
Jq1iGcIQBGDBdT6SEnyxzafwOP/7r0qjcvlpgTI6ez0aSFsorFptJ+wJ1kaMSuXdlsXMhNimooEd
zgf+cs5rVACW13NByrQihTbjOLU7Dv2d3zjUMm7a2qtxX1Ff769mq1RNwmWFJtTnqH2ZWQJ2IQQ1
81RU86TAn4jZu9M26lCuUMu+DF0OCA7CjefNxr7jeCKOMPpqeR0ugdaVrsHvb/M4V9HByLUmc2xg
C7Qyb2KIuiJOdIbZqFlXGB8Imuh5zo7nQPY5ZDzwIYrn1/bZiYLSbtK2VoU2kWc1UvYi3Jk00bs6
+3k4n96g5PLMqslomR50sv+wDoN1XTQyrDceA7wMckjgp9BVdWnNYQ778LiwwxRcrCfISXNdHHbc
uY2Sxb2puJF4yrBHuNPtcnJ45/wlgvL1K71Sl4wiAkJAfEPIzFbOV8udD2VttaDwq0YjnMO1pWns
t1jFE/cChdy1psvoj0ym0L1ZGV5zBKek6bzDIPebfjHtUAZnPI7GvtDy3qiS12BQrMHClymrcGLI
4L8Cx19IuogC4vXw/+0CdPdyoD2hlNhGLALCGO2BSNcwLqj5b06Pieju9SiTs3sg9LezKZmr06YN
Wgak1KfA6Yd1k9dJAod0Mu0lOM69H0UzJ5e7dfODaJZCs4LL/6db4nHDmaMtrD4esYKX5YLrAJon
jCddcS1dTypN48SRvo3h2ks244vLYeRONUEPTkuCZil5224jDdk4CzbwSwypqq3H8cbN5UcICytW
VacrwaKQ5XPnkrwBL6iEKaqTFanilnGR9TMSIggtSI9HWpp+GtH7kvsWGlZRMM2kooYdYpdvjQSz
u4Kli+PwWDhUuAg0pKXhKyGVIXh4SoKKf0Vy7rNjYs8YHXjakUZbcSJ2CA+2g/YeV8Qi2ip5+sbr
NCryAuVmyM4TnhwQiJRYwheWkG39m7PLWdkIebw4mvYEyxs8lzUY3hvFx8OROWVNg3KIG9H9n+XC
zxGQrD9aMRfIqE9rkbXkKf7xl5LYf9CJ7U8IZf4Sp7uRroA13FAMUkCLNRbId5A6iYXYuB3q4+Oo
E++TkDgasre5ixj8ZlDz/aBU0jZSXkWuehyE0sivTAzcu+nfPZjKLavXMTU3TYtJj5whIjCQMYG7
EowxA1ys6BIbLMy7zB8vDv/w5l31YOzu/oPTKLg+CXiojRm58ik0pHX8xJxygVQM4T9GgaNyd9ok
Q4m9giO0nk5UgOg9viN+UE+mvSYm9yaMzBQ2ZE9B8dD+S7mHVFUEFkohvF/HcS0zpLP3SbZdvf3U
cyEWu+pwTq2JW+AcYNBGz1MELjb7+6ZTbqZbKPJY9rd8OM1TIAtZ0a4PDCKYAaULQDj06iCZe5zC
fwMsuZN1xO5o2pGSk/zEQgQinwBFfWdRuskbEqf/OD6Cw8B2L+SKoO+mBp/OO/ANluJFj85nYRrH
rd7DPs11+w1c9jud+xN4mJRkoeD0CaPaVrgbdzax+ws6Ue2zPKDIYWyLDyfUAIr7KaPLZ2gU9rBq
sJ091m8GkDKZswZHV2opRSRCLayui1qyoGXVUp39EnE5gDf34Z4uaXwi2CV2H5Vy4NS+dWIWRpVS
O9TK+coH22w3QsL6lO7d5c0As4hFnzd0lUycHdg0qj4Nn4bKRPOCT1lwiiScftLpxaO0Lst4OGnG
+qMcLb7XVst0F8IdMjiLrfP8Nx46gXn16uiMq5/Gi0bQOA4Jrg8Thh9s0vcOY0teaqYgUpDyZn0c
VPNm9Otgsyc93fmSiFoJbkmHa/EwxwvHx/LW51dbT1BYJGAIn5A0uBtqol052BhMDM/LXeZ0mxl8
TNVtY8bUJT0uweCpGNj5Z74ahxaIQS9TvnO4g88v2GBLWnVRmr6t21XfZucfTsNTbf3E2WTABofd
QylBErfV7iglDg52cwp/fJvCizSFWP4PyYx8QzGdKOf9mduPiur/MG4v2xQ2wXZ9MSaF5Cdd1+Le
T/tFlkNWU7YM/YaHdBzsdphhXeoD2aSR1hNsezPqw0+j87YQ9q7s+zv3+BVj2ty/WbXkE7yP6ufa
W1gGl/5V+0gdHePPdxTm+ue+kPCnCSDnP1n80YDf1XBSVsmoZQf/r2ZV1ce2EA1WvoZ9B07LKEBV
JKSykTF4fXLs6oJRmkScX0YPtJgoo9eTHNG/9mq+Wex5hJCM+8INWuaXNOrVt2ySbDjL8q7ZG5o/
sctjrBoGoxLgfolwxnCcsSCbodTd5d1V143JdGGhsRKulkb+wdHm7vlEOlYh8NxSZnvRbPRj9i7l
n1JIE59vE7HC6Scspe4bumBjTh4sEcL5z09qst5GdB6NET+P1v5htZ3/hgq/V8enAa3AS2zxn6ud
ES2QNlq2/6Trjgda9/NQHAtv9bzEzQmwYPWCcguhIcGpjzdpCgJF+dRcp0MYJGTmxbjVd4vjVuMv
TaygoT7NxjjJZA4zkMIoyY35a8YHElasDtvzZrebnZy6a7YRcyCgMsv/TJM7enzH0T8pP3w48W2p
QurJRNhewtvUApIoeXy+Z+d0a/OCYGMzT95rV9l7wCbpqNM7MRqvedVsmpiNKUsk4zpc3kt78hlU
rVKyjLhZEonuOfgyrDmO3zILfH9voBkReKTzZ+mKILuXsVWTYTx9G5ydo0iaOg2kA2pJxAMfQrzv
HSpIS45CTp/Jz/AIN2RIbwkZiOZCQ7N0g2QOLjdy9WWtnqsyTLzqQ+Evce4Mr0mcRTWso/MKLk/C
xX6JsAQ7+j9B1FV7IFnuuHFzLM2l4+XHYZjqoqKg6JsKHfMo+IgJTp/ZVGHsrt/SaKxUKSZVNerB
evq445novyX5Ucmu5dQ0sMyewz1jCiC/TSMO3pjEO7Px3t8sWz/kz/E1/XVqXO+x/06bwZrantKQ
aMaV6UgV4Hg7JCApVRLGGyK3WwI7n72zJTgZpIApKlUqWXBJMXOYckJNR96yof768EjmPW7R5X8H
VaHRZ4U5AEBO8VCaKfSvvriRNRXVqkcVw7eHGYU+YRP3vi4S8yBN6Avwk0zmtt+ivQ6LRyBRnkh0
gSo/6h8n8HKr5eQnRydYSgIKQ0pLN8XGqcXQFS708Nof4mQE5Ogig0pXb5miEz/suD4JMVpzSdr+
fY/uLYGDwAnMtGce5eUNkzqnMxpUn6GEhDbL5NckyMu9dc4B6xRchiZUEjxa9bQCmflIha6nbZDJ
JaTSai+rt69drembkfdPdHZuYwRMqNfI8rtCyuUbxTlajLBsqlACsmtDU9T2fqv2goBDdsmcXcN2
ktqFwknhhVtxpKmBd/KopNZqLxar63nUqSZbNUBG+qGakw6Mo2/+TXzwPcOhJm/SG4xTwLgFi/sO
uLYfpkoQwKSG2HzYS0mnmSEgOQp1VFbRFFBcbSWhShG2qZ9lJ8BYv1UsVe/p/95ihAKOO4BoD7mu
xV2CRHx78bMpTQZ6SH8MFbCCm403TMz1IwtRokwfInTmMyOOTwr1rrU/r4O8kwi4kMTR8jwAkAVS
WoULUJo1VJHeKMGA5e2RZo6GeSTJ8rctTcmEsjVcz2bddrchYjDpHnvXwuZp6byulEJQiRhjUEhk
xi5wy2nkQ5f8WIxoxCl8qdZ0KZsqdsPvwtJoiM3Op/RIPRGoddlhCSmSBJwatUgAANsZRVys+krp
AAGQN4DIAgBJteGNscRn+wIAAAAABFla"|base64 -d > $TMP/patches.tar.xz

tar xvf $TMP/patches.tar.xz &>/dev/null

patch -p1 -i ./patches/libquicktime-1.2.4-ffmpeg2.patch
patch -p1 -i ./patches/libquicktime-ffmpeg3.patch

CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
LDFLAGS="-L/usr/lib${LIBDIRSUFFIX}" \
./configure \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --sysconfdir=/etc \
  --localstatedir=/var \
  --mandir=/usr/man \
  --docdir=/usr/doc/$PRGNAM-$VERSION \
  --enable-gpl \
  --with-libdv \
  --build=$ARCH-slackware-linux

echo 
echo "$VERDE"Compilando ..."$CIERRE"
sleep 1

make || exit 1
make install-strip DESTDIR=$PKG
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Comprobamos version instalada del paquete
f_versionInstalada
#Compronar dependencias
F_dependencias
#Si no existe el fichero se descargara
f_download
#Preparamos entorno
f_preparar
#Descomprimir fichero descargado y compilamos
F_compilar
#Creamos xzm , instalamos y salimos
f_tareasFinales