#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20170923

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=libtorrent-rasterbar
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=https://github.com/arvidn/libtorrent/releases
	VERSION="$(curl -s $WEB|grep tar.gz|grep 1.1.*|head -1|cut -d- -f4|cut -d t -f-1|sed 's/.$//g')"
	CONVERT="$(echo $VERSION|tr . _)"
	EXTENSION=tar.gz
	SOURCES=$PRGNAM-$VERSION.$EXTENSION
	CD=$PRGNAM-$VERSION
	DOWNLOAD=$WEB/download/libtorrent-$CONVERT/$SOURCES
}

F_dependencias(){
DEPENDENCIAS="GeoIP"
f_dependencias
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
# Parcheamos
echo "LS0tIGEvaW5jbHVkZS9saWJ0b3JyZW50L2V4cG9ydC5ocHAKKysrIGIvaW5jbHVkZS9saWJ0b3Jy
ZW50L2V4cG9ydC5ocHAKQEAgLTMzLDE5ICszMyw3IEBAIFBPU1NJQklMSVRZIE9GIFNVQ0ggREFN
QUdFLgogI2lmbmRlZiBUT1JSRU5UX0VYUE9SVF9IUFBfSU5DTFVERUQKICNkZWZpbmUgVE9SUkVO
VF9FWFBPUlRfSFBQX0lOQ0xVREVECiAKLSNpZiAhZGVmaW5lZChCT09TVF9DT01QSUxFUl9DT05G
SUcpICYmICFkZWZpbmVkKEJPT1NUX05PX0NPTVBJTEVSX0NPTkZJRykKLSMgIGluY2x1ZGUgPGJv
b3N0L2NvbmZpZy9zZWxlY3RfY29tcGlsZXJfY29uZmlnLmhwcD4KLSNlbmRpZgotI2lmZGVmIEJP
T1NUX0NPTVBJTEVSX0NPTkZJRwotIyAgaW5jbHVkZSBCT09TVF9DT01QSUxFUl9DT05GSUcKLSNl
bmRpZgotCi0jaWYgIWRlZmluZWQoQk9PU1RfUExBVEZPUk1fQ09ORklHKSAmJiAhZGVmaW5lZChC
T09TVF9OT19QTEFURk9STV9DT05GSUcpCi0jICBpbmNsdWRlIDxib29zdC9jb25maWcvc2VsZWN0
X3BsYXRmb3JtX2NvbmZpZy5ocHA+Ci0jZW5kaWYKLSNpZmRlZiBCT09TVF9QTEFURk9STV9DT05G
SUcKLSMgIGluY2x1ZGUgQk9PU1RfUExBVEZPUk1fQ09ORklHCi0jZW5kaWYKKyNpbmNsdWRlIDxi
b29zdC9jb25maWcuaHBwPgogCiAvLyBiYWNrd2FyZHMgY29tcGF0aWJpbGl0eSB3aXRoIG9sZGVy
IHZlcnNpb25zIG9mIGJvb3N0CiAjaWYgIWRlZmluZWQgQk9PU1RfU1lNQk9MX0VYUE9SVCAmJiAh
ZGVmaW5lZCBCT09TVF9TWU1CT0xfSU1QT1JUCg=="|base64 -d > $TMP/boost-1.65.patch

patch -p1 -i $TMP/boost-1.65.patch

# Configuramos paquete
echo ""
echo "$VERDE"Configurando ..."$CIERRE"
sleep 1
CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS -std=c++11" \
LDFLAGS="-L/usr/lib${LIBDIRSUFFIX}" \
PYTHON=/usr/bin/python$1 \
./configure \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --sysconfdir=/etc \
  --localstatedir=/var/lib \
  --disable-static \
  --with-boost-libdir=/usr/lib${LIBDIRSUFFIX} \
  --with-libiconv \
  --enable-python-binding \
  --build=$ARCH-slackware-linux
  
# Compilamos paquete
echo ""
echo "$VERDE"Compilando ..."$CIERRE"
sleep 1
make  || exit 1
make install DESTDIR=$PKG
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del script
f_versionInstalada
# Comprobar dependencias
F_dependencias
#Si no existe el fichero se descargara
f_download
#Preparamos entorno
f_preparar
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales