#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20170818

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=transcode
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=https://bitbucket.org/france/transcode-tcforge/downloads
	VERSION=$(curl -s $WEB/|grep .bz2|head -1|cut -d- -f 3|cut -d t -f1|sed "s/.$//g")
	EXTENSION=tar.bz2
	SOURCES=$PRGNAM-$VERSION.$EXTENSION
	CD=$PRGNAM-$VERSION
	DOWNLOAD=$WEB/$SOURCES
}

# Comprobar dependencias
F_dependencias(){
DEPENDENCIAS="ffmpeg faac lame libdv libmpeg2 mjpegtools libquicktime x264 xvidcore"
f_dependencias
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo 
echo "$VERDE"Aplicando parches ..."$CIERRE"
sleep 1

echo "
/Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj4S//KUVdACgYSwSGSBse52ctkNNMlj+104pwANfUHUZ5
MBN/0xh3BvQtWsAHSXUtUEZdGyJinFxLziThzhmoLTdTH3xLlHgEdN1ZgI9Q+MBYCi0RqVDW/oW4
nPGStiJ6aOP49ifdaJOgcFMh0yuUd6iiV7poDPtc/yshtRu9Mpr96SWz8HdxwPh4icPNAAUF9TZP
/PT6C+Oz2fUJmBzEVfAAHvEZ51Fo1DKnalQWTfC5g4yU0ImtF7TBnonI1KJORFRFysvZLaxVSpAl
i6iDA0gBOJOG3/SlyP3LhptKfkL0InV0rYWzsrguE+NTbaJq7vsEd/Nny5sQei7MXz0dJQveMbjw
6KoD2kiReAJZrdOR6I7XH8zx/UYKSjinyAiK5dR1AfWyM40NQRYdo2oO9iSl5JE8/CnDeWFo9TxH
3+cr7XR/q0+NFAAVm3c7QHmSNY6Tf+ojRL5taotghLEeLPqFB4VaVuJYFktn5vhFwnvDUkA3HNVa
H1iSmEf4pSKcjdAMUFh0QZLRbMDeNBtm8NzCfnUQf9U/APMOZy/B1fdEi8F4CBKiEZZqFCo5EVk9
i7BicbwJt57cLid/ci03GOjdl+/YqzJB+UJUk3kTCXjPk8QOOJkU8AFZT0ydIHEgb/TD8p2M6QMc
Ct0ZbMB+LFrsdJ4Ac0Kd875Bv0LQXbMkfu3djCeieOqVHXXzEyF7m/ZwpYi9XYxyl46j91IsOJGa
CElwC3DQIEO7PV0+aqIWKcKUCzC6fPjuuR9V425wY/sISa9c9LZ3WigiwhaV+PfkjnRBmoTZ4ueF
Qq7bj7m3CPT5/1UlkIEZBHBO7vtJzerS+A8bzL09TMO6SBSHAddjIcOy/jol7hvE+qDAzXl0HG0n
MHzB6+w21sFIFWIzHSMelrgvTkl1a0OtX/ktEkjK4jMn5K0D1y0WbG53RyTsEGDKQHu0Kt2PolxH
NIrYBJP8ZLUBxgu79g7kxCsZU1r6ZqTg9+/8fnMJBij5NKEJb143KxIGN/+y2wf24eJRUpmY8Ys5
oDNxu+azdh4XDw5t1WFmm8HzSDuLn9hQ0C4n7yGG9iirTL7yYkm3gp45it7Xo3zI/pIQZfgo0J50
rxdfzCX4nwQauzKt0nC5mGtygrhZAtiwkYwH1jZdQXWoKeMNMejGHJ1riIbtNu0GNQPshytXCZmd
gIMWH9B/S5gMht7H2NoDmZN5HlJvAV/OdgWzU3MPnsBLw6nFeR3oqYTZCamjtf3pVg51tlwea84a
jjsPvoee5+2ztqD1yuiMTY65nMUP9lYJ01ZBt/mIMe4/13uoZAgpN60lclDT6IW3vAge/vAQ+3jK
8iiO1c+OX30eblJg1wcbsykdjjk2c9/jf+BdBdMExVnH8Ewuo4RiRTLH8rKgAwJRUKJNPXuhmS77
HxV2Sij6x2pBpSbhdqXn2inSH0I6efs3zy4LfgkTqZ/GpijF3O7bYdt6qQ2o0Us57XipAu/Hl//3
6eiZX8G8UcAXypAujoTkFySFA1KhcQAvLMV9IxgDcmTWzSRNwmwyYGxB49Cj/I9QdUbmKiD5Lnh3
fgumM8kR1qE4Zlcr9nfIPHck4MediENeQryjjuPoQHh0oNlpK+KXvbTdTTL7gR31R34/f8CFXZFu
n3c20wEcoAVkzIZRDTixJi4GjcnwgU+6hmM3VYsLrlvb6lyXqUhpBop1xuSz2K81m7h4oVCeBzfu
oFY83YzxjLLpxFwUJG/BRrVKzPaBGinIqdHrElvzzwhV1HRV6dSs6A1q9THaSOgi1vuy4uooZ4rP
lgz+zGPMiDl4407lReOEX1C9mpqRlJwYMktgKYx9ocf9oc4tKq3aP5zL9SgzkQsNyRxlgKHvTZf8
l0AHE1Ue1iXD9QPaDNnSqrZEDX8VybE8QsCNfkpo913MWqk+A+myQw6cTtqhRrhKIBiBMbPeEL4S
dwZX2oPAiNhHKfX3XMxgDP5pGQIMsMds3h0nAGSeoHgj5JcFZAxA0r2hRQEhCcAbm/dHFDBnuoRE
paNXoQqzP80ZXRG/o6djGBdMJzIrpmivEZ1dKyL3QgQaqZHjY1rHc4Gyu+JFupY3zEIo+pPqmHCi
nwD8x94K/rC8tK9wPLaqVpaNk3fLMhL99apgyZVtuIzTei5/b+s4n4t159tsxvswZhFvY0XY6sG+
sfc6Yh8wQTW8eqFnRONZcxq0zrj+3SO1k0sYjibD91a5jd9IiildFiqHNOeBbplwlFv2ww1L6HwF
1JI0/RLUGQYpRsxUr3hBZMInZFipqMuDtTOncDSyhCSXyEgbTWoxWYIU0H8AuJRaoyUj+jr6FicW
22gP7i6AAHfATT6HcZPBxpwxEPV+TQjWEZhQP4d9+KkUfNF9Ua8/KvmKBTsYFR74XuzsGD8Ezf/D
+kBGHPSfkWD882YUgrIT08/lRcQU3tLccw5/Uzaz7PFVoB0m1/u94L2RVqnSSL5V4FhF0rj7jYa5
fWgUZdp9FP/Wz8Jw82jAp+Pit/MDs3697VpEJTcTfdPz0Qkn/+yFaGsfApvgqBVwlpl/3DV3LgiK
bnNZVaXTGIzS4K5Fq6bp2T6ekiowG6egxMH66cWqHBml9wVoG8CEf6jJgo4zYRy2D9x3FUma0Jpq
JLyh24QQt5TP/PQ8hi+CFnsVy4T93oloI4MvjHWO0D6xHMso/XxgAA+G5ftIDL74/k47d4llrIpJ
z2LrUlL94TcheURU/A36wSepD7oBjpnYnhCkb/HvmQVA6btGx9zcv7CeZbNyV4HEQ4s+Bws7cLh9
mrDPYlqwrgRqekS0ZFAe5l9YraslFlHBdKWKD7oIhv0vy5T+DKsN20Xt63jDGSl/zy1Bi6FQB88S
o6TT7iAQDHVVTXXkS6Ak3OLZJ1H5jMmrdbPfZuUQN6Zo11Livq1LgENB7/3m7HKjS5NKLxyQdKYH
MuxeijuksxrU3ssX2I0ZzCUU/vQl+xaFXvyilMxv3Sh64gmws1jdC3m/5lXXjGfpIJRImZmC4d1C
FIp4/YGu2xSBZRCx1t0pdoRaJhxb4NbCwjDLiaIDUqlOQM9I1mvW3Q0eupRCzr0+fyG022s+ohq4
3lKoJvFZM+gXAFuo+pVmltgyNTFoySkxqnmxuFcBSvV9QuIvqPeGCm1E2IekW88xXoKUdYvEQmUz
O+l6EgtMcHWK/9k+V0hof4hQ3q3NigvJSud4Aw1gSIWK5DNAEioeJSihwXBWssQCpP08zPQNArWU
zof+dUBb9EHdkx5dM1Dn+qe10ZcjtZvkEy5lY/08tVecvkZZU+waGWZPlczM7VP53f5UNBnYPgrj
A+m7/5htwRuem9QbMUAZABPPxDct4TIxLZ3iqScSTH5OU8QjNKxw184D4LPcLmsW+32odIa4m6o1
wPtz1RhVRqQkpWMmsaQ+2ofChoKJL3vHvYZAZhuzSlhkksw92hGSze+0R8yKJUzA6Ro9ofBFTnee
99ifxgsnvhmk84M5Jvo9Vm/Vk9mH7bcQL2VtKFPRK/thxXdQ9uCPCd0aouq86dnUKWniLcMiz1xY
oO4z5GwZlhMwtsxyvbf91bp9ePxbGf5Y90ZGePeb/X9jM8vpp1i+ND97T8JIaTVuepJj0lwrGOPZ
bHFTFtPl/3WpECJEUJbwEEjmx6lV3w1Gia155m2fnMYmXGVxvkLizcNb7EHUqgXD3nOdpdXJc/5A
0kYwpXKo6OdvfEnJ7MAKdhiYpsIAsSa0hGdxTzLkNSqn0i3sZpKSCzk/7prnwJ70YtlqHau3vSXI
Bi3i/E4uGodia8V7Q3vN0w/rodpYeE0gm51UUmZ/d/SK1TSgY1+u91TU5dEDkrKR0z0QdT9CnI1g
w1avFh17LW3loGDgA2WkutODpuRoIPYO69g+zoanvfuh+r0MS+CYq4wOmKy+JQNHf7eid1GYEQ7b
LEdAtOlPyOYp7I+8sov0GqY/J2rzM+zMT3DD0j2TeiXQ57a2YfkzhuquH+e58b5F9iFa3fg9mpoN
YHmpzW5XheMLPEJZ57HZxSYfCaGrGLymgpq2uigkleVYgVvN3WCHe+7/AI74wdKuEEs1k78+bJLE
jRXRlhs2WrXOam3IC/syHB1YoU6cSWAu9SHnXRU5YiXV9hlfYbK5uAcOyanVdHJ358bC0mSP7EyY
3A3868y247F8XIJEgzYuoywBRC/VpPfcYVIHSiqSrjVoas/Hw+43eciPaLgrljROvwq15cQKf/Ud
+UImLrOUAkHojlbjxooJGOAcCpr2zcKOj+dLXdzrlZDdopE3ly24Dh08PcUjHS/Rfwc8rZ1HVmEA
lZvn/iU4+m9Qs6r+mu7s08SqgEF3CTjxNek5Io9/NUqPiesI0ui5HjrW+ErAGpPwjvaCFj7h9qyu
QISes57ao3t0J0p7FMLbStWm4+yU0BiDpC0F16bhD10pzgu3crViG0vFI4BEqCHd8f9lpI4K1dHd
2WRpHhb2H3cF2zpcch/IEJAcajT8FBdw8NkjXOIHNBogAyiL5BE8ys8/s8VpsYU7rRnHrLmcmydH
ap9sipmprjoi0jfCWBkOEh82ZElks6lK9f0O2+cWMpUBNQde/GbRL3+W/oCCRs/MGxJuSiJL8bDT
HBNrUrZVXXRl9WTrEzYFUx08OYDhMJCyBybDUVgmr6gYXQxCBTbbLXjE593DbTkYQv2nWX2y54u9
4r975ys7TBjTGboixy3G0AwfXQUNr2m1qkne1KsXRzVmKNTFHlE8An2NzYYLxcwBj9/8sCjy51Rg
wh7tFlm+Gdfh4m8TbmocETSKnkpKt2GABi9O/Qbq8mDHaOrYJZrh8zP+spygE+1pjsm698JW6wdt
Xc3JkT6uY15oDsCi4T5vihxG0JaEKnZO49AEhU1ggOU0k54eNqSiPTJ6QJ9fKxo9oA+9ctxSwg5v
ow/58zFPjlhQzbcg8jOGKC95f9P7OL2OvepksoJcAbBVIw2K0S8JBvdTciLkH59Cuds6FSLxatjE
mNreT2/s5g11o5bw7dR2LdQrduVNhrvrDGIZI5urJ3FsdVUUFbooo09kGg78QT6jLaY6Ws+QzCq7
F+d16M244A+cz8L0gPRvt++H5RbY4ikeWoyqwU4xUlR8JJ6jNx2NlzsQjdeSqS/y1zfpll1SLYdF
DScNNfAXJSulwKtuceYCUPyevV2kITZPoRs5wJxfob38y9bXxzp494S5n2V+GA4j4VULZA7hw47L
K3z7m6XObwbe4SI8Wiugcr3bxrPu4ta50xYPK9Poo9unsGdOfqPhm9PGDlplcZm97dP0PfVaQU1r
A2QopbK1CqscVywcFBBnYEu3GY13wCaR2g5DjRTaG91mUkRwFQyGEehQvLtLeVkEZJwEtV1us/TM
ogu+vUd6PpdS7Q0bekn2EVY4j8Kd72SRYCG9WDuZMEqVIjdLAQcxYUeMgrZoWoeHsFPBqV53AToE
QX5GVwxu0at6c9VgsPXdFpMHsgQwdJ7Ds6UvDdZGVRYwdxqTDQ5hDTcgUelmdYNZ9T3DxdoixI7g
bMfxPnuV9WN91ATts83Ma9L6gpLD4WLTyuwksLVA+L0P5+iVcLCkMz6CQWSb6dSVc5lB7fx5PclW
XKqGxKUb//de2ZmHV4y4iM2ioRUcMPw9XmHR/bmiGPWrrfx7CCsJ0n9tn8Qua/WVIc2RWwiaqRpu
HfiPx8Uqm1YlXuJimuRAOsRpCRdbEIxqpQU8Ht/b/TziED8BI6EulZg3SLu+ZbghLXsQ3fL3uTB+
2bNvYjxM+F90B15xK3FhE8LTGQyQqo0lQh/55FubrlgNF8FTEoqNhf7iyn2QfJG1OJEgb8eGWMGR
zm9pH8xQKZVsEHvCD6kRz6YjBEVWM57F3mWZacmI5Z9WgXnIGe/J4+sRtAPVbwVx9YEfW0zRPNu6
CimC/3npY6WLOkjax2n7G4yAFUmwLVCkQzTdfuvwhFn1cmWERBG0L8eqQUVjONJ5W2OCJTvnUwcx
zcJsAi/VkC4xtjpVTo0W9I2U8Kqqt+K8S935ol6jXYIIIZzoyQjZhc9hwyzf+MJ/6LoUpE/hElXI
YkBLiGPIhPBI07bC7rEFTMLtAA7QNnB4huzcai5To1+stSSkcWgS9GizP3FJb1Rd6cDBH+dTzf2d
izfXCDpFeO/cA6lNrSnJ65Ruh45URvX9evI6PLHCXrj2/oQFGtE99d1BDuZt+7StAfOHqjrJ7YXu
scT/IDNWsKOAl9Op0hMIRv/BLWfg9ued3U/ExJ5zXrd0qXsbu9oi7fB7rl7fUzMfJUN1f2q6dP1r
ukWz2yGL38MloYr6lmYuFWtQUtpfkrfJPe9qqRtWGBxPi5w1LkD1kViJgYLsW+yveAM2MFFw+Tuk
a/2iHcyYuAy1dywNv219mLx10daTkfShuubJnOef017Z2AwVHi9MzkSIZMlCCgTXqseNyHLe2PMf
dV2l3egAZmw5wlHilOHroSYkRoqp2dP3e6/mmd5y85+pgQ2SNUw76GhivVwAIAdbjKS6Oy8zz72J
AqUQ68bGI1X/b94u5aFdle47tFG8ZKmUugRLY9Xc4z0MvRtr9hucBrQMoo4IFMTRkWUt5ZqM5ShH
8pfqRuM5kPmBcVOqvH860hKOphHdcEfTN7JL2wTZlSEYEQNGZ/Yy2ZZatelBoii8/UbrwBsYbBio
ysvN/y1IDgYlN9hZrOZP5rZmJopdDfbL54JbgBneCmcExNk9RgB8IIQB1kfsJXFcPBee8UQYqzTX
wz5nJEKOsUKz7xTmRORPLVFfrDGpl/+R5ZODDKdMlol3fTcaqWm0cIEmRY5eM5jMFT5fo0bagvAn
5NdIE1fNJS5pbBb2gagwePR6q0XRAs2CCsK3xnh+VP+lfR/Og26dH+LKIGTd8hFDt4+ey6yYZQrq
NIy5rvNJvcyPQUcFb6C2WB7OSHIftO/N+a5zP+gOQa0MKgd9fVM48L0NiUm8DVD0veRLu23iWhaA
Uy8QvAnhfRDp7jhPjnynHde6oFcqjd1fwr2gXNh0xo2mdolUrrJ0JSney7Dvh2b8Hk+CyagUrIsF
0cX227B3AymXQ/tw7PbANErtqnXkyDgFGJi5WOe4XqbYrDMgQ3xsFSscAa1ZYqFlbQVPNdmAo7ta
Wy+V95/X1AR3wnYdu2NC+Erz+R53awrwh6+g6j54HSBGHaTtseRnfeVK72h/r5x7R5vtv73VYK/t
knXqoWh8qGqumEWsEhyOYBhWbKKBqXyQTQrxylFhEYHyTFY0HJS8cs/ScnlQT3aoK68qzdeZRtgO
MmwJTppHlqtSU3hUzZDqRnkAYKLes1wrWxDCHX5dAWXBJGJMw1VPwo5TpwFbXOn5LVWdrqfbKy9t
b1DnZ3bor1Z5rjoJzAtN98/5/XyQkf62t/81yi/UiNn9Fdu9i1rqupTC/u8Z5rYNlvfiQQwniT7w
IuOQv6asuj6GSMzMH1pWU0BYKquEwIl9Lh9bGi9ModB/FDbslTAghzPGzQtunq5ICNO13ikWIUwD
cz5k0vA+Z189oCVTyL3InhFDLdgCXzCklmkyZujEC60q6YfinUiBoNwj7nP+5Qk1EUWOunCtb58P
Ma79a38Jhh2PZs7CuSLz6k8LUK/FUey/SDjq/N36pU29K97bYZpZlH2CFMoVCTZxWCjLILCm7qGq
zDrNfDZ+qzM82kJtttZ1dHKT6PlawyyoefZfbemQ6RYPbDYa1poql4McZUQ3F2g8ST3qkgP8i40V
whuOPiOsmxpkpxR+Pm1yGSWhTJO/3QzTNcWeHekVWv+CqbEd2/xf3lsrjxkshyqDKnGlNhxaEvcJ
q5wCfDlIfH3N3q7A74yUXgQUZTbppyE83RtWSOtFjkTSZ4HcIXOXHwQyeHCv2kyMPa27apKc/Qv/
7At2t2NI+czBbBjeiN5pmSAkpEt+MsgJoV0hhq9xdRt+5mIRes5/88gElw+XtVIqSDZX6imenn8U
9JKQ71Td+EyayTF1FFQKjz414viraJ4botK4ABN2Nys4/oDxSoHEbqana6C0m4PmkkFUeKLCVWE8
JgzdAD7uz5vLm2/pgPAAQWkA83Pe07MCShvwuHlL7/+vas6LJboEipyWNITmV654LDy5i3BBP5TH
lneipRXmZFl4q+71/G7bdJITV2NR0nK7cX54kfkJdg0OpdS9XSV3UDjS8VteKH9vJ3XkN1UQJCDm
TJ/2qcyWk949utBQEbq+oBqeg4CULmQjSLFD4tLeiofZAd8X55qUmKXYtB8OFY+whqvGYgdPId3G
oVDPi6v7GAADZOS8IFdaM99iJ2qKYCo6qz24XkCEgf/r1Zo0ZuTEncTDTFAkplfyhrRym0Snn+7/
fwDzowUHioAp3JSQvsC7rfxlvFWfBfExHUwCzW9QbUO3+VGFeIQBeqPHFhExhjnAjYmRHbfipfCc
6Sh2IAgqPNUYddCeiaN7epIa4tH7qVlbGIkdL0ggWn07lxV1v5awsXMr/BZ8FToYPvPas4V01mXK
PV4jHx1HvPpWlBij6QAdD6ecSX/0flttPMbqz2zq2nuWQUMn/vGoKkzeyHgBMSgkNTL+jtLV8Hol
TLPEm8ljW6n0BA6F3QCmpx/qa5atB9gInQ7W9oslKvTkV4C7+gKN+mTZVjJbHjkPmux7HC/T65A0
VQVvJ0PdvaG1IAZR+RSNtwJX32XrizajDJTEtO+LTRQVOq6YpI6x7ZHTcH6YRLABnRo3R4hRLB/9
tApiTT+/OiHYgVDfEMMuquT3QDm+uTQX814b1Eu6TmO8TNUuMT3lbyGzCSn0OPIyu70TeypVCBk7
x6AUWGckYjYD8x0X/RU+aZaEDO1ZeFr4MUUE1YwUrOTYCHV4L4xrdhBlYqOFM5+jj90Sj1orhdnA
JTZclwDUvb4bp9za01pIRiPH1XFQe9B9o7Fg5ZjeMeiRn7m1vxWzhmtJJ//CoAu7+XoL7AKmgwVv
F4i/NAlF3zUcAmy8ZvCUourpW7R/Zg99+Wy6na4us6tZLCayrRSYv9G5MRriK+Wpz3afNwlHKoMA
S8lNsJcm/Q2f9eoKKCbi+zoak+T1QgvOW5SGm86ZBFds/zEP/1DevRFCwNpi2nSpdcYgLJmC1pk/
ZYU/JPwHjZtljXJHgWnHlk8LmzsYcZrFrv8cKaZ+m5ah3mCQ+lAEWHXZmxr3eN3h7pD0hBOaYvQU
ycxPnEu32UHYJZL57GWfy5kEPV6svuLkq3mSGKI42sfYld69FTVfzoYxZ/EImITFh7aW1ZWKMVM9
ykOvRjftlp10RIk7mi9g8ytOnQBLR6PGThhedDGPtdYusd8Jn/x+JhKSicBYjcPOedgMgisbWGXC
ph0aohuFU9REfBdbBmU94TrHMKgNA0tWEFzvPzF3rxSUZPEERT+NqCLT4LcZjjMAK3+LS4RexiMF
/uMv9vGNn95ECGEWxOhJ9Q4MaqfO9covfYiq5zwUQIt+xM4gURXOffZeRhZ2Iov1T880+PLbpZ88
FJsprv3Lb3wvsOQVkA+OFCM1ELeQTS12cqhIAba5acmT6TRMPAb9aS+tIVC0Nluwf9CsTesITikF
w9wrSTt9pNSpGtep1+qm96KNf+XfBm2djm+Q1imnQWVW/0Nz+zVZhk/2L3o5dBagocGfFN0pGNGD
+CAV1tHcUgUaxRJUIDBckA61cp+8vhm+Er1OGxq1JjlKZqczsckW3qyxyHppRYCidxQJDerxhLm1
miCpbehvaPrTpdh21DApaIRhIcVu2hFXYSFT6ksAk9N6VZHjl9u0T/NoKE7uuoVZotMixQ15LAqQ
nh+Bff4cVC8UxFfFx+FH9e7RIEsWhUFCDiraeLFsukMgHqSVjCjaPtJrGvRoQA+NfnZBj5AcuM32
1qgLEevAr4/ZbF0nZP/yCzwYmXmQzxvNkbc5BGdoSNyhfalo/C0vzHC8+np2Hoqxl49Ycm/A7N0f
AgZoCP2GzGLKtTlgYtPRN12jhtqzLCZ8GJgU3BNZou4zdz5yOrB8kOypUlkm7BOIkOvq5aFrAY9z
J6Z8NQ5Y1YrGLrx9NhPx/JGNmaSYzpN2tjAXl6NTlljlZu+SgbtqzqMQ30qzvJpYJPnfGaJ5y4cA
vUncUg149IuGa31Cgg+DoturIJZz2fEHEkgfZArk/lN+Jhy8mSLKeXPiEjRfkSzkMvhguSlEkHFN
8c9IhwGv4xZyba/g56GXDNukFzJy3k8+LNMXGnur1RDVOoQnKFefdxd4wPA03cJqQmD7gzXDxWbQ
IWfILXgkwngFUHuKSApWlgjCY+UksdWKfnhmze3HfkS9a4gZvjAlTrsJDVIEfEOXc2lyILogVm5q
o5fwPZV8hdMdfE3RM1U9rxJtFgYpgQcGa2BZ54OBDotSU9/GZFsOgaoBO8fpY7FGWbml+ZlmxB78
Be09AB5E7Px93WMj3qQAmNqrc1N7dsvMYc1MEOHzE0jcj98lvS4d2trJzcG7JFLXPs9dd1Sf/Dsg
dKsitnPlpFTuys0TVt3bwydG9btQHSIZBrZT5qGjn+kkfJt9ny7Z4vgduXaYKrCCCYIsSisQodQ+
r4iuYBpbCq45zahCLEPRdRpCmQlvkbjHQu5ekf8fLzJa679bSGRgsQ8rjfTPoHCq1URp4kTyMtmI
yG3FHg2SSuS3o5NIzEBFwhW2XRT5f7rc7zdW8955u/hsKQx0sLjCboU0bOAn4kN64tPbRnQRABRf
hIVQbu4Tu1aYPZg19LAu4QNooH6zI47HsC3UJXuSOThQRf1vMSqUfFkdfLVVaEvBGOplTkK1j79I
bWKIwa2tW/4FlbsJKLHhi9GIdyu97PCgtAgKSs/HQhctz17NrF34iLXzY91ZmnKWJmyUwK76sCsl
KdF49CdMlQOdtJWT0kC896qdwtY7659F7thgNoe+H/VNl5jks9zIBQCgX+JfdRwFN2Wg+GTwzgFf
SbcT7g/beO8N7jJBwnYElmieVVni1IJ4CfoxT7a8dTezrh8z4chLjL8KO7dUnxqyaAWKB1okUj0A
wScjyc6tTIfnVAPCeb07Wig4We/1ZhpeesKAFxIykg3n1PChVB4m6aRqigf2IyA38HUABnsUmy8T
40q1Xi8S9OABEiVP9BJtCkTWLP7lcQfkqoAKuYNqjzlX7UDWAk+Ev0yADGJhmuaWe0qVmkSAEDpq
gYPAN7i5wkSBk5+k8AqMejcGI0CnWcQKHBIznLLbaDvSh5aHUzqRNXcflsOjOEabQ4BfSEYF7rpE
+ZNRoyK//5j9pBEi2cIhM6ZJhCHeobyZrFVje13rOZ7eDY3Bd/Ov9D6/w7LC7GFIogowQWgV/akw
QBw0eUmvN7NB8jNK4VLD2NLYTmiZDUPCp2SO/JRJbEudR2lu6bXucfwJSbzeV4OFJZDFwi6+yWjN
X2086C/ZBe0ztQqJBJFzjN/rGIamVrrLkxmJ2kYO8Hk2Hq4R8gJ9IoPhNANXJ3E77FzZ+KSZWycI
Vz43SwsfZEEZTHuLV0i7nHbV7PKwLKsNCTP+WvMSe8UlaUd+YyPW13yjl6roZ90AYxhqP5Fit8xq
DaX1Lv7SuUrfu4VpqNJlLLeFEI52cqjkiu2KcBowfE2bEprW2bywK0p1N8o043oOE39XG8uHZpzp
tqWrfI7fwQ+H69WoxYzPAlMu3J3//n8pcWGg+Fm5aKqhu4SL6KNT3R98/bgoHV342Ze6g906+9nx
mAi1DAfzcYEtipPuMlTEu/l/YaLmy9jIapOr6kWZvUHViVdkPZNWg5HjoWfDEGMGC4ePfaGQ8pCr
pY4FT+GRXPuyAlPDlAs/p5JPnV7qXWfXNrmvNJsHxBeKc365zafqiyw700CNQpmbMPHU/8gtgQRj
bDs/EmOlPufDJojPgj/rIxpmGmsRGYHYlzYFWL+U9rQb+DAI5pTJl21IawqzfARvQPOipYau9ECF
o2ssEMEXtEz1G9r61vlnLQs8fNcRn9hRTMysxFT7IC9mqwsGeN1XKG4yv6e3sA6JwZ6lpbY2X1Nj
9AsjlDjThlLmbrEGhJMQA6d6XGCui0koU1Q/msXaOzWAlTx9LWMMzu6ruuFVXSrtxbaJH2XUTV+E
d61gzt13IJm5OHKLlvuSILs7ULQzQPN9ZC9728x+sxj8Rw/BfKg67iQIz0wrvSWCQ+GBOrKAXAOl
7MXHfG7GCGT5swpcd82APTM5Mo17fPRclJAhzh5QocfFwf3sLnDIjZMWggcT8XuEq7+rNniQY5Pg
l3DX0SwXdwPyRkanwNEVrqGGMjnm4pb7lYbgAPaNX2dlXXp47TgmLrcPszrJboneJHvhH5DV/KCS
MVOSn1HDGkW83AsPWrZHLKEelVoz+FDJg0wRuU/1nmrYtKQxYa49yiVqXdO0xdfxfE3gZa748lE5
7SFGWGyDDblp4kFeo+t0QS9nsonyXZfMlSOdrmJyfwDDaRNu2zHsbDmVR1OVqsK4gD3KlJVZgMGk
zTqY6oAj7rwtcKv1C4alWuG5Xgfkl8XhImT7tOk+Ysmo2SmdAOFC5ephylyW+gHuq78g4MAzwvbo
yiT05AGn7zydIYEGuPEEO91pGrywt30Uxqu2jagiepLQtXbzv2iYX0IsGk/klu5NQ3oSRPY5KytX
0kDZsI4gqlZwC2mL0AYlNV7qjghs8zEx95ke8v1VHoLyP6v3qNpY1Y+0jCH2nDhgn6KeuyVB5Wes
xa4Q2eGxo7+2eetGWFNqbyLG6lokyUmpp2FJLNzLcelZd3rmMeRaoEygI0H21ugXLPXiCafDbgM6
iXIJVwYcnd9T6CtAx8W3LmW4hrfisyQLHcwl6IIAxG0ymE3/tDPP6CuJye/mCNAK31kfzW3sNSer
tDh/BciyKC6ZTXm4OakgD8vxwcZhZTUnu04rvCrXKycu9iRbPZMi/pPdVmaN18M/Ibj3+e0nmplS
fensMfLwF8/Ij2o+4G1ZOP8VGWY21pAIEPe/Wf+JShkpHLns66+GlJvacQ6scPH0OBZOfXq6BTj/
40Dxl6bw58vgqYJDcqq/O9bayJEfTnn8of2/rXznmzt4xu2qPkMDwTAQO6qwISthv11Mu4jFh0kf
LVVGBYCk7c8mOfxZMeUt3KsHie1tnacg85yma86AKP49qZx3rr06bOinoMBcX6C3tIQB8S0hvI8z
MGhO7G480r81Es5HvwrVsHJj6UejELJdoBQm9ErLCPa7HsvhKHXn72pu8Y+gFkkHmj2jzyWuYWqN
XuiJBqe228llspDJ4yJbUyDdwrVuP2brvZnORI0C3rwtLfml/ViaavPdecvoNyl3or8HHhrjdtf+
INQrMAuOB7NGWbjnmXEPV7y++0Rz2lAKPzBJvsI0pOl4J5Hb3OzuuyvBODWX3fk3nG05pGO4gJ7j
T4/UCySINi6NiZQdikKtn7lFPFln7TFwXUWf8feeLd73W6JTQrIBgiO9vyzJodHf+HHUcnDrk+6t
ss5MOQCYKM9q5+5r+imPV04fXMwbbgLQGsbZ2iwBdk1zPKjCV5mt75TTFkBvPX0sE39h+vec/7Fq
PBIWkK3oCre9su4uwzjYkpb3Fs+jbiSbUZd2W1jwIqQhMH5fi7czSoASSKciwMmTNzbcn+/u/1gq
O/EAqN6V0RZMaiiT5ytCCmtgsF13KDdHZ5QLzMp3yYZHwB2ErqQbCxf6UyInd5fVDUC7GEJBGel+
jc3PtFXDFXPJFVVPf6E/Jn/1qS0ODe702U2PkLysUXyYIvgSmUTgYGXdaJyjaSVrlh6zyAkyxrJ3
5mlNV9VE1NYmx34jLu+jSljzMjqMP3nj8rRHDZWrIF0RzaRaKhRO2hV4O73pNgKg4yPJb3IELFmY
pHvb7+2MlbvL4pLW5cJcu73dlRWDy4fA8QNpFQeVwXCnpNYfTcA6JumxuBWjislP9M8XhujvQR9X
70oq1TQE98tOj26Ze4RpsYO6DreUV4M11yKSLeuOei7iDss+mu04vFrDdJj5u8PEhTpPSN+nG+QF
VwWWwbaIbf2iMCa91tvm4dX6w1JMv4pmK/fmiXBstprY2D7S5SFbnka6WIOzD3N5FpcawCKEdB/5
rN4NbRWjp+wiQDg8kBKxgv+kv6V4K28LdLB8Gp1Hb3bwJ7HNMpCRkD9CUZlp01WCtTrcAAAAAEQP
/zkv+PxcAAHhUoDgBADOI0l8scRn+wIAAAAABFla"|base64 -d > $TMP/patches.txz

tar xvf $TMP/patches.txz &>/dev/null

patch -p0 -i ./patches/transcode-1.1.7-ffmpeg.patch||exit 1
patch -p0 -i ./patches/transcode-1.1.7-ffmpeg-0.10.patch||exit 1
patch -p1 -i ./patches/transcode-1.1.7-ffmpeg-0.11.patch||exit 1
patch -p1 -i ./patches/transcode-1.1.7-preset-free.patch||exit 1
patch -p0 -i ./patches/transcode-1.1.7-libav-9.patch||exit 1
patch -p1 -i ./patches/transcode-1.1.7-libav-10.patch||exit 1
patch -p1 -i ./patches/transcode-1.1.7-preset-force.patch||exit 1
patch -p1 -i ./patches/transcode-1.1.7-ffmpeg2.patch||exit 1
patch -p1 -i ./patches/transcode-1.1.7-ffmpeg24.patch||exit 1
patch -p1 -i ./patches/transcode-1.1.7-ffmpeg29.patch||exit 1

echo 
echo "$VERDE"Configurando paquete ..."$CIERRE"
sleep 1

CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
LDFLAGS="-L/usr/lib${LIBDIRSUFFIX}" \
./configure \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --sysconfdir=/etc \
  --localstatedir=/var \
  --docdir=/usr/doc/$PRGNAM-$VERSION \
  --mandir=/usr/man \
  --enable-alsa \
  --enable-v4l \
  --enable-libv4l2=yes \
  --enable-libv4lconvert=yes \
  --enable-libmpeg2=yes \
  --enable-libmpeg2convert=yes \
  --enable-ogg \
  --enable-vorbis \
  --enable-theora \
  --enable-x264=yes \
  --enable-xvid=yes \
  --enable-faac=yes \
  --enable-freetype2 \
  --enable-sdl \
  --enable-libxml2 \
  --enable-libdv=yes \
  --enable-libquicktime=yes \
  --enable-mjpegtools=yes \
  --enable-a52=yes \
  --enable-lame=yes \
  --enable-nuv \
  --enable-lzo \
  --enable-libpostproc \
  --enable-imagemagick \
  --build=$ARCH-slackware-linux
  
echo 
echo "$VERDE"Compilando paquete ..."$CIERRE"
sleep 1

make  || exit 1
make DESTDIR=$PKG install || exit 1

# Install headers
mkdir -p $PKG/usr/include/transcode/{aclib,avilib,libtc,libtcaudio,libtcvideo}
install -m 644 src/*.h $PKG/usr/include/transcode/
install -m 644 aclib/*.h $PKG/usr/include/transcode/aclib/
install -m 644 avilib/*.h $PKG/usr/include/transcode/avilib/
install -m 644 libtc/*.h $PKG/usr/include/transcode/libtc/
install -m 644 libtcaudio/*.h $PKG/usr/include/transcode/libtcaudio/
install -m 644 libtcvideo/*.h $PKG/usr/include/transcode/libtcvideo/
install -m 644 config.h $PKG/usr/include/transcode/

# remove filters shipped by other packages
rm -f $PKG/usr/lib$LIBDIRSUFFIX/transcode/filter_{stabilize,transform}.*

# Hay un bug que no respeta el docdir y lo eliminamos a mano
if [ -d $PKG/usr/share/doc ]; then
rm -rf $PKG/usr/share/doc
fi
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del paquete
f_versionInstalada
# Comprobar dependencias
F_dependencias
#Si no existe el fichero se descargara
f_download
#Preparando entorno
f_preparar
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales