#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20161226

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=ffmpeg
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB='http://ffmpeg.org/releases/?C=M;O=A'
	VERSION=`curl -s $WEB/|grep $PRGNAM-3.[0-9]|tail -1|cut -d- -f2|cut -d t -f-1|sed 's/.$//g'`
	EXTENSION=tar.xz
	SOURCES=$PRGNAM-$VERSION.$EXTENSION
	DOWNLOAD=$WEB/$SOURCES
}

# Comprobar dependencias
F_dependencias(){
DEPENDENCIAS="SDL2 soxr libmp4v2 zeromq decklink-sdk libquvi-scripts libquvi libwebp libass libass libaacs libbluray celt libdc1394 faac libfdk-aac frei0r gsm libiec61883 libavc1394 libilbc ladspa_sdk lame libmodplug OpenAL opencore-amr opencv opus rtmpdump schroedinger speex twolame vid.stab x264 x265 xvidcore zvbi"
f_dependencias
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){

CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \

./configure \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --shlibdir=/usr/lib${LIBDIRSUFFIX} \
  --docdir=/usr/doc/${PRGNAM}-${VERSION} \
  --mandir=/usr/man \
  --enable-gpl \
  --enable-version3 \
  --enable-avfilter \
  --enable-avresample \
  --enable-libass \
  --enable-libdc1394 \
  --enable-libgsm \
  --enable-libopencore-amrnb \
  --enable-libopencore-amrwb \
  --enable-libopus \
  --enable-libschroedinger \
  --enable-libspeex \
  --enable-libtheora \
  --enable-libv4l2 \
  --enable-libvorbis \
  --enable-libvpx \
  --enable-libx264 \
  --enable-libx265 \
  --enable-libzvbi \
  --enable-postproc \
  --enable-runtime-cpudetect \
  --enable-vaapi \
  --enable-vdpau \
  --enable-memalign-hack \
  --enable-pthreads \
  --enable-x11grab \
  --enable-bzlib \
  --enable-zlib \
  --enable-shared \
  --enable-static \
  --disable-debug \
  --enable-libmp3lame \
  --enable-libfdk-aac \
  --enable-openssl \
  --enable-nonfree \
  --arch=x86_64 --enable-pic \
  --pkg-config-flags="--static" 
  
  make || exit 1
  make install DESTDIR=$PKG
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del script
f_versionInstalada
#Compronar dependencias
F_dependencias
#Si no existe el fichero se descargara
f_download
#Preparamos entorno
f_preparar
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales