#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20170103

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=libopenshot
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=https://github.com/OpenShot/libopenshot
	VERSION=$(curl -s $WEB/releases|grep tar.gz|head -1|cut -d / -f5|cut -d t -f-1|sed 's/.$//g'|cut -d v -f2)
	EXTENSION=tar.gz
	SOURCES=v$VERSION.$EXTENSION
	DOWNLOAD=$WEB/archive/$SOURCES
}

# Comprobar dependencias
F_dependencias(){
DEPENDENCIAS="libxkbcommon qt5 zeromq ffmpeg python3 unittest-cpp libopenshot-audio"
f_dependencias
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo 
echo "$VERDE"Configurando ..."$CIERRE"
sleep 1

wget -q https://raw.githubusercontent.com/zeromq/cppzmq/014628c/zmq.hpp
cp -p ./zmq.hpp include/

mkdir -p build
cd build
  cmake \
    -DCMAKE_C_FLAGS:STRING="$SLKCFLAGS" \
    -DCMAKE_CXX_FLAGS:STRING="$SLKCFLAGS" \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DLIB_SUFFIX=${LIBDIRSUFFIX} \
    -DZMQ_INCLUDE_DIR=$TMP/$PRGNAM-$VERSION/include \
    -DCMAKE_BUILD_TYPE=Release ..

echo 
echo "$VERDE"Compilando ..."$CIERRE"
sleep 1

  make || exit 1
  make install DESTDIR=$PKG || exit 1
cd ..
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Comprobamos version instalada del paquete
f_versionInstalada
#Compronar dependencias
F_dependencias
#Si no existe el fichero se descargara
f_download
#Preparamos entorno
f_preparar
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales