#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20260808

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=ffmpeg
	SRCNAM=FFmpeg
	EXTENSION=tar.gz
	GESTOR=wget
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=https://github.com/$SRCNAM/$SRCNAM
	VERSION=$(ls /var/log/packages|grep ffmpeg-|cut -d- -f2|grep -v compat)
	SOURCES=n$VERSION.$EXTENSION
	CD=$SRCNAM-n$VERSION
	DOWNLOAD=$WEB/archive/$SOURCES
}

# Comprobar dependencias
F_dependencias(){
DEPENDENCIAS="
AviSynthPlus
ladspa_sdk
libavc1394
libiec61883
libbs2b
gsm
highway
libjxl
onevpl
libmodplug
opencore-amr
portaudio
libopenmpt
rav1e
vamp-plugin-sdk
rubberband
snappy
soxr
srt
svt-av1
vmaf
x264
x265
xvidcore
zeromq
zimg
vapoursynth
"
f_dependencias
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){

echo "/Td6WFoAAATm1rRGBMC8BYAYIQEWAAAAAAAAABMLS9rgC/8CtF0AGGgIRaRUITKFfHexlCj+MSEj
enCC8OSAUBOpIhqj0c11Mj7LzWbYJPk85jkME9w/U4r7Usc+ranu71IjTWX5Wt+A58z2IBBXMYTM
h6QYqKXpaiA21RCXcrv+SbsFWly69VroEzjkZxRWldd4Hg4xoulYc9SajEcQMkUgENWS4AT/bcO1
LzwfHZrWXG15/3kG2cL9saBCs1uSnYhZJLKrqb070gj2okBQ23Sqf1D7MjU//LkyndkW/yvvjGhg
se79LluffTJJ3vEHbu3PxyfwJtgYK8JfWF//4dVZBpWoM0jfpkNuMui0BeQu2WFum+r3pO0PjNO/
7NSg7roO0Cpl+ZcAIE4LfQ/CRvGM48lNwAtFNdsErT+Q9ur8zMvVpDR3JdpnjWsoVxxtRI0Q0zW5
Ci7q/KTEciSAP84zSwTdy2x5mnCXy/Ge+QuGjvTZMEIFMO3zqwEs/tKcJJtcYm/FjJZyoMHn1UcL
psAoA2+vcgIkjtqvZdGbP+C7HWcXl6fTa7VkYh3WEBaSVbaEYoy4Xt7Au1ZoVTJJb9Ah6GMa1FDl
SjavatXRDCxcNk4Dwvt1jnWaXkGMOVJrDTE/86yas/B31A4V/xjs8cjYq73qMPDedxfCmlz9mwgF
JIGU3tFjDW6YoKTBSa0YWfZu7z8ouVrQgKtql2LuEVHAGyOrIUA8BeWP8pNZ0tf+Rgg4K3MWn3tj
Oah/UYkvReA0kwLATSvf/zi7y1W9Dkl885HQvWSw10Y9C9ZPNPz7otFf97EPUkn9SoMnAueJtQqo
84HSky6fYC3YLLuEUbo/QrSjkLF+JrZ8pCB56/d0pNAlymghD4HSAd3W+Knu7fUKbvGFAg9k/4u0
1zLt+DC6GjRTeqXBpcdEqlSvqeky+qk0EKz7ffBQcFzukXm4iT10HTssnY1uqAAA5Xetz1XPdt4A
AdgFgBgAAByBtAqxxGf7AgAAAAAEWVo="|base64 -d > $TMP/patches.txz

tar xvf $TMP/patches.txz &>/dev/null
patch -p1 < ./0001-Add-av_stream_get_first_dts-for-Chromium.patch||exit 1

echo 
echo "$VERDE"Configurando ..."$CIERRE"
sleep 1

CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./configure \
    --prefix=/usr \
    --libdir=/usr/lib${LIBDIRSUFFIX} \
    --shlibdir=/usr/lib${LIBDIRSUFFIX} \
    --disable-doc \
    --disable-htmlpages \
    --disable-manpages \
    --disable-podpages \
    --disable-txtpages \
    --disable-debug \
    --disable-static \
    --disable-stripping \
    --enable-amf \
    --enable-avisynth \
    --enable-lto \
    --enable-fontconfig \
    --enable-frei0r \
    --enable-gmp \
    --enable-gnutls \
    --enable-gpl \
    --enable-ladspa \
    --enable-lcms2 \
    --enable-libaom \
    --enable-libass \
    --enable-libbluray \
    --enable-libbs2b \
    --enable-libdav1d \
    --enable-libdrm \
    --enable-libdvdnav \
    --enable-libdvdread \
    --enable-libfreetype \
    --enable-libfribidi \
    --enable-libgsm \
    --enable-libharfbuzz \
    --enable-libiec61883 \
    --enable-libjack \
    --enable-libjxl \
    --enable-libmodplug \
    --enable-libmp3lame \
    --enable-libopencore_amrnb \
    --enable-libopencore_amrwb \
    --enable-libopenjpeg \
    --enable-libopenmpt \
    --enable-libopus \
    --enable-libplacebo \
    --enable-libpulse \
    --enable-librav1e \
    --enable-librsvg \
    --enable-librubberband \
    --enable-libsnappy \
    --enable-libsoxr \
    --enable-libspeex \
    --enable-libsrt \
    --enable-libssh \
    --enable-libsvtav1 \
    --enable-libtheora \
    --enable-libv4l2 \
    --enable-libvidstab \
    --enable-libvmaf \
    --enable-libvorbis \
    --enable-libvpl \
    --enable-libvpx \
    --enable-libwebp \
    --enable-libx264 \
    --enable-libx265 \
    --enable-libxcb \
    --enable-libxml2 \
    --enable-libxvid \
    --enable-libzmq \
    --enable-nvdec \
    --enable-nvenc \
    --enable-opencl \
    --enable-opengl \
    --enable-shared \
    --enable-vapoursynth \
    --enable-version3 \
    --enable-vulkan \
    --disable-decoder=magicyuv
  
make || exit 1
make install DESTDIR=$PKG
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del script
f_versionInstalada
#Compronar dependencias
F_dependencias
#Si no existe el fichero se descargara
f_download
#Descomprimir sources
f_descomprimir
#Cd a ruta
f_cd
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales