#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20181122

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=wine-gecko
	SRCNAM=wine_gecko
	EXTENSION=msi
	GESTOR=wget
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=http://dl.winehq.org/wine/$PRGNAM
	VERSION=$(curl -s $WEB/|egrep -o ">[0-9].[0-9]{1,2}/"|tr -d '>/'|tail -1)
	SOURCES=$SRCNAM-$VERSION-$ARCH.$EXTENSION
	DOWNLOAD=$WEB/$VERSION/$SOURCES
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){           
echo "Incluyendo version x86 ..."
wget -N -L -c -q --show-progress $WEB/$VERSION/$SRCNAM-$VERSION-x86.$EXTENSION
mkdir -p $PKG/usr/share/wine/gecko
mv -f *.$EXTENSION $PKG/usr/share/wine/gecko
chmod 777 $PKG/usr/share/wine/gecko/*
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Comprobamos version instalada del paquete
f_versionInstalada
#Si no existe el fichero se descargara
f_download
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales