#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20180421

############################################################
## Funciones comunes. Su nombre empieza por f_            ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=pokerth
	EXTENSION=tar.gz
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=https://sourceforge.net/projects/$PRGNAM/files/$PRGNAM/
	VERSION=$(curl -s $WEB|grep $EXTENSION|head -1|rev|cut -d / -f-1|rev|cut -d- -f2|cut -d t -f-1|sed 's/.$//g')
	SOURCES=$PRGNAM-$VERSION.$EXTENSION
	CD=$PRGNAM-$VERSION-rc
	DOWNLOAD=$WEB/$VERSION/$SOURCES
}

# Comprobar dependencias
F_dependencias(){
DEPENDENCIAS="libgsasl tinyxml six python-dateutil google-apputils python-gflags pytz protobuf"
f_dependencias
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo ""
echo "$VERDE"Compilamos ..."$CIERRE"
sleep 1

echo "/Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj4BX/BNBdADgbyak/YlYooqp2gsOrAA0GqnpCckD/Nr+K
FVUe79uG2u9pvNxzI8+TB725uKIuVfKWczRssbTHOZQKMWsjPcsHzGvnx9HxdxI8rwi07MSy6QMt
uEBrNsImNHZ7oiMOyQWs6btecXaltdLoM/3WNEQJfl8MjE5PgV78/f7/pnjMI/9J8Ad4Z7/vTItX
S8mfgK9NpGu0+ShDTOkBTjhDP3Xwy1WJmlpHcNUrePoIkkgwjVOP/v8WKyFnb6W7NDMy0zY9sKfU
oLikJrSQRiqOxGsxQnDtpeYLXqNPcR/k/BS1B91L5Z0DxXYyiifOmLo3Z5YMPNaOG0qKPCf0/3uL
fxXXW6Mv00bjHWWEIhJo3i5l7uTBfOb9I7MFlHOinlAQZ29RC8Ka0inGcFTIatloreIvu91nwNus
u3eryapgUuswwtuXFIta4UV/yqbMYeQAM5O37UH38YQhiRd7UTKICX4SSwAoUfwbbtGSdJ27rUF5
E5bk7MUM1PtECGZ8p+qjaKWL6/5cv74LpaAIGZSKVXibrn4ccd/9UjkVPza96q/fN3E7eG7LPjcA
YnaCqSKTKu2WgjknmQJ/nHZao1Z1mNhtfIBfk1BwV6SyP2JIAh0Nu7kE++200cgWx2L5d0S9xs5t
/8tPlr+IQ+iJM2sPxBfWSqOCNi7xzrO25LChIovLz0YxIweegNDUxGbXUCzc1hgKhc1qb2KXyRVl
2iuM/DywDbtQqh3zzxk7PVBhWxFlrXaldigeW7obWjaee1vJfT5VNyJ4qkskbYQK9uURryAQaRu1
V+WAOcCvA0ua9xHsUaXxrdCFMaTH+s+NUF81FL3qoBA0w4ffqUgmCn7dZa80bDArYUhyPTYYgRen
PaOyeUF41eBiQ227X6V4lOQxax4ujTOshS50VeHkUrp582oL8XnLX2qIqELKdEBmMyameGihZWo8
YGBgDbonfqegzk/4mBrrFaaWwYNJuGzclQ++tQzPmQUE9K0qQlQWi1flXQZV0W2FSJbKQMuSYrfs
iHZ5H5KUay1agxEJPylt2/ih8Xcn3Bf9CtKbG3jK7Yaq7cnOiMxbAbVePYeZ1ZXY8rNrTmm/x5cc
3kf0Pa7pQuHW6j10Dkm1eCXgL3u/tioH/klaHUkEeX/UbOUe/sXdWNGFNLBKJIVNtcYKbOk/pnyk
3ckJmWvEvmBzFurt3byaK7fsNKPOYzXdn/2Noepc5KUQUhoMA446DVojzCGgUGESEZoEcTUkQz9T
3x0LSfY3D9/bU2uoKQOJQTVxhq0tK8H1D747d+Tfbh4+mrSanPO5QCJZtXJWKp1qssni08Obg9jx
nW7EK3r1Xk/BRVWmK23wujXXUmlAIpp24VQwoEIAmHriMbsP6b8Fz6B+lWuOdg8rGqBVgGr783IY
q/uRuDohBxmHpubpXXirdYlyOp6sIppbjaNlUagRCpouK6dA1tcHIuz4LDq0TiewGkdWbdqW6vvt
PMakMlJIgQTM9RoMdoXv5/SJuEmOLj1T63331NCySOhWxSTg6F5qaPZMXFBF9ND0vbbn4zQ/tkaw
+3gSs1hSCv3zf9t2G5Vdop79+SQZp4NE1xy+VMIZdXoTJPBJo1gOrFj8G/aZYdse+YzmyBsuLsWF
iVYVwQby544AAL+8kPY6oj/qAAHsCYAsAADqZM1zscRn+wIAAAAABFla"|base64 -d > $TMP/patches.txz

tar xvf $TMP/patches.txz -C $TMP
patch -Np1 -i "$TMP/pokerth-1.1.2.patch"||exit 1

protoc -I=$TMP/$CD/ --cpp_out=$TMP/$CD/src/third_party/protobuf/ $TMP/$CD/pokerth.proto $TMP/$CD/chatcleaner.proto

qmake CONFIG+="client" QMAKE_CFLAGS_ISYSTEM= -spec linux-g++ $PRGNAM.pro

make||exit 1
make INSTALL_ROOT="$PKG" install

install -D pokerth "$PKG/usr/bin/pokerth"
install -D -m644 docs/pokerth.1 "$PKG/usr/share/man/man1/pokerth.1"
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del script
f_versionInstalada
# Comprobar dependencias
F_dependencias
#Si no existe el fichero se descargara
f_download
#Preparamos entorno
f_preparar
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales