#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20250407

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=aircrack-ng
	EXTENSION=tar.gz
	GESTOR=wget
	echo -e "\033]2;${PRGNAM}_updater\007"
	WEB=https://www.aircrack-ng.org
	VERSION=$(curl -s $WEB/|grep Sources|grep $EXTENSION|cut -d- -f4|cut -d t -f-1|sed 's/.$//g')
	SOURCES=$PRGNAM-$VERSION.$EXTENSION
	CD=$PRGNAM-$VERSION
	DOWNLOAD=https://download.aircrack-ng.org/$SOURCES
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo -e "\n${VERDE}Configurando ...${RESET}"
sleep 1

autoreconf -fiv

LDFLAGS="-L/usr/lib${LIBDIRSUFFIX}" \
CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
PYTHON="/usr/bin/python3" \
./configure \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --sbindir=/usr/bin \
  --sysconfdir=/etc \
  --localstatedir=/var \
  --mandir=/usr/man \
  --docdir=/usr/doc/$PRGNAM-$VERSION \
  --with-experimental \
  --with-ext-scripts \
  --build=$ARCH-slackware-linux

echo -e "\n${VERDE}Compilando ...${RESET}"
sleep 1

make DESTDIR=$PKG install

# Creamos el fichero oui
echo -e "\n${VERDE}Actualizando aircrack oui.list ....${AMARILLO}"
cp -rf $PKG/usr/bin/airodump-ng-oui-update /usr/bin
airodump-ng-oui-update
mkdir -p $PKG/etc/aircrack-ng/
cp /etc/aircrack-ng/airodump-ng-oui.txt $PKG/etc/aircrack-ng/airodump-ng-oui.txt
echo -e "${RESET}"
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Comprobamos version instalada del paquete
f_versionInstalada
#Si no existe el fichero se descargara
f_download
#Descomprimir sources
f_descomprimir
#Cd a ruta
f_cd
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales