#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20250407

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=ipscan
	EXTENSION=jar
	GESTOR=wget
	echo -e "\033]2;${PRGNAM}_updater\007"
	WEB=https://github.com/angryip/$PRGNAM
	VERSION=$(curl -s $WEB/tags|grep .tar.gz|head -1|cut -d / -f7|cut -dt -f1|sed 's/.$//g')
	SOURCES=ipscan-linux${LIBDIRSUFFIX}-$VERSION.$EXTENSION
	DOWNLOAD=$WEB/releases/download/$VERSION/$SOURCES
}

#Comprobar dependencias
F_dependencias() {
DEPENDENCIAS="jdk"
f_dependencias
}


# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo -e "\n${VERDE}Empaquetando ...${RESET}"
mkdir -p $PKG/usr/lib${LIBDIRSUFFIX}/ipscan/
mv -f $SOURCES $PKG/usr/lib${LIBDIRSUFFIX}/$PRGNAM/$PRGNAM.$EXTENSION
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Comprobamos version instalada del paquete
f_versionInstalada
#Comprobar dependencias
F_dependencias
#Si no existe el fichero se descargara
f_download
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales