#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20250407

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=wireshark
	EXTENSION=tar.xz
	GESTOR=wget
	echo -e "\033]2;${PRGNAM}_updater\007"
	WEB=https://www.wireshark.org
	VERSION=$(lynx -dump -width=256 $WEB/download.html|grep $EXTENSION|head -1|cut -d- -f2|cut -dt -f1|sed 's/.$//g')
	SOURCES=$PRGNAM-$VERSION.$EXTENSION
	CD=$PRGNAM-$VERSION
	DOWNLOAD=https://1.eu.dl.wireshark.org/src/$SOURCES
}

# Comprobar dependencias
F_dependencias(){
DEPENDENCIAS="
libmaxminddb
libsmi
snappy
libminizip
libilbc
opencore-amr
spandsp
"
f_dependencias
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){

if [ $VERSION = 4.4.1 ] ; then
echo "
/Td6WFoAAATm1rRGAgAhARwAAAAQz1jM4A3/Am1dADgYSu7FL5n6pvg745dpgzgztyjlznaup/J3
K7y7ObJX2/8T/aZsBr1OtsBenOUeFG9pS/Dx/Jtz0BVu17uiP9tgP1XebQiLtGzN7IZJlipLDxXZ
pdqfZqhwSl3XYYyGkufBD0wn/OIvYqtKlcag1ZRab853fwCbxP5D0GR592qMPmF/0Ra9+U3BTVGe
rFThlVpB2d1j540rXWg4yVHRjZ63rn8Nal1eLHvf5Dfp8SXoYwBtJKA6JVBU/vY2+4mrFg425bAq
uQiEHy5Hn6hMexL5BQjryivqP1CQnjuLxToqSrNxVz7/I2m6XqE3ybyRor/BkzbAs+dP8PcZ55MN
o4QmCPNBNsTospSNVJiXpG5+y0+xgw9pBjBvO0gXm0bj84NTF9rm4i8LvKlyCrx3pBPvY6V7o+gz
QQQ8UCbrhnDCyu5bXCzTP/TMCsfCRZRVTSv8PCxvAZpcBmEL2Xkp30lN5mXzlyJJ8Uoc52WXp0Jn
75hDxs4n92BH7elBx/Yryii0E1Sl8yIY2Xt3sJVHt+t7XYdXq3sD81cS9Nbp4Xr2mVi9IcYJsThB
sICM3jC9uirXMnhc0SVMpOjK0AfotwslMbPk3w8U3dmSI4JGcnMHKU7/46n3oY8obz+saBbVCEA3
hp2/vrIkWnd+7PzAu2BA1ZQFmW26z9HI1OMPo8weE0U2bjAytBCVt2O+7UyX7w0M55kOOMnBONdH
MHit5IK0jIyRdLQ31z1OzS+6rM+MB0RLsV1vyRi4PjkJhrImM6vRwcH12SUqWoXXnHuN3MFV/HSj
Yye8uQF9HyG64lQPLy96xAHcGN1tQAGhAAAAAABUOsPzIxWIUwABiQWAHAAAkvJvyrHEZ/sCAAAA
AARZWg=="|base64 -d > $TMP/patches.txz
tar xvf $TMP/patches.txz &>/dev/null
patch -p1 < ./patches/cares.patch || exit 1
fi

echo -e "\n${VERDE}Configurando ...${RESET}"
sleep 1
mkdir -p build
cd build
  cmake \
    -DCMAKE_C_FLAGS:STRING="$SLKCFLAGS" \
    -DCMAKE_CXX_FLAGS:STRING="$SLKCFLAGS" \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_MANDIR=/usr/man \
    -DCMAKE_INSTALL_DOCDIR=/usr/doc \
    -DCMAKE_INSTALL_LIBDIR=lib${LIBDIRSUFFIX} \
    -DCMAKE_INSTALL_RPATH= \
    -DCMAKE_SKIP_RPATH=ON \
    -Wno-dev \
    -DCMAKE_BUILD_TYPE=None ..
    
# Compilamos
echo -e "\n${VERDE}Compilando ...${RESET}"
sleep 1
make || exit 1
make install DESTDIR=$PKG || exit 1

# Creamos una config basica
CONFIG=$PKG/$HOME/.$PRGNAM
mkdir -p $CONFIG

echo "# Main window maximized.
# TRUE or FALSE (case-insensitive).
gui.geometry_main_maximized: TRUE
# Warn if running with elevated permissions (e.g. as root).
# TRUE or FALSE (case-insensitive).
privs.warn_if_elevated: FALSE" > $CONFIG/recent
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del script
f_versionInstalada
# Comprobar dependencias
F_dependencias
#Si no existe el fichero se descargara
f_download
#Descomprimir sources
f_descomprimir
#Cd a ruta
f_cd
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales