#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20201226

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=yersinia
	EXTENSION=tar.gz
	GESTOR=wget
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=https://github.com/tomac/$PRGNAM
	VERSION=$(curl -s $WEB/releases|grep $EXTENSION|head -1|cut -d v -f3|cut -d t -f-1|sed 's/.$//g')
	SOURCES=v$VERSION.$EXTENSION
	CD=$PRGNAM-$VERSION
	DOWNLOAD=$WEB/archive/$SOURCES
}

# Comprobar dependencias
F_dependencias(){
DEPENDENCIAS="libnet"
f_dependencias
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo "
/Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj4Bv/BStdADgYSu7FL5n6pvg745dpgzgztyjlznaup/JO
/bHvZT2KSqqnhNpNAKpnoHm8Dp+9thtxwi10HmxA0/qK8f0L7xfWaq2oXa1bHg4OyIlw26eThvWt
xkilNjzz27l91SaJQKKHbr8M3vNyl4w4X+f92z8/begXdUqGvr7nDhUbYGMuV7QPKkMph6V5UiZR
qURpqeneAgsw7iBHmONpCAftAfsu5gTIV6TLjrqCMhjAIQYKr8EvjygfNcS3AahH/sTUrgWToQoQ
AIkjxG+EJR2kMokbVnHYBumL69dDr0USdK/7SLg9sk+GxFbvizzHj8/rZzsnlvAyVxfVWqzoFcUC
ImssvMMe/cPDug1A9BGq/R115yEf0ZsDuZ5wIFo8Rx+oqITtXfXm8PSMsfx1k52iLfXvzh1qUdwa
l5hwVStswg3VdRFLB91H1w+algb+dO8pQ6z7zzUYqsXrETty71po3AX7WCD1oj5HjuTR3ch/aFeA
CWGg7PG93Cwj7aHLWkpi6fhB/s5kE6MnXoHBrM/WoB2hBrRypPg2RbCHgCwRgLgHW2rmpvqMIgVf
uAaMMNMCNAcnUaxblYaaoSz6KUQTTD5kB367GrEjkkXrGgTVqdyX5zsRfGVxmZFSv503APBHsTNK
bLklLLYCTuvIQoSdQnOdc070Si0fz/7GOqqL93+C1U+J9a4KHMAv1m2Cx/uZulL1KxscwFmTRhIY
p2dVaoty9LgI77rWmHUhg8pfjX/HMfWg0dAJ8Vss9yesU4rAg0IdFBy3rPHnpl3tsdxw5h9QrKvc
xl1XBPNvksCF7RjAZUq0kMjWipZfMPIdxfetLgDUFUfbm7yy670gbuWvknejpahkNqFoXi/03cug
wNsjGoeumYB4WqfkIOuumjvDeluX1X5wlkYBVCQbdxtSFqLEZ6QH04ybpLN4xYmCQqJ6hoL5hwlg
UUzUNr1m7RYlmVJ3dy5Teexg4KJ08kR42q1I/gcOH4ydLRkkOASk9Yn+IJq1qATZc6T/Bd/Qq3gc
y3/RGMislxjEcii77sZ4Z+2ds155QtTKHrzFcMe1pGxb6ITZSyBT2trOmHLylSPQwOjGqLsOQL2H
kFPz1iCLMtNd9obSGSgai4kLIjGvZCmadile840LDaaV3lFlmmARznxHxVjMSEgrSH3h9Q8aypAH
P7H7jc5l4yiLLgK8owQgtN0vDrua5FTDdRmJVN4uvBrQcB5zXzjSuENUMN62TYZJwd1GqH9luHS3
JC9KHqD3erOeKcWn+2eqODzMd6Hwqyyp2XWNsoPcs7MVoJkNH6UqSKqzekkFigPiOo9N8x9VnhRt
fDTvk335BlanQv+zOWnNfJ/BmGAdii1+nhcaDh2ytfPW3ydtRgrI7wA8MIBWBSAVKsAIv+mh4qBh
LpMl9F9/l+5l0Ght/VnT53R5rFqnuwgE04Ml6QAjnWiCmpw0ZUS/dPBFOw0TllSURkzhenLMMkc4
GwitMNvqfDr3eyXKschEpHwGqHX25Cwx+sk3MCBXqTjMkIhaTj2Eu7A4atRA5td0zdOo1dsTopBj
D9CTlMfjiGVd2fpLKRtpTQcivrV++UUsaupxdt4OdQaXMrWVcK1Ex7hbUusNN5PvlV8JDCnP8BQN
ciHHx9v8n7AJvqlTSYL0jcLBW18ML+2W6/dWpPDN03MgvnkFZCm698/iCDgi/j5YboQ1WvWFZUnB
fJIByrUjE3ECcUJcWMds+vkaQnKx8gvs5gDsWI+IC2T30aE3hawWYLeIAAAAbMiGmB45gmIAAccK
gDgAAGPgKUKxxGf7AgAAAAAEWVo="|base64 -d > $TMP/patches.txz

tar xvf $TMP/patches.txz &>/dev/null

patch -p1 -i ./patches/yersinia_reproducible.patch || exit 1
patch -p1 -i ./patches/gcc10.patch || exit 1


LDFLAGS="$SLKLDFLAGS" \
CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./autogen.sh --prefix=/usr
make || exit 1
make DESTDIR=$PKG install-strip || exit 1
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del paquete
f_versionInstalada
# Comprobar dependencias
F_dependencias
#Si no existe el fichero se descargara
f_download
#Descomprimir sources
f_descomprimir
#Cd a ruta
f_cd
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales
