#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20230115

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=rtl8192eu
	SRCNAM=$PRGNAM-linux
	GESTOR=git
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=https://github.com/clnhub/$SRCNAM
	VERSION="5.11.2.1_$(lynx -dump -width=256 $WEB/commits|grep commit/|head -1|cut -d/ -f7|cut -c 1-7)"
	SOURCES=$SRCNAM
	CD=$SRCNAM
	DOWNLOAD=$WEB
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo 
echo "$VERDE"Compilando ..."$CIERRE"
make||exit 1
mkdir -p $PKG/lib/modules/$(uname -r)/kernel/drivers/net/wireless/
make install MODDESTDIR=$PKG/lib/modules/$(uname -r)/kernel/drivers/net/wireless/
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Comprobamos version instalada del paquete
f_versionInstalada
#Si no existe el fichero se descargara
f_download
#Cd a ruta
f_cd
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales