#!/bin/bash

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20170602

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=firmwares
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB="https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git"
	VERSION="$(curl -s $WEB|grep master|grep -o [0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]|head -1|sed 's/-//g')"
}

# Descarga los firmwares mas nuevos disponibles
F_descargar() {
echo ""
echo "$VERDE"Se procede a descargar los firmwares desde kernel.org"$CIERRE"
echo "$AMARILLO"
git clone "$WEB"
echo "$CIERRE"
}

# Creamos directorios , eliminamos sobrantes .git y movemos
F_compilar(){
echo 
echo "$VERDE"Compilando ..."$CIERRE"
sleep 1
cd $TMP/linux-firmware
make DESTDIR=$PKG FIRMWAREDIR=/lib/firmware install
rm $PKG/lib/firmware/{Makefile,README,configure,GPL-3}
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura noarch
#Comprobamos version instalada del script
f_versionInstalada
#Descarga los firmwares mas nuevos disponibles
F_descargar
#Descomprimir fichero descargado y compilamos
F_compilar
#Creamos xzm , instalamos y salimos
f_tareasFinales