#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20181221

#################################################
## Funciones comunes. Su nombre empieza por f_ ##
#################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables(){
	PRGNAM=wine
	EXTENSION=txz
	GESTOR=wget
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=https://sourceforge.net/projects/wine/files/Slackware%20Packages
	RAMA=$(curl -s $WEB/|grep -v rc|grep -m1 Packages/[0-9]|cut -d / -f 6)
	VERSION=$(echo $RAMA|sed 's/-/./g')
	SOURCES=$(curl -s $WEB/$RAMA/$ARCH/|grep -m1 .$EXTENSION|cut -d '"' -f2)
	DOWNLOAD=$WEB/$VERSION/$ARCH/$SOURCES
}

# Comprobar dependencias
F_dependencias(){
DEPENDENCIAS="wine-gecko wine-mono"
f_dependencias
}

# Tareas de conversion de formato
F_compilar(){
echo ""
echo "$VERDE"
ROOT=$PKG installpkg $SOURCES
rm $PKG/var/log/packages/wine*

# Creamos estructura de menu
mkdir -p $PKG/etc/xdg/menus/applications-merged
echo '<!DOCTYPE Menu PUBLIC "-//freedesktop//DTD Menu 1.0//EN"
"http://www.freedesktop.org/standards/menu-spec/menu-1.0.dtd">
<Menu>
  <Name>Applications</Name>
  <Menu>
    <Name>wine-wine</Name>
    <Directory>wine-wine.directory</Directory>
    <Include>
      <Category>Wine</Category>
    </Include>
  </Menu>
</Menu>' > $PKG/etc/xdg/menus/applications-merged/wine.menu

mkdir -p $PKG/usr/share/desktop-directories/
echo "[Desktop Entry]
Icon=winecfg
Name=Wine
Type=Directory" > $PKG/usr/share/desktop-directories/wine-wine.directory

# Creamos iconos extras
convert $PKG/usr/share/pixmaps/winecfg.png -scale 64 $PKG/usr/share/pixmaps/winecfg.png
convert $PKG/usr/share/pixmaps/winecfg.png -scale 64 $PKG/usr/share/pixmaps/folder-wine.png
convert $PKG/usr/share/pixmaps/winecfg.png -scale 64 $PKG/usr/share/pixmaps/wine-uninstaller.png

# El desktop winecfg viene mal ..se repara
rm $PKG/usr/share/applications/winecfg.desktop
echo "[Desktop Entry]
Exec=winecfg
Icon=winecfg
Terminal=false
Name=Wine Configuration
Comment=Configure Wine
Type=Application
Categories=Wine;
" > $PKG/usr/share/applications/winecfg.desktop

# Incluimos unisnstaller
echo "[Desktop Entry]
Name=Uninstall Wine Software
Comment=Uninstall Windows applications for Wine
Exec=wine uninstaller
Terminal=false
Type=Application
Icon=wine-uninstaller
Categories=Wine;
" > $PKG/usr/share/applications/wine-uninstaller.desktop

# Incluimos explorador c
echo "[Desktop Entry]
Name=Browse C: Drive
Comment=Browse your virtual C: drive
Exec=wine winebrowser c:
Terminal=false
Type=Application
Icon=folder-wine
Categories=Wine;
" > $PKG/usr/share/applications/wine-browsedrive.desktop
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Asignamos o detectamos arquitectura
f_arquitectura
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Comprobamos version instalada del script
f_versionInstalada
# Comprobar dependencias
F_dependencias
#Si no existe el fichero se descargara
f_download
#Descomprimir fichero descargado y compilamos
F_compilar
#Creamos xzm , instalamos y salimos
f_tareasFinales