#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20170726

#################################################
## Funciones comunes. Su nombre empieza por f_ ##
#################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables(){
	PRGNAM=wine
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=https://sourceforge.net/projects/wine/files/Slackware%20Packages/
	RAMA=$(curl -s $WEB|grep -m1 "class=\"folder"|awk '{print $2}'|cut -d "\"" -f 2)
	VERSION=$(echo $RAMA|sed 's/-/./g')
	GECKO_WEB=http://dl.winehq.org/wine/wine-gecko
	GECKO_VERSION=$(curl -s $GECKO_WEB/|egrep -o ">[0-9].[0-9]{1,2}/"|tr -d '>/'|tail -1)
	MONO_WEB=https://dl.winehq.org/wine/wine-mono
	MONO_VERSION=$(curl -s $MONO_WEB/|egrep -o ">[0-9].[0-9]{1,2}.[0-9]{1,2}/"|tr -d '>/'|tail -1)
	WINEPKG=$(curl -s $WEB/$RAMA/$ARCH/|grep -m1 .txz|cut -d '"' -f2)
}

# Si el paquete no existe se descargara de internet
F_download(){
	DESCARGAR="wget -N -L -c -q --show-progress"
	if [ ! -f $WINEPKG ]; then
	echo ""
	echo "$CYAN"Descargando sources de $PRGNAM-$VERSION"$CIERRE"
	sleep 1
	$DESCARGAR ${WEB}$RAMA/$ARCH/$WINEPKG
	fi
# Si gecko no existe se descargara de internet
	if [ ! -f ${PRGNAM}_gecko-$GECKO_VERSIO-$ARCH.msi ]; then
	echo ""
	echo "$CYAN"Descargando plugin ${PRGNAM}_gecko-$GECKO_VERSION-$ARCH.msi"$CIERRE"
	sleep 1
	$DESCARGAR $GECKO_WEB/$GECKO_VERSION/${PRGNAM}_gecko-$GECKO_VERSION-$ARCH.msi
	fi
	if [ ! -f ${PRGNAM}_gecko-$GECKO_VERSIO-x86.msi ]; then
	echo ""
	echo "$CYAN"Descargando plugin ${PRGNAM}_gecko-$GECKO_VERSION-x86.msi"$CIERRE"
	sleep 1
	$DESCARGAR $GECKO_WEB/$GECKO_VERSION/${PRGNAM}_gecko-$GECKO_VERSION-x86.msi
	fi
# Si mono no existe se descargara de internet
	if [ ! -f ${PRGNAM}-mono-$MONO_VERSION.msi ]; then
	echo ""
	echo "$CYAN"Descargando plugin ${PRGNAM}-mono-$MONO_VERSION.msi"$CIERRE"
	sleep 1
	$DESCARGAR $MONO_WEB/$MONO_VERSION/${PRGNAM}-mono-$MONO_VERSION.msi
fi
}

# Tareas de conversion de formato
F_compilar(){
echo ""
echo "$VERDE"
txz2dir $WINEPKG $PKG
mkdir $PKG/usr/share/wine/gecko $PKG/usr/share/wine/mono
mv ${PRGNAM}_gecko-$GECKO_VERSION-$ARCH.msi $PKG/usr/share/wine/gecko
chmod 777 $PKG/usr/share/wine/gecko/${PRGNAM}_gecko-$GECKO_VERSION-$ARCH.msi
mv ${PRGNAM}_gecko-$GECKO_VERSION-x86.msi $PKG/usr/share/wine/gecko
chmod 777 $PKG/usr/share/wine/gecko/${PRGNAM}_gecko-$GECKO_VERSION-x86.msi
mv ${PRGNAM}-mono-$MONO_VERSION.msi $PKG/usr/share/wine/mono
chmod 777 $PKG/usr/share/wine/mono/${PRGNAM}-mono-$MONO_VERSION.msi
rm $PKG/var/log/packages/wine*

# Creamos estructura de menu
mkdir -p $PKG/etc/xdg/menus/applications-merged
echo '<!DOCTYPE Menu PUBLIC "-//freedesktop//DTD Menu 1.0//EN"
"http://www.freedesktop.org/standards/menu-spec/menu-1.0.dtd">
<Menu>
  <Name>Applications</Name>
  <Menu>
    <Name>wine-wine</Name>
    <Directory>wine-wine.directory</Directory>
    <Include>
      <Category>Wine</Category>
    </Include>
  </Menu>
</Menu>' > $PKG/etc/xdg/menus/applications-merged/wine.menu

mkdir -p $PKG/usr/share/desktop-directories/
echo "[Desktop Entry]
Icon=winecfg
Name=Wine
Type=Directory" > $PKG/usr/share/desktop-directories/wine-wine.directory

# Creamos iconos extras
convert $PKG/usr/share/pixmaps/winecfg.png -scale 64 $PKG/usr/share/pixmaps/winecfg.png
convert $PKG/usr/share/pixmaps/winecfg.png -scale 64 $PKG/usr/share/pixmaps/folder-wine.png
convert $PKG/usr/share/pixmaps/winecfg.png -scale 64 $PKG/usr/share/pixmaps/wine-uninstaller.png

# El desktop winecfg viene mal ..se repara
rm $PKG/usr/share/applications/winecfg.desktop
echo "[Desktop Entry]
Exec=winecfg
Icon=winecfg
Terminal=false
Name=Wine Configuration
Comment=Configure Wine
Type=Application
Categories=Wine;
" > $PKG/usr/share/applications/winecfg.desktop

# Incluimos unisnstaller
echo "[Desktop Entry]
Name=Uninstall Wine Software
Comment=Uninstall Windows applications for Wine
Exec=wine uninstaller
Terminal=false
Type=Application
Icon=wine-uninstaller
Categories=Wine;
" > $PKG/usr/share/applications/wine-uninstaller.desktop

# Incluimos explorador c
echo "[Desktop Entry]
Name=Browse C: Drive
Comment=Browse your virtual C: drive
Exec=wine winebrowser c:
Terminal=false
Type=Application
Icon=folder-wine
Categories=Wine;
" > $PKG/usr/share/applications/wine-browsedrive.desktop
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Asignamos o detectamos arquitectura
f_arquitectura
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Comprobamos version instalada del script
f_versionInstalada
#Si no existe el fichero se descargara
F_download
#Descomprimir fichero descargado y compilamos
F_compilar
#Creamos xzm , instalamos y salimos
f_tareasFinales