#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20200801

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=jdk
	EXTENSION=tar.gz
	GESTOR=wget
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=https://www.oracle.com/java/technologies/javase/javase-jdk8-downloads.html
	#VERSION=$(curl -s $WEB|grep -E x64.$EXTENSION|grep linux|rev|cut -d- -f3|rev)
	VERSION=8u261
	SOURCES=$PRGNAM-$VERSION-linux-x64.$EXTENSION
	DOWNLOAD=https://download.oracle.com/otn/java/jdk/8u261-b12/a4634525489241b9a9e1aa73d9e118e6/jdk-8u261-linux-x64.tar.gz
}

# Empezamos a crear el paquete
F_compilar(){
DVER=1.8.0_$(printf $VERSION|cut -du -f2)
mkdir -p $PKG/etc/profile.d
echo "#!/bin/csh
setenv JAVA_HOME /usr/lib${LIBDIRSUFFIX}/java
setenv MANPATH \${MANPATH}:\${JAVA_HOME}/man
setenv PATH \${PATH}:\${JAVA_HOME}/bin:\${JAVA_HOME}/jre/bin" >$PKG/etc/profile.d/jdk.csh

echo "#!/bin/sh
export JAVA_HOME=/usr/lib${LIBDIRSUFFIX}/java
export MANPATH=\"\${MANPATH}:\${JAVA_HOME}/man\"
export PATH=\"\${PATH}:\${JAVA_HOME}/bin:\${JAVA_HOME}/jre/bin\"" >$PKG/etc/profile.d/jdk.sh
	chmod +x $PKG/etc/profile.d/jdk.sh
	chmod +x $PKG/etc/profile.d/jdk.csh

mkdir -p $PKG/usr/lib${LIBDIRSUFFIX}
( cd $PKG/usr/lib${LIBDIRSUFFIX}
  mv ${TMP}/${PRGNAM}${DVER} java
  ln -sf java ${PRGNAM}${DVER}
)


	mkdir -p $PKG/usr/lib${LIBDIRSUFFIX}/mozilla/plugins
	cd $PKG/usr/lib${LIBDIRSUFFIX}/mozilla/plugins
	ln -sf /usr/lib${LIBDIRSUFFIX}/java/jre/lib/amd64/libnpjp2.so libnpjp2.so

	cd $PKG/usr/lib${LIBDIRSUFFIX}
	ln -sf ./java/jre/lib/amd64/server/libjvm.so .

# Entrada a escritorio
mkdir -p $PKG/usr/share/{applications,icons,mime}
cp -a $PKG/usr/lib${LIBDIRSUFFIX}/java/jre/lib/desktop/applications/* \
  $PKG/usr/share/applications/
cp -a $PKG/usr/lib${LIBDIRSUFFIX}/java/jre/lib/desktop/icons/hicolor \
  $PKG/usr/share/icons/
cp -a $PKG/usr/lib${LIBDIRSUFFIX}/java/jre/lib/desktop/mime/packages \
  $PKG/usr/share/mime/

# Si el sistema tiene jre ya no es necesario ya que este paquete incluye jre
if [ -f /var/log/packages/jre-[0-9]* ]; then
echo ""
echo "Se detecto en el sistema el paquete Jre..."
echo "Se eliminara antes de instalar jdk..."
echo ""
sleep 1
removepkg /var/log/packages/jre-[0-9]*
fi

# Ejecutamos l script que define las variables de sistema asi no es necesraio reiniciar
sh $PKG/etc/profile.d/jdk.sh
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Comprobamos version instalada del script
f_versionInstalada
#Si no existe el fichero se descargara
f_download
#Descomprimir sources
f_descomprimir
#Cd a ruta
f_cd
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales