#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20220923

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=hashcat
	EXTENSION=tar.gz
	GESTOR=wget
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=https://github.com/$PRGNAM/$PRGNAM
	VERSION=$(curl -s $WEB/tags|grep $EXTENSION|head -1|cut -d / -f7|cut -d t -f-1|sed 's/.$//g'|cut -d v -f2)
	SOURCES=v$VERSION.$EXTENSION
	CD=$PRGNAM-$VERSION
	DOWNLOAD=$WEB/archive/$SOURCES
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo 
echo "$VERDE"Compilando ..."$CIERRE"
sleep 1

# Forzamos compilar con las liberias de sistema
rm -rf deps/{OpenCL-Headers,xxHash}
make PREFIX=/usr SHARED=1 USE_SYSTEM_OPENCL=1 USE_SYSTEM_XXHASH=1 LIBRARY_FOLDER=/usr/lib${LIBDIRSUFFIX}||exit 1
make PREFIX=/usr SHARED=1 USE_SYSTEM_OPENCL=1 USE_SYSTEM_XXHASH=1 LIBRARY_FOLDER=/usr/lib${LIBDIRSUFFIX} DESTDIR=$PKG install||exit 1
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Comprobamos version instalada del paquete
f_versionInstalada
#Si no existe el fichero se descargara
f_download
#Descomprimir sources
f_descomprimir
#Cd a ruta
f_cd
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales