#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20170318
CATEGORIA="Editores de audio"

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=audacity
	SRCNAM=Audacity
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=https://github.com/audacity/audacity/releases
	VERSION=`curl -s $WEB|grep [0-9].tar.gz|head -1|cut -d- -f2|cut -d t -f-1|sed 's/.$//g'`
	EXTENSION=tar.gz
	SOURCES=$SRCNAM-$VERSION.$EXTENSION
	DOWNLOAD=https://github.com/audacity/audacity/archive/$SOURCES
}

# Comprobar dependencias
F_dependencias(){
DEPENDENCIAS="libiec61883 libxml++ libconfig libffado celt wxGTK3 jack-audio-connection-kit ffmpeg ladspa_sdk lame soundtouch twolame vamp-plugin-sdk serd sord lv2 sratom lilv suil"
f_dependencias
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){  
# Configuramos paquete
echo ""
echo "$VERDE"Configurando ..."$CIERRE"
sleep 1

# fix vamp plugin search path on x86_64 - thanks to B. Watson
sed -i "s,lib/vamp,lib$LIBDIRSUFFIX/vamp,g" \
  lib-src/libvamp/src/vamp-hostsdk/PluginHostAdapter.cpp || true

# Patch
echo "ZGlmZiAtTmF1ciBhdWRhY2l0eS1zcmMtMi4wLjYtb3JpZy9zcmMvRkZtcGVnLmggYXVkYWNpdHkt
c3JjLTIuMC42L3NyYy9GRm1wZWcuaAotLS0gYXVkYWNpdHktc3JjLTIuMC42LW9yaWcvc3JjL0ZG
bXBlZy5oCTIwMTQtMDktMjggMjE6NTQ6NTUuMTU5NjM2MjA4IC0wNDAwCisrKyBhdWRhY2l0eS1z
cmMtMi4wLjYvc3JjL0ZGbXBlZy5oCTIwMTQtMDktMjggMjE6NTU6MTEuMjQ2Mjc2NzY2IC0wNDAw
CkBAIC02ODgsNyArNjg4LDcgQEAKICAgIEZGTVBFR19GVU5DVElPTl9XSVRIX1JFVFVSTigKICAg
ICAgIEFWT3V0cHV0Rm9ybWF0KiwKICAgICAgIGF2X29mb3JtYXRfbmV4dCwKLSAgICAgIChBVk91
dHB1dEZvcm1hdCAqZiksCisgICAgICAoY29uc3QgQVZPdXRwdXRGb3JtYXQgKmYpLAogICAgICAg
KGYpCiAgICApOwogICAgRkZNUEVHX0ZVTkNUSU9OX1dJVEhfUkVUVVJOKApAQCAtNzU1LDcgKzc1
NSw3IEBACiAgICBGRk1QRUdfRlVOQ1RJT05fV0lUSF9SRVRVUk4oCiAgICAgICBpbnQsCiAgICAg
ICBhdl9maWZvX3NpemUsCi0gICAgICAoQVZGaWZvQnVmZmVyICpmKSwKKyAgICAgIChjb25zdCBB
VkZpZm9CdWZmZXIgKmYpLAogICAgICAgKGYpCiAgICApOwogICAgRkZNUEVHX0ZVTkNUSU9OX1dJ
VEhfUkVUVVJOKApAQCAtODAxLDcgKzgwMSw3IEBACiAgICBGRk1QRUdfRlVOQ1RJT05fV0lUSF9S
RVRVUk4oCiAgICAgICBBVkRpY3Rpb25hcnlFbnRyeSAqLAogICAgICAgYXZfZGljdF9nZXQsCi0g
ICAgICAoQVZEaWN0aW9uYXJ5ICptLCBjb25zdCBjaGFyICprZXksIGNvbnN0IEFWRGljdGlvbmFy
eUVudHJ5ICpwcmV2LCBpbnQgZmxhZ3MpLAorICAgICAgKGNvbnN0IEFWRGljdGlvbmFyeSAqbSwg
Y29uc3QgY2hhciAqa2V5LCBjb25zdCBBVkRpY3Rpb25hcnlFbnRyeSAqcHJldiwgaW50IGZsYWdz
KSwKICAgICAgIChtLCBrZXksIHByZXYsIGZsYWdzKQogICAgKTsKICAgIEZGTVBFR19GVU5DVElP
Tl9XSVRIX1JFVFVSTigK" | base64 -d > $TMP/audacity-ffmpeg.patch
patch -p1 < $TMP/audacity-ffmpeg.patch
  
# libsoxr is the new default resampling library
LDFLAGS="-L/usr/lib$LIBDIRSUFFIX" \
CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \

   autoreconf -vi

  ./configure \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --without-libsamplerate

echo ""
echo "$VERDE"Compilamos ..."$CIERRE"
sleep 1
make  || exit 1
make install DESTDIR=$PKG
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del script
f_versionInstalada
# Comprobar dependencias
F_dependencias
#Si no existe el fichero se descargara
f_download
#Preparamos entorno
f_preparar
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales