#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20170113
CATEGORIA="Reproductores multimedia"

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=clementine
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=https://www.clementine-player.org/es/downloads
	VERSION=`curl -s $WEB|grep Clementine|grep .tar.gz|head -1|cut -d "/" -f 7|cut -d t -f-1|sed 's/.$//g'`
	EXTENSION=tar.gz
	SOURCES=$VERSION.$EXTENSION
	SRCNAM=Clementine-$VERSION
	DOWNLOAD=https://github.com/clementine-player/Clementine/archive/$SOURCES
}

# Comprobar dependencias
F_dependencias(){
DEPENDENCIAS="x264 twolame libmpeg2 libdvdcss lame opencore-amr amrnb amrwb libass libcdaudio celt libdc1394 libdca faac faad2 flite fluidsynth gsm libkate liblrdf libmodplug libmimic libmusicbrainz libofa libdv schroedinger libquicktime libwebp lv2 musepack-tools OpenAL opencv soundtouch swfdec xvidcore rtmpdump schroedinger TiMidity++ xvidcore ffmpeg chromaprint cryptopp libechonest pytz six python-dateutil python-gflags protobuf gst-plugins-bad gst-plugins-ugly gst-libav sparsehash"
f_dependencias
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){

if [ $VERSION = 1.3.1 ]; then
echo "LS0tIENsZW1lbnRpbmUtMS4zLjEvc3JjL211c2ljYnJhaW56L2Nocm9tYXByaW50ZXIuY3BwLm9y
aWcJMjAxNi0wNC0xOSAyMjowODozNS4wMDAwMDAwMDAgKzA3MDAKKysrIENsZW1lbnRpbmUtMS4z
LjEvc3JjL211c2ljYnJhaW56L2Nocm9tYXByaW50ZXIuY3BwCTIwMTctMDEtMDIgMDg6MDc6MTQu
MzM0OTgzOTYyICswNzAwCkBAIC0xNDMsMTYgKzE0MywyNCBAQAogICBDaHJvbWFwcmludENvbnRl
eHQqIGNocm9tYXByaW50ID0KICAgICAgIGNocm9tYXByaW50X25ldyhDSFJPTUFQUklOVF9BTEdP
UklUSE1fREVGQVVMVCk7CiAgIGNocm9tYXByaW50X3N0YXJ0KGNocm9tYXByaW50LCBrRGVjb2Rl
UmF0ZSwga0RlY29kZUNoYW5uZWxzKTsKLSAgY2hyb21hcHJpbnRfZmVlZChjaHJvbWFwcmludCwg
cmVpbnRlcnByZXRfY2FzdDx2b2lkKj4oZGF0YS5kYXRhKCkpLAorICBjaHJvbWFwcmludF9mZWVk
KGNocm9tYXByaW50LCByZWludGVycHJldF9jYXN0PGludDE2X3QgKj4oZGF0YS5kYXRhKCkpLAog
ICAgICAgICAgICAgICAgICAgIGRhdGEuc2l6ZSgpIC8gMik7CiAgIGNocm9tYXByaW50X2Zpbmlz
aChjaHJvbWFwcmludCk7CiAKLSAgdm9pZCogZnByaW50ID0gbnVsbHB0cjsKICAgaW50IHNpemUg
PSAwOworCisjaWYgQ0hST01BUFJJTlRfVkVSU0lPTl9NQUpPUiA+PSAxICYmIENIUk9NQVBSSU5U
X1ZFUlNJT05fTUlOT1IgPj0gNAorICB1X2ludDMyX3QgKmZwcmludCA9IG51bGxwdHI7CisgIGNo
YXIgKmVuY29kZWQgPSBudWxscHRyOworI2Vsc2UKKyAgdm9pZCAqZnByaW50ID0gbnVsbHB0cjsK
KyAgdm9pZCAqZW5jb2RlZCA9IG51bGxwdHI7CisjZW5kaWYKKwogICBpbnQgcmV0ID0gY2hyb21h
cHJpbnRfZ2V0X3Jhd19maW5nZXJwcmludChjaHJvbWFwcmludCwgJmZwcmludCwgJnNpemUpOwor
CiAgIFFCeXRlQXJyYXkgZmluZ2VycHJpbnQ7CiAgIGlmIChyZXQgPT0gMSkgewotICAgIHZvaWQq
IGVuY29kZWQgPSBudWxscHRyOwogICAgIGludCBlbmNvZGVkX3NpemUgPSAwOwogICAgIGNocm9t
YXByaW50X2VuY29kZV9maW5nZXJwcmludChmcHJpbnQsIHNpemUsIENIUk9NQVBSSU5UX0FMR09S
SVRITV9ERUZBVUxULAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAmZW5jb2Rl
ZCwgJmVuY29kZWRfc2l6ZSwgMSk7Cg==
" | base64 -d > $TMP/chromaprint-1.4.patch

patch -p1 < $TMP/chromaprint-1.4.patch

echo "LS0tIGEvc3JjL2NvcmUvZGF0YWJhc2UuY3BwCisrKyBiL3NyYy9jb3JlL2RhdGFiYXNlLmNwcApA
QCAtMjY1LDYgKzI2NSwxNiBAQAogICBTdGF0aWNJbml0KCk7CgogICB7CisjaWZkZWYgU1FMSVRF
X0RCQ09ORklHX0VOQUJMRV9GVFMzX1RPS0VOSVpFUgorICAgIFFWYXJpYW50IHYgPSBkYi5kcml2
ZXIoKS0+aGFuZGxlKCk7CisgICAgaWYgKHYuaXNWYWxpZCgpICYmIHFzdHJjbXAodi50eXBlTmFt
ZSgpLCAic3FsaXRlMyoiKSA9PSAwKSB7CisgICAgICBzcWxpdGUzKiBoYW5kbGUgPSAqc3RhdGlj
X2Nhc3Q8c3FsaXRlMyoqPih2LmRhdGEoKSk7CisgICAgICBpZiAoaGFuZGxlKSB7ICAgICAgICAg
ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAKKyAgICAgICAgc3FsaXRlM19kYl9jb25maWcoaGFuZGxlLCBTUUxJVEVf
REJDT05GSUdfRU5BQkxFX0ZUUzNfVE9LRU5JWkVSLCAxLCBOVUxMKTsgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
IAorICAgICAgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCisgICAgfSAgICAg
ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKKyNlbmRpZiAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAgICAgIAorICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgCiAgICAgUVNxbFF1ZXJ5IHNldF9mdHNfdG9rZW5pemVyKCJTRUxFQ1QgZnRzM190b2tl
bml6ZXIoOm5hbWUsIDpwb2ludGVyKSIsIGRiKTsKICAgICBzZXRfZnRzX3Rva2VuaXplci5iaW5k
VmFsdWUoIjpuYW1lIiwgInVuaWNvZGUiKTsKICAgICBzZXRfZnRzX3Rva2VuaXplci5iaW5kVmFs
dWUoCg==" | base64 -d > $TMP/sqlite.patch
patch -p1 -i $TMP/sqlite.patch || exit 1
fi

echo ""
echo "$VERDE"Compilando ..."$CIERRE"
sleep 1

mkdir build
cd build
  cmake \
	-DCMAKE_C_FLAGS:STRING="$SLKCFLAGS" \
	-DCMAKE_CXX_FLAGS:STRING="$SLKCFLAGS" \
	-DCMAKE_INSTALL_PREFIX=/usr \
	-DLIB_SUFFIX=${LIBDIRSUFFIX} \
	-DMAN_INSTALL_DIR=/usr/man \
	-DCMAKE_BUILD_TYPE=Release \
	..
  make all CFLAGS="-fPIC" PMFLAGS="-DNEWBUFFER"  || exit 1
  make install DESTDIR=$PKG
cd ..
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Comprobamos version instalada del script
f_versionInstalada
#Compronar dependencias
F_dependencias
#Si no existe el fichero se descargara
f_download
#Preparamos entorno
f_preparar
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales