#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20170526
CATEGORIA="Reproductores multimedia"

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=kodi
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=https://github.com/xbmc/xbmc
	VERSION=$(curl -s $WEB/releases/latest|cut -d "/" -f8|cut -d '"' -f1|cut -d- -f-1)
	RAMA=$(curl -s $WEB/releases/latest|cut -d "/" -f8|cut -d '"' -f1|cut -d- -f2)
	SRCNAM=xbmc
	EXTENSION=tar.gz
	SOURCES=$SRCNAM-$VERSION-$RAMA.$EXTENSION
	CD=$SRCNAM-$VERSION-$RAMA
	DOWNLOAD=$WEB/archive/$VERSION-$RAMA/$SOURCES
}

# Comprobar dependencias
F_dependencias(){
DEPENDENCIAS="lockdev lockdev platform libcec python3 python3-PyYAML lirc dcadec libass libmpeg2 tinyxml jdk yajl bluray-keys libaacs libbdplus libbluray libmicrohttpd crossguid libnfs python-gattlib pybluez" 
f_dependencias
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo 
echo "$VERDE"Configurando ..."$CIERRE"
sleep 1

echo "
LS0tIHRvb2xzL2RlcGVuZHMvbmF0aXZlL1RleHR1cmVQYWNrZXIvTWFrZWZpbGUub2xkCTIwMTUt
MDMtMTcgMjI6Mjk6MTguODgwMDI5NTA5ICswMTAwCisrKyB0b29scy9kZXBlbmRzL25hdGl2ZS9U
ZXh0dXJlUGFja2VyL01ha2VmaWxlCTIwMTUtMDMtMTcgMjI6Mjk6NDEuNDU5NjcxNjc5ICswMTAw
CkBAIC05LDE0ICs5LDEwIEBACiAKIGlmZXEgKCQoTkFUSVZFUExBVEZPUk0pLCkKICAgUExBVEZP
Uk0gPSBuYXRpdmUKLSAgRVhUUkFfQ09ORklHVVJFID0gLS1lbmFibGUtc3RhdGljCiBlbHNlCiAg
IFBMQVRGT1JNID0gJChOQVRJVkVQTEFURk9STSkKIGVuZGlmCiAKLWlmZXEgKCQoTkFUSVZFX09T
KSwgbGludXgpCi0gIEVYVFJBX0NPTkZJR1VSRSA9IC0tZW5hYmxlLXN0YXRpYwotZW5kaWYKIGlm
ZXEgKCQoTkFUSVZFX09TKSwgYW5kcm9pZCkKICAgRVhUUkFfQ09ORklHVVJFID0gLS1lbmFibGUt
c3RhdGljCiBlbmRpZgo=
" | base64 -d > $TMP/kodi-texturepacker.patch
patch -p0 -i $TMP/kodi-texturepacker.patch || exit 1

export PATH="$PATH:$PWD/tools/depends/native/JsonSchemaBuilder/bin"

./bootstrap

CFLAGS="$SLKCFLAGS $AFPFS_NGFLAGS" \
CXXFLAGS="$SLKCFLAGS $AFPFS_NGFLAGS" \
LDFLAGS="-L/usr/lib${LIBDIRSUFFIX}" \
./configure \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --docdir=/usr/doc/$PRGNAM-$VERSION \
  --enable-static=no \
  --disable-debug \
  --enable-gl \
  --enable-mid \
  --enable-goom \
  --enable-alsa \
  --disable-asap-codec \
  --enable-pulse \
  --enable-webserver \
  --enable-shared-libraries \
  --with-ffmpeg=shared \
  --build=$ARCH-slackware-linux
    
echo 
echo "$VERDE"Compilando ..."$CIERRE"
sleep 1
make VERBOSE=1 || exit 1

make install DESTDIR=$PKG || exit 1
python -m compileall $PKG/usr/share/$PRGNAM/addons/service.xbmc.versioncheck
install -m 0755 tools/TexturePacker/TexturePacker $PKG/usr/lib${LIBDIRSUFFIX}/$PRGNAM
find $PKG \( -name "Makefile*" -o -name "*cmake*" -o -name "*\.in" \) -exec rm -f '{}' \;
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del paquete
f_versionInstalada
#Compronar dependencias
F_dependencias
#Si no existe el fichero se descargara
f_download
#Preparamos entorno
f_preparar
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales