#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20161103
CATEGORIA="Editores de video"

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	WEB=http://www.openshot.org/download/
	VERSION=`curl -s $WEB | grep Version | head -1 | cut -d ">" -f2 | cut -d "<" -f-1 | sed "s/ //g"`
	RAMA=`echo $VERSION | cut -d "." -f-2`
	PRGNAM=openshot
	echo -ne "\033]2;${PRGNAM}_updater\007"
	EXTENSION=tar.gz
	SOURCES=$PRGNAM-qt-$VERSION.$EXTENSION
	DOWNLOAD=https://launchpad.net/$PRGNAM/$RAMA/$VERSION/+download/$SOURCES
}

# Comprobar dependencias
F_dependencias(){
DEPENDENCIAS="qt5 python3 libffado celt jack-audio-connection-kit python3-httplib2 qt5-webkit python3-sip python3-PyQt5 python3-pyzmq zeromq ffmpeg unittest-cpp libopenshot-audio libopenshot"
f_dependencias
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo 
echo "$VERDE"Compilando ..."$CIERRE"
sleep 1
python3 setup.py install --root=$PKG
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del paquete
f_versionInstalada
#Compronar dependencias
F_dependencias
#Si no existe el fichero se descargara
f_download
#Preparamos entorno
f_preparar
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales