#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20170526
CATEGORIA="Reproductores multimedia"

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=smplayer
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=http://www.smplayer.info/es/downloads
	VERSION=$(curl -s $WEB|grep .tar.bz2|head -1|cut -d ":" -f2|cut -d "/" -f5|cut -d- -f-2|cut -d- -f2 |sed 's/.tar.bz2">smplayer//g'|sed "s/ //g")
	EXTENSION=tar.bz2
	SOURCES=$PRGNAM-$VERSION.$EXTENSION
	CD=$PRGNAM-$VERSION
	DOWNLOAD=http://downloads.sourceforge.net/$PRGNAM/$SOURCES
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
# Configuramos paquete
echo ""
echo "$VERDE"Configurando y compilano..."$CIERRE"
sleep 1

sed -i "/^PREFIX/s/=.*$/=\/usr/;
        /^DOC_PATH/s/\/.*$/\/doc\/$PRGNAM-$VERSION/;
        s/share\/man/man/g;
        s/^QMAKE_OPTS=/QMAKE_OPTS+=/" Makefile

QMAKE_OPTS="QMAKE_CXXFLAGS=\"$SLKCFLAGS\"" \
make || exit 1
make install DESTDIR=$PKG
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Comprobamos version instalada del script
f_versionInstalada
#Si no existe el fichero se descargara
f_download
#Preparamos entorno
f_preparar
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales