#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20170209
CATEGORIA="Reproductores multimedia"

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=vlc
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=http://download.videolan.org
	VERSION=$(curl -s $WEB/$PRGNAM/ | grep -Po 'href="\K.*(?=")' | sed 's/\///g' | sort -g | tail -1)
	EXTENSION=tar.xz
	SOURCES=$PRGNAM-$VERSION.$EXTENSION
	DOWNLOAD=$WEB/$PRGNAM/$VERSION/$SOURCES
}

# Comprobar dependencias
F_dependencias(){
DEPENDENCIAS="libiec61883 libxml++ libconfig libffado celt libass libdc1394 libdvbpsi libmpeg2 libupnp lua portaudio twolame opus ffmpeg libwebp gsm opencv libtar libkate faac libdca libebml libmatroska libshout speex jack-audio-connection-kit libsidplay2 zvbi faad2 libavc1394 libmodplug libcuefile libreplaygain musepack-tools vcdimager dirac gnome-vfs live555 rtmpdump libdvdcss fluidsynth schroedinger libminizip chromaprint x264 x265 bluray-keys libaacs libbdplus libbluray"
f_dependencias
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo 
echo "$VERDE"Configurando ..."$CIERRE"
sleep 1

echo "LS0tIG1vZHVsZXMvdmlzdWFsaXphdGlvbi9wcm9qZWN0bS5jcHAub3JpZwkyMDEzLTA5LTEzIDAx
OjE4OjM0LjAwMDAwMDAwMCArMTAwMAorKysgbW9kdWxlcy92aXN1YWxpemF0aW9uL3Byb2plY3Rt
LmNwcAkyMDE0LTA5LTA0IDE0OjUzOjIxLjUxMDI0MjAzNiArMTAwMApAQCAtNzksOCArNzksOCBA
QAogIyBkZWZpbmUgRk9OVF9QQVRIX01FTlUgIkM6XFxXSU5ET1dTXFxGb250c1xcYXJpYWwudHRm
IgogIyBkZWZpbmUgUFJFU0VUX1BBVEggICAgTlVMTAogI2Vsc2UKLSMgZGVmaW5lIEZPTlRfUEFU
SCAgICAgICIvdXNyL3NoYXJlL2ZvbnRzL3RydWV0eXBlL3R0Zi1kZWphdnUvRGVqYVZ1U2Fucy50
dGYiCi0jIGRlZmluZSBGT05UX1BBVEhfTUVOVSAiL3Vzci9zaGFyZS9mb250cy90cnVldHlwZS90
dGYtZGVqYXZ1L0RlamFWdVNhbnNNb25vLnR0ZiIKKyMgZGVmaW5lIEZPTlRfUEFUSCAgICAgICIv
dXNyL3NoYXJlL2ZvbnRzL1RURi9EZWphVnVTYW5zLnR0ZiIKKyMgZGVmaW5lIEZPTlRfUEFUSF9N
RU5VICIvdXNyL3NoYXJlL2ZvbnRzL1RURi9EZWphVnVTYW5zTW9uby50dGYiCiAjIGRlZmluZSBQ
UkVTRVRfUEFUSCAgICAiL3Vzci9zaGFyZS9wcm9qZWN0TS9wcmVzZXRzIgogI2VuZGlmCiAK
" | base64 -d > $TMP/patch-projectM-fontpath.diff

patch -p0 < $TMP/patch-projectM-fontpath.diff || exit 1

echo "LS0tIGJpbi9NYWtlZmlsZS5hbS5vcmlnCTIwMTUtMDYtMDMgMTA6NDk6NTEuMjY2MjgyNzM2ICsx
MDAwCisrKyBiaW4vTWFrZWZpbGUuYW0JMjAxNS0wNi0wMyAxMDo1MDoyMC40NjkyODIzMTAgKzEw
MDAKQEAgLTcyLDYgKzcyLDEwIEBACiB2bGNfY2FjaGVfZ2VuX0RFUEVOREVOQ0lFUyA9IHZsY193
aW4zMl9yYy4kKE9CSkVYVCkKIGVuZGlmCiAKK2lmIEhBVkVfR09CSkVDVAordmxjX2NhY2hlX2dl
bl9MREFERCArPSAkKEdPQkpFQ1RfTElCUykKK2VuZGlmCisKICMKICMgUGx1Zy1pbnMgY2FjaGUK
ICMKLS0tIGNvbmZpZ3VyZS5hYy5vcmlnCTIwMTUtMDYtMDMgMTA6NTM6MjIuMjk5Mjc5NjU3ICsx
MDAwCisrKyBjb25maWd1cmUuYWMJMjAxNS0wNi0wMyAwOTo0NDozMy4zMzgzMzk4ODkgKzEwMDAK
QEAgLTc2Miw2ICs3NjIsMTIgQEAKICAgICBdKQogXSkKIAorZG5sCitkbmwgQ2hlY2sgZm9yIGdv
YmplY3QKK2RubAoraGF2ZV9nb2JqZWN0PSJubyIKK1BLR19DSEVDS19NT0RVTEVTKFtHT0JKRUNU
XSwgW2dvYmplY3QtMi4wXSwgWyBoYXZlX2dvYmplY3Q9InllcyIgXSkKK0FNX0NPTkRJVElPTkFM
KEhBVkVfR09CSkVDVCwgWyB0ZXN0ICIke2hhdmVfZ29iamVjdH0iID0gInllcyIgXSkKIAogZG5s
CiBkbmwgQ2hlY2sgZm9yIHpsaWIuaCBhbmQgLWx6IGFsb25nIHdpdGggc3lzdGVtIC1sbWluaXpp
cCBpZiBhdmFpbGFibGUK" | base64 -d > $TMP/patch_vlc_cache_gen.diff

patch -p0 < $TMP/patch_vlc_cache_gen.diff || exit 1

echo "aHR0cHM6Ly9naXN0LmdpdGh1Yi5jb20va2Fyb2xoZXJic3QvZmI5ZTNkOGY2YmEwNWYxZjVkNTQK
Rm9yIHVzZSB1bnRpbCB1cHN0cmVhbSBldmVyIGFjY2VwdHMgdGhpcyBwYXRjaCBvciBmaXhlcyBp
dCB0aGVtc2xldmVzCi0tLSBhL2NvbmZpZ3VyZS5hYworKysgYi9jb25maWd1cmUuYWMKQEAgLTM3
MDksNyArMzcwOSw4IEBACiAgIF0pCiBdKQogQVNfSUYoW3Rlc3QgIiR7ZW5hYmxlX3F0fSIgIT0g
Im5vIl0sIFsKLSAgUEtHX0NIRUNLX01PRFVMRVMoW1FUXSwgW1F0NUNvcmUgPj0gNS4xLjAgUXQ1
V2lkZ2V0cyBRdDVHdWldLCBbCisgIEFTX0lGKFt0ZXN0ICIke2VuYWJsZV9xdH0iICE9ICI0Il0s
IFsKKyAgICBQS0dfQ0hFQ0tfTU9EVUxFUyhbUVRdLCBbUXQ1Q29yZSA+PSA1LjEuMCBRdDVXaWRn
ZXRzIFF0NUd1aV0sIFsKICAgICAgIFBLR19DSEVDS19NT0RVTEVTKFtRVFgxMV0sIFtRdDVYMTFF
eHRyYXNdLCBbCiAgICAgICAgICAgVkxDX0FERF9MSUJTKFtxdDRdLFske1FUWDExX0xJQlN9XSkK
ICAgICAgICAgICBWTENfQUREX0NYWEZMQUdTKFtxdDRdLFske1FUWDExX0NGTEFHU30gLURRVDVf
SEFTX1gxMV0pCkBAIC0zNzIxLDIwICszNzIyLDIzIEBACiAgICAgICBBQ19QQVRIX1BST0dTKE1P
QywgW21vYy1xdDUgbW9jXSwgbW9jLCBbIiR7UVRfSE9TVF9QQVRIfSIgIiR7UVRfUEFUSH0vYmlu
IiAiJHtDT05UUklCX0RJUn0vYmluIl0pCiAgICAgICBBQ19QQVRIX1BST0dTKFJDQywgW3JjYy1x
dDUgcmNjXSwgcmNjLCBbIiR7UVRfSE9TVF9QQVRIfSIgIiR7UVRfUEFUSH0vYmluIiAiJHtDT05U
UklCX0RJUn0vYmluIl0pCiAgICAgICBBQ19QQVRIX1BST0dTKFVJQywgW3VpYy1xdDUgdWljXSwg
dWljLCBbIiR7UVRfSE9TVF9QQVRIfSIgIiR7UVRfUEFUSH0vYmluIiAiJHtDT05UUklCX0RJUn0v
YmluIl0pCisgICAgICBlbmFibGVfcXQ9IjUiCi0gICAgXSwgWwotICAgICAgUEtHX0NIRUNLX01P
RFVMRVMoW1FUXSwgW1F0Q29yZSBRdEd1aSA+PSA0LjYuMF0sLCBbCi0gICAgICAgIEFTX0lGKFt0
ZXN0IC1uICIke2VuYWJsZV9xdH0iXSxbCi0gICAgICAgICAgQUNfTVNHX0VSUk9SKFske1FUX1BL
R19FUlJPUlN9Ll0pCi0gICAgICAgIF0sWwotICAgICAgICAgIEFDX01TR19XQVJOKFske1FUX1BL
R19FUlJPUlN9Ll0pCi0gICAgICAgIF0pCi0gICAgICAgIGVuYWJsZV9xdD0ibm8iCisgICAgXSkK
KyAgXSkKKyAgQVNfSUYoW3Rlc3QgIiR7ZW5hYmxlX3F0fSIgIT0gIjUiXSwgWworICAgIFBLR19D
SEVDS19NT0RVTEVTKFtRVF0sIFtRdENvcmUgUXRHdWkgPj0gNC42LjBdLCwgWworICAgICAgQVNf
SUYoW3Rlc3QgLW4gIiR7ZW5hYmxlX3F0fSJdLFsKKyAgICAgICAgQUNfTVNHX0VSUk9SKFske1FU
X1BLR19FUlJPUlN9Ll0pCisgICAgICBdLFsKKyAgICAgICAgQUNfTVNHX1dBUk4oWyR7UVRfUEtH
X0VSUk9SU30uXSkKICAgICAgIF0pCi0gICAgICBRVF9QQVRIPSIkKGV2YWwgJFBLR19DT05GSUcg
LS12YXJpYWJsZT1leGVjX3ByZWZpeCBRdENvcmUpIgotICAgICAgQUNfUEFUSF9QUk9HUyhNT0Ms
IFttb2MtcXQ0IG1vY10sIG1vYywgWyIke1FUX1BBVEh9L2JpbiIgIiR7Q09OVFJJQl9ESVJ9L2Jp
biJdKQotICAgICAgQUNfUEFUSF9QUk9HKFJDQywgcmNjLCByY2MsIFske1FUX1BBVEh9L2JpbiAk
e0NPTlRSSUJfRElSfS9iaW5dKQotICAgICAgQUNfUEFUSF9QUk9HUyhVSUMsIFt1aWMtcXQ0IHVp
Y10sIHVpYywgWyIke1FUX1BBVEh9L2JpbiIgIiR7Q09OVFJJQl9ESVJ9L2JpbiJdKQorICAgICAg
ZW5hYmxlX3F0PSJubyIKICAgICBdKQorICAgIFFUX1BBVEg9IiQoZXZhbCAkUEtHX0NPTkZJRyAt
LXZhcmlhYmxlPWV4ZWNfcHJlZml4IFF0Q29yZSkiCisgICAgQUNfUEFUSF9QUk9HUyhNT0MsIFtt
b2MtcXQ0IG1vY10sIG1vYywgWyIke1FUX1BBVEh9L2JpbiIgIiR7Q09OVFJJQl9ESVJ9L2JpbiJd
KQorICAgIEFDX1BBVEhfUFJPRyhSQ0MsIHJjYywgcmNjLCBbJHtRVF9QQVRIfS9iaW4gJHtDT05U
UklCX0RJUn0vYmluXSkKKyAgICBBQ19QQVRIX1BST0dTKFVJQywgW3VpYy1xdDQgdWljXSwgdWlj
LCBbIiR7UVRfUEFUSH0vYmluIiAiJHtDT05UUklCX0RJUn0vYmluIl0pCisgIF0pCiBdKQogQVNf
SUYoW3Rlc3QgIiR7ZW5hYmxlX3F0fSIgIT0gIm5vIl0sIFsKICAgVkxDX0FERF9QTFVHSU4oW3F0
NF0pCgo=" | base64 -d > $TMP/qt4-select.patch

patch -p1 < $TMP/qt4-select.patch || exit 1

autoreconf -fiv

CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
LDFLAGS="$SLKLDFLAGS" \
./configure \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --sysconfdir=/etc \
  --mandir=/usr/man \
  --docdir=/usr/doc/vlc-$VERSION \
  --localstatedir=/var \
  --enable-run-as-root \
  --build=$ARCH-slackware-linux \
  --enable-qt=4 \
  --enable-merge-ffmpeg \
  --with-kde-solid=no \
  
echo 
echo "$VERDE"Compilando ..."$CIERRE"
sleep 1
make  || exit 1
make install DESTDIR=$PKG || exit 1

mkdir -p $PKG/$(cd /usr/share/vim/vim*/syntax ; pwd)
cp extras/analyser/vlc.vim $PKG/$(cd /usr/share/vim/vim*/syntax ; pwd)/
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del script
f_versionInstalada
# Comprobar dependencias
F_dependencias
#Si no existe el fichero se descargara
f_download
#Preparamos entorno
f_preparar
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales