#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20210302

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=rtl8814au
	GESTOR=git
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=https://github.com/aircrack-ng/$PRGNAM
	RAMA=5.8.5.1
	VERSION="${RAMA}_$(curl -s $WEB/tree/v$RAMA|grep commit/|grep src=|cut -d/ -f6|cut -c 1-7)"
	SOURCES=$PRGNAM
	CD=$PRGNAM
	DOWNLOAD="-b v$RAMA $WEB"
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo 
echo "$VERDE"Compilando ..."$CIERRE"
sleep 1
if [ $(uname -r|cut -d- -f1|cut -d. -f-2) = 5.11 ]; then
echo "/Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj4Af/ASddABqLgp23UhxLCEI0mO6mW//motbj5kmcBBjK
0l9gqCS6jX76tEi95xHX+v7uc1qcAOtRmF2eT4DUVlR9RTnaQX9RbNmWJWj5nn8BeI90ni4tuhId
XB7ToztX3ws0RjFwH04qTN1vQnTGD+l7jnjNLD+yUXu824fJNwnnHMU/NhhhgnG+LlbhEkZmKqtt
vwbrOrlJqLSd3DdLIDbNAsHfY6Kqz9yfZXsiMvs1PqXtP43Eid3tZp5jQi3vt4M0u82Spyg7fshg
rnV8Sthszo77iVh8B/1fEQmktJe6c56osxRWoOijBRHVCP+RXENmnc0XGRl7BlCfoFiqI+1ph3bN
oQdRcnq9eesnOKezJT90pcRl8ijcdTl9+besd80QZZZr2yUTmSObuAAAAAOBGmZxvslXAAHDAoAQ
AADs/pbfscRn+wIAAAAABFla"|base64 -d > $TMP/patches.txz
tar xvf $TMP/patches.txz &>/dev/null
patch -p1 -i 5.11.patch || exit 1
fi
make || exit 1
mkdir -p $PKG/lib/modules/$(uname -r)/kernel/drivers/net/wireless/
make install MODDESTDIR=$PKG/lib/modules/$(uname -r)/kernel/drivers/net/wireless/|| exit 1
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Comprobamos version instalada del paquete
f_versionInstalada
#Si no existe el fichero se descargara
f_download
#Cd a ruta
f_cd
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales